// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: internal/infrastructure/server/grpc/proto/definitions/jobworker.proto

package jobworker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClaimWorkFilter struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	TenantCodes               []string               `protobuf:"bytes,1,rep,name=tenantCodes,proto3" json:"tenantCodes,omitempty"`
	ExcludeTenantCodes        []string               `protobuf:"bytes,2,rep,name=excludeTenantCodes,proto3" json:"excludeTenantCodes,omitempty"`
	TenantPatterns            []string               `protobuf:"bytes,3,rep,name=tenantPatterns,proto3" json:"tenantPatterns,omitempty"`
	ExcludeTenantPatterns     []string               `protobuf:"bytes,4,rep,name=excludeTenantPatterns,proto3" json:"excludeTenantPatterns,omitempty"`
	VNamespaces               []string               `protobuf:"bytes,5,rep,name=vNamespaces,proto3" json:"vNamespaces,omitempty"`
	ExcludeVNamespaces        []string               `protobuf:"bytes,6,rep,name=excludeVNamespaces,proto3" json:"excludeVNamespaces,omitempty"`
	VNamespacePatterns        []string               `protobuf:"bytes,7,rep,name=vNamespacePatterns,proto3" json:"vNamespacePatterns,omitempty"`
	ExcludeVNamespacePatterns []string               `protobuf:"bytes,8,rep,name=excludeVNamespacePatterns,proto3" json:"excludeVNamespacePatterns,omitempty"`
	QueueCodes                []string               `protobuf:"bytes,9,rep,name=queueCodes,proto3" json:"queueCodes,omitempty"`
	ExcludeQueueCodes         []string               `protobuf:"bytes,10,rep,name=excludeQueueCodes,proto3" json:"excludeQueueCodes,omitempty"`
	QueuePatterns             []string               `protobuf:"bytes,11,rep,name=queuePatterns,proto3" json:"queuePatterns,omitempty"`
	ExcludeQueuePatterns      []string               `protobuf:"bytes,12,rep,name=excludeQueuePatterns,proto3" json:"excludeQueuePatterns,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ClaimWorkFilter) Reset() {
	*x = ClaimWorkFilter{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_jobworker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimWorkFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimWorkFilter) ProtoMessage() {}

func (x *ClaimWorkFilter) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_jobworker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimWorkFilter.ProtoReflect.Descriptor instead.
func (*ClaimWorkFilter) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_jobworker_proto_rawDescGZIP(), []int{0}
}

func (x *ClaimWorkFilter) GetTenantCodes() []string {
	if x != nil {
		return x.TenantCodes
	}
	return nil
}

func (x *ClaimWorkFilter) GetExcludeTenantCodes() []string {
	if x != nil {
		return x.ExcludeTenantCodes
	}
	return nil
}

func (x *ClaimWorkFilter) GetTenantPatterns() []string {
	if x != nil {
		return x.TenantPatterns
	}
	return nil
}

func (x *ClaimWorkFilter) GetExcludeTenantPatterns() []string {
	if x != nil {
		return x.ExcludeTenantPatterns
	}
	return nil
}

func (x *ClaimWorkFilter) GetVNamespaces() []string {
	if x != nil {
		return x.VNamespaces
	}
	return nil
}

func (x *ClaimWorkFilter) GetExcludeVNamespaces() []string {
	if x != nil {
		return x.ExcludeVNamespaces
	}
	return nil
}

func (x *ClaimWorkFilter) GetVNamespacePatterns() []string {
	if x != nil {
		return x.VNamespacePatterns
	}
	return nil
}

func (x *ClaimWorkFilter) GetExcludeVNamespacePatterns() []string {
	if x != nil {
		return x.ExcludeVNamespacePatterns
	}
	return nil
}

func (x *ClaimWorkFilter) GetQueueCodes() []string {
	if x != nil {
		return x.QueueCodes
	}
	return nil
}

func (x *ClaimWorkFilter) GetExcludeQueueCodes() []string {
	if x != nil {
		return x.ExcludeQueueCodes
	}
	return nil
}

func (x *ClaimWorkFilter) GetQueuePatterns() []string {
	if x != nil {
		return x.QueuePatterns
	}
	return nil
}

func (x *ClaimWorkFilter) GetExcludeQueuePatterns() []string {
	if x != nil {
		return x.ExcludeQueuePatterns
	}
	return nil
}

type ClaimWorkCapacityPolicy struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	MaxQueueMessages     int32                  `protobuf:"varint,1,opt,name=maxQueueMessages,proto3" json:"maxQueueMessages,omitempty"`
	CurrentQueueMessages int32                  `protobuf:"varint,2,opt,name=currentQueueMessages,proto3" json:"currentQueueMessages,omitempty"`
	ClaimWorkFilter      *ClaimWorkFilter       `protobuf:"bytes,3,opt,name=claimWorkFilter,proto3" json:"claimWorkFilter,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ClaimWorkCapacityPolicy) Reset() {
	*x = ClaimWorkCapacityPolicy{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_jobworker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimWorkCapacityPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimWorkCapacityPolicy) ProtoMessage() {}

func (x *ClaimWorkCapacityPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_jobworker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimWorkCapacityPolicy.ProtoReflect.Descriptor instead.
func (*ClaimWorkCapacityPolicy) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_jobworker_proto_rawDescGZIP(), []int{1}
}

func (x *ClaimWorkCapacityPolicy) GetMaxQueueMessages() int32 {
	if x != nil {
		return x.MaxQueueMessages
	}
	return 0
}

func (x *ClaimWorkCapacityPolicy) GetCurrentQueueMessages() int32 {
	if x != nil {
		return x.CurrentQueueMessages
	}
	return 0
}

func (x *ClaimWorkCapacityPolicy) GetClaimWorkFilter() *ClaimWorkFilter {
	if x != nil {
		return x.ClaimWorkFilter
	}
	return nil
}

type QueueMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	MessageID     string                 `protobuf:"bytes,2,opt,name=MessageID,proto3" json:"MessageID,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=ContentType,proto3" json:"ContentType,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,5,rep,name=Headers,proto3" json:"Headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	QueueID       string                 `protobuf:"bytes,6,opt,name=QueueID,proto3" json:"QueueID,omitempty"`
	Priority      int32                  `protobuf:"varint,7,opt,name=Priority,proto3" json:"Priority,omitempty"`
	Handler       string                 `protobuf:"bytes,8,opt,name=Handler,proto3" json:"Handler,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,9,rep,name=Parameters,proto3" json:"Parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	VNamespace    string                 `protobuf:"bytes,10,opt,name=VNamespace,proto3" json:"VNamespace,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueMessage) Reset() {
	*x = QueueMessage{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_jobworker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueMessage) ProtoMessage() {}

func (x *QueueMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_jobworker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueMessage.ProtoReflect.Descriptor instead.
func (*QueueMessage) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_jobworker_proto_rawDescGZIP(), []int{2}
}

func (x *QueueMessage) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *QueueMessage) GetMessageID() string {
	if x != nil {
		return x.MessageID
	}
	return ""
}

func (x *QueueMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *QueueMessage) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *QueueMessage) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *QueueMessage) GetQueueID() string {
	if x != nil {
		return x.QueueID
	}
	return ""
}

func (x *QueueMessage) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *QueueMessage) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

func (x *QueueMessage) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *QueueMessage) GetVNamespace() string {
	if x != nil {
		return x.VNamespace
	}
	return ""
}

func (x *QueueMessage) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ClaimWorkRequest struct {
	state            protoimpl.MessageState     `protogen:"open.v1"`
	WorkerID         string                     `protobuf:"bytes,1,opt,name=workerID,proto3" json:"workerID,omitempty"`
	Information      map[string]string          `protobuf:"bytes,2,rep,name=information,proto3" json:"information,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CapacityPolicies []*ClaimWorkCapacityPolicy `protobuf:"bytes,3,rep,name=capacityPolicies,proto3" json:"capacityPolicies,omitempty"`
	WorkerName       string                     `protobuf:"bytes,4,opt,name=workerName,proto3" json:"workerName,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ClaimWorkRequest) Reset() {
	*x = ClaimWorkRequest{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_jobworker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimWorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimWorkRequest) ProtoMessage() {}

func (x *ClaimWorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_jobworker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimWorkRequest.ProtoReflect.Descriptor instead.
func (*ClaimWorkRequest) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_jobworker_proto_rawDescGZIP(), []int{3}
}

func (x *ClaimWorkRequest) GetWorkerID() string {
	if x != nil {
		return x.WorkerID
	}
	return ""
}

func (x *ClaimWorkRequest) GetInformation() map[string]string {
	if x != nil {
		return x.Information
	}
	return nil
}

func (x *ClaimWorkRequest) GetCapacityPolicies() []*ClaimWorkCapacityPolicy {
	if x != nil {
		return x.CapacityPolicies
	}
	return nil
}

func (x *ClaimWorkRequest) GetWorkerName() string {
	if x != nil {
		return x.WorkerName
	}
	return ""
}

type ClaimWorkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Messages      []*QueueMessage        `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimWorkResponse) Reset() {
	*x = ClaimWorkResponse{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_jobworker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimWorkResponse) ProtoMessage() {}

func (x *ClaimWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_jobworker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimWorkResponse.ProtoReflect.Descriptor instead.
func (*ClaimWorkResponse) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_jobworker_proto_rawDescGZIP(), []int{4}
}

func (x *ClaimWorkResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ClaimWorkResponse) GetMessages() []*QueueMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_internal_infrastructure_server_grpc_proto_definitions_jobworker_proto protoreflect.FileDescriptor

const file_internal_infrastructure_server_grpc_proto_definitions_jobworker_proto_rawDesc = "" +
	"\n" +
	"Einternal/infrastructure/server/grpc/proto/definitions/jobworker.proto\x12\tjobworker\"\xa9\x04\n" +
	"\x0fClaimWorkFilter\x12 \n" +
	"\vtenantCodes\x18\x01 \x03(\tR\vtenantCodes\x12.\n" +
	"\x12excludeTenantCodes\x18\x02 \x03(\tR\x12excludeTenantCodes\x12&\n" +
	"\x0etenantPatterns\x18\x03 \x03(\tR\x0etenantPatterns\x124\n" +
	"\x15excludeTenantPatterns\x18\x04 \x03(\tR\x15excludeTenantPatterns\x12 \n" +
	"\vvNamespaces\x18\x05 \x03(\tR\vvNamespaces\x12.\n" +
	"\x12excludeVNamespaces\x18\x06 \x03(\tR\x12excludeVNamespaces\x12.\n" +
	"\x12vNamespacePatterns\x18\a \x03(\tR\x12vNamespacePatterns\x12<\n" +
	"\x19excludeVNamespacePatterns\x18\b \x03(\tR\x19excludeVNamespacePatterns\x12\x1e\n" +
	"\n" +
	"queueCodes\x18\t \x03(\tR\n" +
	"queueCodes\x12,\n" +
	"\x11excludeQueueCodes\x18\n" +
	" \x03(\tR\x11excludeQueueCodes\x12$\n" +
	"\rqueuePatterns\x18\v \x03(\tR\rqueuePatterns\x122\n" +
	"\x14excludeQueuePatterns\x18\f \x03(\tR\x14excludeQueuePatterns\"\xbf\x01\n" +
	"\x17ClaimWorkCapacityPolicy\x12*\n" +
	"\x10maxQueueMessages\x18\x01 \x01(\x05R\x10maxQueueMessages\x122\n" +
	"\x14currentQueueMessages\x18\x02 \x01(\x05R\x14currentQueueMessages\x12D\n" +
	"\x0fclaimWorkFilter\x18\x03 \x01(\v2\x1a.jobworker.ClaimWorkFilterR\x0fclaimWorkFilter\"\x8a\x04\n" +
	"\fQueueMessage\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x1c\n" +
	"\tMessageID\x18\x02 \x01(\tR\tMessageID\x12\x18\n" +
	"\aContent\x18\x03 \x01(\tR\aContent\x12 \n" +
	"\vContentType\x18\x04 \x01(\tR\vContentType\x12>\n" +
	"\aHeaders\x18\x05 \x03(\v2$.jobworker.QueueMessage.HeadersEntryR\aHeaders\x12\x18\n" +
	"\aQueueID\x18\x06 \x01(\tR\aQueueID\x12\x1a\n" +
	"\bPriority\x18\a \x01(\x05R\bPriority\x12\x18\n" +
	"\aHandler\x18\b \x01(\tR\aHandler\x12G\n" +
	"\n" +
	"Parameters\x18\t \x03(\v2'.jobworker.QueueMessage.ParametersEntryR\n" +
	"Parameters\x12\x1e\n" +
	"\n" +
	"VNamespace\x18\n" +
	" \x01(\tR\n" +
	"VNamespace\x12\x1c\n" +
	"\tCreatedAt\x18\v \x01(\tR\tCreatedAt\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xae\x02\n" +
	"\x10ClaimWorkRequest\x12\x1a\n" +
	"\bworkerID\x18\x01 \x01(\tR\bworkerID\x12N\n" +
	"\vinformation\x18\x02 \x03(\v2,.jobworker.ClaimWorkRequest.InformationEntryR\vinformation\x12N\n" +
	"\x10capacityPolicies\x18\x03 \x03(\v2\".jobworker.ClaimWorkCapacityPolicyR\x10capacityPolicies\x12\x1e\n" +
	"\n" +
	"workerName\x18\x04 \x01(\tR\n" +
	"workerName\x1a>\n" +
	"\x10InformationEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"b\n" +
	"\x11ClaimWorkResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x123\n" +
	"\bmessages\x18\x02 \x03(\v2\x17.jobworker.QueueMessageR\bmessages2Z\n" +
	"\x10JobWorkerService\x12F\n" +
	"\tClaimWork\x12\x1b.jobworker.ClaimWorkRequest\x1a\x1c.jobworker.ClaimWorkResponseB\x18Z\x16pb/jobworker;jobworkerb\x06proto3"

var (
	file_internal_infrastructure_server_grpc_proto_definitions_jobworker_proto_rawDescOnce sync.Once
	file_internal_infrastructure_server_grpc_proto_definitions_jobworker_proto_rawDescData []byte
)

func file_internal_infrastructure_server_grpc_proto_definitions_jobworker_proto_rawDescGZIP() []byte {
	file_internal_infrastructure_server_grpc_proto_definitions_jobworker_proto_rawDescOnce.Do(func() {
		file_internal_infrastructure_server_grpc_proto_definitions_jobworker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_infrastructure_server_grpc_proto_definitions_jobworker_proto_rawDesc), len(file_internal_infrastructure_server_grpc_proto_definitions_jobworker_proto_rawDesc)))
	})
	return file_internal_infrastructure_server_grpc_proto_definitions_jobworker_proto_rawDescData
}

var file_internal_infrastructure_server_grpc_proto_definitions_jobworker_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_infrastructure_server_grpc_proto_definitions_jobworker_proto_goTypes = []any{
	(*ClaimWorkFilter)(nil),         // 0: jobworker.ClaimWorkFilter
	(*ClaimWorkCapacityPolicy)(nil), // 1: jobworker.ClaimWorkCapacityPolicy
	(*QueueMessage)(nil),            // 2: jobworker.QueueMessage
	(*ClaimWorkRequest)(nil),        // 3: jobworker.ClaimWorkRequest
	(*ClaimWorkResponse)(nil),       // 4: jobworker.ClaimWorkResponse
	nil,                             // 5: jobworker.QueueMessage.HeadersEntry
	nil,                             // 6: jobworker.QueueMessage.ParametersEntry
	nil,                             // 7: jobworker.ClaimWorkRequest.InformationEntry
}
var file_internal_infrastructure_server_grpc_proto_definitions_jobworker_proto_depIdxs = []int32{
	0, // 0: jobworker.ClaimWorkCapacityPolicy.claimWorkFilter:type_name -> jobworker.ClaimWorkFilter
	5, // 1: jobworker.QueueMessage.Headers:type_name -> jobworker.QueueMessage.HeadersEntry
	6, // 2: jobworker.QueueMessage.Parameters:type_name -> jobworker.QueueMessage.ParametersEntry
	7, // 3: jobworker.ClaimWorkRequest.information:type_name -> jobworker.ClaimWorkRequest.InformationEntry
	1, // 4: jobworker.ClaimWorkRequest.capacityPolicies:type_name -> jobworker.ClaimWorkCapacityPolicy
	2, // 5: jobworker.ClaimWorkResponse.messages:type_name -> jobworker.QueueMessage
	3, // 6: jobworker.JobWorkerService.ClaimWork:input_type -> jobworker.ClaimWorkRequest
	4, // 7: jobworker.JobWorkerService.ClaimWork:output_type -> jobworker.ClaimWorkResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_internal_infrastructure_server_grpc_proto_definitions_jobworker_proto_init() }
func file_internal_infrastructure_server_grpc_proto_definitions_jobworker_proto_init() {
	if File_internal_infrastructure_server_grpc_proto_definitions_jobworker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_infrastructure_server_grpc_proto_definitions_jobworker_proto_rawDesc), len(file_internal_infrastructure_server_grpc_proto_definitions_jobworker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_infrastructure_server_grpc_proto_definitions_jobworker_proto_goTypes,
		DependencyIndexes: file_internal_infrastructure_server_grpc_proto_definitions_jobworker_proto_depIdxs,
		MessageInfos:      file_internal_infrastructure_server_grpc_proto_definitions_jobworker_proto_msgTypes,
	}.Build()
	File_internal_infrastructure_server_grpc_proto_definitions_jobworker_proto = out.File
	file_internal_infrastructure_server_grpc_proto_definitions_jobworker_proto_goTypes = nil
	file_internal_infrastructure_server_grpc_proto_definitions_jobworker_proto_depIdxs = nil
}
