// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: internal/infrastructure/server/grpc/proto/definitions/jobworker.proto

package jobworker

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JobWorkerService_ClaimWork_FullMethodName = "/jobworker.JobWorkerService/ClaimWork"
)

// JobWorkerServiceClient is the client API for JobWorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JobWorkerServiceClient interface {
	ClaimWork(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClaimWorkRequest, ClaimWorkStreamMessage], error)
}

type jobWorkerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJobWorkerServiceClient(cc grpc.ClientConnInterface) JobWorkerServiceClient {
	return &jobWorkerServiceClient{cc}
}

func (c *jobWorkerServiceClient) ClaimWork(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClaimWorkRequest, ClaimWorkStreamMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &JobWorkerService_ServiceDesc.Streams[0], JobWorkerService_ClaimWork_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClaimWorkRequest, ClaimWorkStreamMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JobWorkerService_ClaimWorkClient = grpc.BidiStreamingClient[ClaimWorkRequest, ClaimWorkStreamMessage]

// JobWorkerServiceServer is the server API for JobWorkerService service.
// All implementations must embed UnimplementedJobWorkerServiceServer
// for forward compatibility.
type JobWorkerServiceServer interface {
	ClaimWork(grpc.BidiStreamingServer[ClaimWorkRequest, ClaimWorkStreamMessage]) error
	mustEmbedUnimplementedJobWorkerServiceServer()
}

// UnimplementedJobWorkerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJobWorkerServiceServer struct{}

func (UnimplementedJobWorkerServiceServer) ClaimWork(grpc.BidiStreamingServer[ClaimWorkRequest, ClaimWorkStreamMessage]) error {
	return status.Error(codes.Unimplemented, "method ClaimWork not implemented")
}
func (UnimplementedJobWorkerServiceServer) mustEmbedUnimplementedJobWorkerServiceServer() {}
func (UnimplementedJobWorkerServiceServer) testEmbeddedByValue()                          {}

// UnsafeJobWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobWorkerServiceServer will
// result in compilation errors.
type UnsafeJobWorkerServiceServer interface {
	mustEmbedUnimplementedJobWorkerServiceServer()
}

func RegisterJobWorkerServiceServer(s grpc.ServiceRegistrar, srv JobWorkerServiceServer) {
	// If the following call panics, it indicates UnimplementedJobWorkerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JobWorkerService_ServiceDesc, srv)
}

func _JobWorkerService_ClaimWork_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(JobWorkerServiceServer).ClaimWork(&grpc.GenericServerStream[ClaimWorkRequest, ClaimWorkStreamMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JobWorkerService_ClaimWorkServer = grpc.BidiStreamingServer[ClaimWorkRequest, ClaimWorkStreamMessage]

// JobWorkerService_ServiceDesc is the grpc.ServiceDesc for JobWorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobWorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jobworker.JobWorkerService",
	HandlerType: (*JobWorkerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ClaimWork",
			Handler:       _JobWorkerService_ClaimWork_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/infrastructure/server/grpc/proto/definitions/jobworker.proto",
}
