// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: scheduled_job.proto

package scheduledjob

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOneOffScheduledJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantCode    string                 `protobuf:"bytes,1,opt,name=tenantCode,proto3" json:"tenantCode,omitempty"`
	QueueCode     string                 `protobuf:"bytes,2,opt,name=queueCode,proto3" json:"queueCode,omitempty"`
	Vnamespace    string                 `protobuf:"bytes,3,opt,name=vnamespace,proto3" json:"vnamespace,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	ContentType   string                 `protobuf:"bytes,5,opt,name=contentType,proto3" json:"contentType,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Handler       string                 `protobuf:"bytes,7,opt,name=handler,proto3" json:"handler,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,8,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Priority      int32                  `protobuf:"varint,9,opt,name=priority,proto3" json:"priority,omitempty"`
	RunAt         string                 `protobuf:"bytes,10,opt,name=runAt,proto3" json:"runAt,omitempty"`       // Specific UTC Date/Time ISO string
	RunAfter      string                 `protobuf:"bytes,11,opt,name=runAfter,proto3" json:"runAfter,omitempty"` // Duration string (e.g., "5m")
	Code          string                 `protobuf:"bytes,12,opt,name=code,proto3" json:"code,omitempty"`         // Optional unique idempotency code
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOneOffScheduledJobRequest) Reset() {
	*x = CreateOneOffScheduledJobRequest{}
	mi := &file_scheduled_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOneOffScheduledJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOneOffScheduledJobRequest) ProtoMessage() {}

func (x *CreateOneOffScheduledJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduled_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOneOffScheduledJobRequest.ProtoReflect.Descriptor instead.
func (*CreateOneOffScheduledJobRequest) Descriptor() ([]byte, []int) {
	return file_scheduled_job_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOneOffScheduledJobRequest) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

func (x *CreateOneOffScheduledJobRequest) GetQueueCode() string {
	if x != nil {
		return x.QueueCode
	}
	return ""
}

func (x *CreateOneOffScheduledJobRequest) GetVnamespace() string {
	if x != nil {
		return x.Vnamespace
	}
	return ""
}

func (x *CreateOneOffScheduledJobRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateOneOffScheduledJobRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *CreateOneOffScheduledJobRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *CreateOneOffScheduledJobRequest) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

func (x *CreateOneOffScheduledJobRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *CreateOneOffScheduledJobRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *CreateOneOffScheduledJobRequest) GetRunAt() string {
	if x != nil {
		return x.RunAt
	}
	return ""
}

func (x *CreateOneOffScheduledJobRequest) GetRunAfter() string {
	if x != nil {
		return x.RunAfter
	}
	return ""
}

func (x *CreateOneOffScheduledJobRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type CreateRecurringScheduledJobRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantCode     string                 `protobuf:"bytes,1,opt,name=tenantCode,proto3" json:"tenantCode,omitempty"`
	QueueCode      string                 `protobuf:"bytes,2,opt,name=queueCode,proto3" json:"queueCode,omitempty"`
	Vnamespace     string                 `protobuf:"bytes,3,opt,name=vnamespace,proto3" json:"vnamespace,omitempty"`
	Content        string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	ContentType    string                 `protobuf:"bytes,5,opt,name=contentType,proto3" json:"contentType,omitempty"`
	Headers        map[string]string      `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Handler        string                 `protobuf:"bytes,7,opt,name=handler,proto3" json:"handler,omitempty"`
	Parameters     map[string]string      `protobuf:"bytes,8,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Priority       int32                  `protobuf:"varint,9,opt,name=priority,proto3" json:"priority,omitempty"`
	Every          string                 `protobuf:"bytes,10,opt,name=every,proto3" json:"every,omitempty"`                   // Duration string (e.g., "5m", "1h")
	CronExpression string                 `protobuf:"bytes,11,opt,name=cronExpression,proto3" json:"cronExpression,omitempty"` // Cron expression (e.g., "0 0 * * *")
	Code           string                 `protobuf:"bytes,12,opt,name=code,proto3" json:"code,omitempty"`                     // Optional unique idempotency code
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateRecurringScheduledJobRequest) Reset() {
	*x = CreateRecurringScheduledJobRequest{}
	mi := &file_scheduled_job_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecurringScheduledJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecurringScheduledJobRequest) ProtoMessage() {}

func (x *CreateRecurringScheduledJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduled_job_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecurringScheduledJobRequest.ProtoReflect.Descriptor instead.
func (*CreateRecurringScheduledJobRequest) Descriptor() ([]byte, []int) {
	return file_scheduled_job_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRecurringScheduledJobRequest) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

func (x *CreateRecurringScheduledJobRequest) GetQueueCode() string {
	if x != nil {
		return x.QueueCode
	}
	return ""
}

func (x *CreateRecurringScheduledJobRequest) GetVnamespace() string {
	if x != nil {
		return x.Vnamespace
	}
	return ""
}

func (x *CreateRecurringScheduledJobRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateRecurringScheduledJobRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *CreateRecurringScheduledJobRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *CreateRecurringScheduledJobRequest) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

func (x *CreateRecurringScheduledJobRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *CreateRecurringScheduledJobRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *CreateRecurringScheduledJobRequest) GetEvery() string {
	if x != nil {
		return x.Every
	}
	return ""
}

func (x *CreateRecurringScheduledJobRequest) GetCronExpression() string {
	if x != nil {
		return x.CronExpression
	}
	return ""
}

func (x *CreateRecurringScheduledJobRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ScheduledJob struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code           string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	TenantId       string                 `protobuf:"bytes,3,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	QueueId        string                 `protobuf:"bytes,4,opt,name=queueId,proto3" json:"queueId,omitempty"`
	QueueCode      string                 `protobuf:"bytes,5,opt,name=queueCode,proto3" json:"queueCode,omitempty"`
	Vnamespace     string                 `protobuf:"bytes,6,opt,name=vnamespace,proto3" json:"vnamespace,omitempty"`
	Content        string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	ContentType    string                 `protobuf:"bytes,8,opt,name=contentType,proto3" json:"contentType,omitempty"`
	Headers        map[string]string      `protobuf:"bytes,9,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Handler        string                 `protobuf:"bytes,10,opt,name=handler,proto3" json:"handler,omitempty"`
	Parameters     map[string]string      `protobuf:"bytes,11,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Priority       int32                  `protobuf:"varint,12,opt,name=priority,proto3" json:"priority,omitempty"`
	State          string                 `protobuf:"bytes,13,opt,name=state,proto3" json:"state,omitempty"`
	Type           string                 `protobuf:"bytes,14,opt,name=type,proto3" json:"type,omitempty"`
	Every          string                 `protobuf:"bytes,15,opt,name=every,proto3" json:"every,omitempty"`
	CronExpression string                 `protobuf:"bytes,16,opt,name=cronExpression,proto3" json:"cronExpression,omitempty"`
	RunAt          string                 `protobuf:"bytes,17,opt,name=runAt,proto3" json:"runAt,omitempty"`
	RunAfter       string                 `protobuf:"bytes,18,opt,name=runAfter,proto3" json:"runAfter,omitempty"`
	NextRunAt      string                 `protobuf:"bytes,19,opt,name=nextRunAt,proto3" json:"nextRunAt,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,20,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,21,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScheduledJob) Reset() {
	*x = ScheduledJob{}
	mi := &file_scheduled_job_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduledJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduledJob) ProtoMessage() {}

func (x *ScheduledJob) ProtoReflect() protoreflect.Message {
	mi := &file_scheduled_job_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduledJob.ProtoReflect.Descriptor instead.
func (*ScheduledJob) Descriptor() ([]byte, []int) {
	return file_scheduled_job_proto_rawDescGZIP(), []int{2}
}

func (x *ScheduledJob) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScheduledJob) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ScheduledJob) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ScheduledJob) GetQueueId() string {
	if x != nil {
		return x.QueueId
	}
	return ""
}

func (x *ScheduledJob) GetQueueCode() string {
	if x != nil {
		return x.QueueCode
	}
	return ""
}

func (x *ScheduledJob) GetVnamespace() string {
	if x != nil {
		return x.Vnamespace
	}
	return ""
}

func (x *ScheduledJob) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ScheduledJob) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ScheduledJob) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ScheduledJob) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

func (x *ScheduledJob) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ScheduledJob) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *ScheduledJob) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ScheduledJob) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ScheduledJob) GetEvery() string {
	if x != nil {
		return x.Every
	}
	return ""
}

func (x *ScheduledJob) GetCronExpression() string {
	if x != nil {
		return x.CronExpression
	}
	return ""
}

func (x *ScheduledJob) GetRunAt() string {
	if x != nil {
		return x.RunAt
	}
	return ""
}

func (x *ScheduledJob) GetRunAfter() string {
	if x != nil {
		return x.RunAfter
	}
	return ""
}

func (x *ScheduledJob) GetNextRunAt() string {
	if x != nil {
		return x.NextRunAt
	}
	return ""
}

func (x *ScheduledJob) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ScheduledJob) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateScheduledJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Result        *ScheduledJob          `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScheduledJobResponse) Reset() {
	*x = CreateScheduledJobResponse{}
	mi := &file_scheduled_job_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScheduledJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScheduledJobResponse) ProtoMessage() {}

func (x *CreateScheduledJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduled_job_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScheduledJobResponse.ProtoReflect.Descriptor instead.
func (*CreateScheduledJobResponse) Descriptor() ([]byte, []int) {
	return file_scheduled_job_proto_rawDescGZIP(), []int{3}
}

func (x *CreateScheduledJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateScheduledJobResponse) GetResult() *ScheduledJob {
	if x != nil {
		return x.Result
	}
	return nil
}

type GetScheduledJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantCode    string                 `protobuf:"bytes,1,opt,name=tenantCode,proto3" json:"tenantCode,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScheduledJobRequest) Reset() {
	*x = GetScheduledJobRequest{}
	mi := &file_scheduled_job_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScheduledJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduledJobRequest) ProtoMessage() {}

func (x *GetScheduledJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduled_job_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduledJobRequest.ProtoReflect.Descriptor instead.
func (*GetScheduledJobRequest) Descriptor() ([]byte, []int) {
	return file_scheduled_job_proto_rawDescGZIP(), []int{4}
}

func (x *GetScheduledJobRequest) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

func (x *GetScheduledJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetScheduledJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Result        *ScheduledJob          `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScheduledJobResponse) Reset() {
	*x = GetScheduledJobResponse{}
	mi := &file_scheduled_job_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScheduledJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduledJobResponse) ProtoMessage() {}

func (x *GetScheduledJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduled_job_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduledJobResponse.ProtoReflect.Descriptor instead.
func (*GetScheduledJobResponse) Descriptor() ([]byte, []int) {
	return file_scheduled_job_proto_rawDescGZIP(), []int{5}
}

func (x *GetScheduledJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetScheduledJobResponse) GetResult() *ScheduledJob {
	if x != nil {
		return x.Result
	}
	return nil
}

type ListScheduledJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantCode    string                 `protobuf:"bytes,1,opt,name=tenantCode,proto3" json:"tenantCode,omitempty"`
	Vnamespace    string                 `protobuf:"bytes,2,opt,name=vnamespace,proto3" json:"vnamespace,omitempty"`
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScheduledJobsRequest) Reset() {
	*x = ListScheduledJobsRequest{}
	mi := &file_scheduled_job_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScheduledJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScheduledJobsRequest) ProtoMessage() {}

func (x *ListScheduledJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduled_job_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScheduledJobsRequest.ProtoReflect.Descriptor instead.
func (*ListScheduledJobsRequest) Descriptor() ([]byte, []int) {
	return file_scheduled_job_proto_rawDescGZIP(), []int{6}
}

func (x *ListScheduledJobsRequest) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

func (x *ListScheduledJobsRequest) GetVnamespace() string {
	if x != nil {
		return x.Vnamespace
	}
	return ""
}

func (x *ListScheduledJobsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListScheduledJobsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ScheduledJobFindResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*ScheduledJob        `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduledJobFindResult) Reset() {
	*x = ScheduledJobFindResult{}
	mi := &file_scheduled_job_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduledJobFindResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduledJobFindResult) ProtoMessage() {}

func (x *ScheduledJobFindResult) ProtoReflect() protoreflect.Message {
	mi := &file_scheduled_job_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduledJobFindResult.ProtoReflect.Descriptor instead.
func (*ScheduledJobFindResult) Descriptor() ([]byte, []int) {
	return file_scheduled_job_proto_rawDescGZIP(), []int{7}
}

func (x *ScheduledJobFindResult) GetEntities() []*ScheduledJob {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *ScheduledJobFindResult) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type ListScheduledJobsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Message       string                  `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Result        *ScheduledJobFindResult `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScheduledJobsResponse) Reset() {
	*x = ListScheduledJobsResponse{}
	mi := &file_scheduled_job_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScheduledJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScheduledJobsResponse) ProtoMessage() {}

func (x *ListScheduledJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduled_job_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScheduledJobsResponse.ProtoReflect.Descriptor instead.
func (*ListScheduledJobsResponse) Descriptor() ([]byte, []int) {
	return file_scheduled_job_proto_rawDescGZIP(), []int{8}
}

func (x *ListScheduledJobsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListScheduledJobsResponse) GetResult() *ScheduledJobFindResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type DeleteScheduledJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantCode    string                 `protobuf:"bytes,1,opt,name=tenantCode,proto3" json:"tenantCode,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScheduledJobRequest) Reset() {
	*x = DeleteScheduledJobRequest{}
	mi := &file_scheduled_job_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScheduledJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScheduledJobRequest) ProtoMessage() {}

func (x *DeleteScheduledJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduled_job_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScheduledJobRequest.ProtoReflect.Descriptor instead.
func (*DeleteScheduledJobRequest) Descriptor() ([]byte, []int) {
	return file_scheduled_job_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteScheduledJobRequest) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

func (x *DeleteScheduledJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteScheduledJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScheduledJobResponse) Reset() {
	*x = DeleteScheduledJobResponse{}
	mi := &file_scheduled_job_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScheduledJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScheduledJobResponse) ProtoMessage() {}

func (x *DeleteScheduledJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduled_job_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScheduledJobResponse.ProtoReflect.Descriptor instead.
func (*DeleteScheduledJobResponse) Descriptor() ([]byte, []int) {
	return file_scheduled_job_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteScheduledJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_scheduled_job_proto protoreflect.FileDescriptor

const file_scheduled_job_proto_rawDesc = "" +
	"\n" +
	"\x13scheduled_job.proto\x12\fscheduledjob\"\xe7\x04\n" +
	"\x1fCreateOneOffScheduledJobRequest\x12\x1e\n" +
	"\n" +
	"tenantCode\x18\x01 \x01(\tR\n" +
	"tenantCode\x12\x1c\n" +
	"\tqueueCode\x18\x02 \x01(\tR\tqueueCode\x12\x1e\n" +
	"\n" +
	"vnamespace\x18\x03 \x01(\tR\n" +
	"vnamespace\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12 \n" +
	"\vcontentType\x18\x05 \x01(\tR\vcontentType\x12T\n" +
	"\aheaders\x18\x06 \x03(\v2:.scheduledjob.CreateOneOffScheduledJobRequest.HeadersEntryR\aheaders\x12\x18\n" +
	"\ahandler\x18\a \x01(\tR\ahandler\x12]\n" +
	"\n" +
	"parameters\x18\b \x03(\v2=.scheduledjob.CreateOneOffScheduledJobRequest.ParametersEntryR\n" +
	"parameters\x12\x1a\n" +
	"\bpriority\x18\t \x01(\x05R\bpriority\x12\x14\n" +
	"\x05runAt\x18\n" +
	" \x01(\tR\x05runAt\x12\x1a\n" +
	"\brunAfter\x18\v \x01(\tR\brunAfter\x12\x12\n" +
	"\x04code\x18\f \x01(\tR\x04code\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfc\x04\n" +
	"\"CreateRecurringScheduledJobRequest\x12\x1e\n" +
	"\n" +
	"tenantCode\x18\x01 \x01(\tR\n" +
	"tenantCode\x12\x1c\n" +
	"\tqueueCode\x18\x02 \x01(\tR\tqueueCode\x12\x1e\n" +
	"\n" +
	"vnamespace\x18\x03 \x01(\tR\n" +
	"vnamespace\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12 \n" +
	"\vcontentType\x18\x05 \x01(\tR\vcontentType\x12W\n" +
	"\aheaders\x18\x06 \x03(\v2=.scheduledjob.CreateRecurringScheduledJobRequest.HeadersEntryR\aheaders\x12\x18\n" +
	"\ahandler\x18\a \x01(\tR\ahandler\x12`\n" +
	"\n" +
	"parameters\x18\b \x03(\v2@.scheduledjob.CreateRecurringScheduledJobRequest.ParametersEntryR\n" +
	"parameters\x12\x1a\n" +
	"\bpriority\x18\t \x01(\x05R\bpriority\x12\x14\n" +
	"\x05every\x18\n" +
	" \x01(\tR\x05every\x12&\n" +
	"\x0ecronExpression\x18\v \x01(\tR\x0ecronExpression\x12\x12\n" +
	"\x04code\x18\f \x01(\tR\x04code\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x96\x06\n" +
	"\fScheduledJob\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1a\n" +
	"\btenantId\x18\x03 \x01(\tR\btenantId\x12\x18\n" +
	"\aqueueId\x18\x04 \x01(\tR\aqueueId\x12\x1c\n" +
	"\tqueueCode\x18\x05 \x01(\tR\tqueueCode\x12\x1e\n" +
	"\n" +
	"vnamespace\x18\x06 \x01(\tR\n" +
	"vnamespace\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12 \n" +
	"\vcontentType\x18\b \x01(\tR\vcontentType\x12A\n" +
	"\aheaders\x18\t \x03(\v2'.scheduledjob.ScheduledJob.HeadersEntryR\aheaders\x12\x18\n" +
	"\ahandler\x18\n" +
	" \x01(\tR\ahandler\x12J\n" +
	"\n" +
	"parameters\x18\v \x03(\v2*.scheduledjob.ScheduledJob.ParametersEntryR\n" +
	"parameters\x12\x1a\n" +
	"\bpriority\x18\f \x01(\x05R\bpriority\x12\x14\n" +
	"\x05state\x18\r \x01(\tR\x05state\x12\x12\n" +
	"\x04type\x18\x0e \x01(\tR\x04type\x12\x14\n" +
	"\x05every\x18\x0f \x01(\tR\x05every\x12&\n" +
	"\x0ecronExpression\x18\x10 \x01(\tR\x0ecronExpression\x12\x14\n" +
	"\x05runAt\x18\x11 \x01(\tR\x05runAt\x12\x1a\n" +
	"\brunAfter\x18\x12 \x01(\tR\brunAfter\x12\x1c\n" +
	"\tnextRunAt\x18\x13 \x01(\tR\tnextRunAt\x12\x1c\n" +
	"\tcreatedAt\x18\x14 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x15 \x01(\tR\tupdatedAt\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"j\n" +
	"\x1aCreateScheduledJobResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x122\n" +
	"\x06result\x18\x02 \x01(\v2\x1a.scheduledjob.ScheduledJobR\x06result\"H\n" +
	"\x16GetScheduledJobRequest\x12\x1e\n" +
	"\n" +
	"tenantCode\x18\x01 \x01(\tR\n" +
	"tenantCode\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"g\n" +
	"\x17GetScheduledJobResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x122\n" +
	"\x06result\x18\x02 \x01(\v2\x1a.scheduledjob.ScheduledJobR\x06result\"\x8e\x01\n" +
	"\x18ListScheduledJobsRequest\x12\x1e\n" +
	"\n" +
	"tenantCode\x18\x01 \x01(\tR\n" +
	"tenantCode\x12\x1e\n" +
	"\n" +
	"vnamespace\x18\x02 \x01(\tR\n" +
	"vnamespace\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x05R\bpageSize\"h\n" +
	"\x16ScheduledJobFindResult\x126\n" +
	"\bentities\x18\x01 \x03(\v2\x1a.scheduledjob.ScheduledJobR\bentities\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\"s\n" +
	"\x19ListScheduledJobsResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12<\n" +
	"\x06result\x18\x02 \x01(\v2$.scheduledjob.ScheduledJobFindResultR\x06result\"K\n" +
	"\x19DeleteScheduledJobRequest\x12\x1e\n" +
	"\n" +
	"tenantCode\x18\x01 \x01(\tR\n" +
	"tenantCode\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"6\n" +
	"\x1aDeleteScheduledJobResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xb4\x04\n" +
	"\x13ScheduledJobService\x12s\n" +
	"\x18CreateOneOffScheduledJob\x12-.scheduledjob.CreateOneOffScheduledJobRequest\x1a(.scheduledjob.CreateScheduledJobResponse\x12y\n" +
	"\x1bCreateRecurringScheduledJob\x120.scheduledjob.CreateRecurringScheduledJobRequest\x1a(.scheduledjob.CreateScheduledJobResponse\x12^\n" +
	"\x0fGetScheduledJob\x12$.scheduledjob.GetScheduledJobRequest\x1a%.scheduledjob.GetScheduledJobResponse\x12d\n" +
	"\x11ListScheduledJobs\x12&.scheduledjob.ListScheduledJobsRequest\x1a'.scheduledjob.ListScheduledJobsResponse\x12g\n" +
	"\x12DeleteScheduledJob\x12'.scheduledjob.DeleteScheduledJobRequest\x1a(.scheduledjob.DeleteScheduledJobResponseB\x1eZ\x1cpb/scheduledjob;scheduledjobb\x06proto3"

var (
	file_scheduled_job_proto_rawDescOnce sync.Once
	file_scheduled_job_proto_rawDescData []byte
)

func file_scheduled_job_proto_rawDescGZIP() []byte {
	file_scheduled_job_proto_rawDescOnce.Do(func() {
		file_scheduled_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scheduled_job_proto_rawDesc), len(file_scheduled_job_proto_rawDesc)))
	})
	return file_scheduled_job_proto_rawDescData
}

var file_scheduled_job_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_scheduled_job_proto_goTypes = []any{
	(*CreateOneOffScheduledJobRequest)(nil),    // 0: scheduledjob.CreateOneOffScheduledJobRequest
	(*CreateRecurringScheduledJobRequest)(nil), // 1: scheduledjob.CreateRecurringScheduledJobRequest
	(*ScheduledJob)(nil),                       // 2: scheduledjob.ScheduledJob
	(*CreateScheduledJobResponse)(nil),         // 3: scheduledjob.CreateScheduledJobResponse
	(*GetScheduledJobRequest)(nil),             // 4: scheduledjob.GetScheduledJobRequest
	(*GetScheduledJobResponse)(nil),            // 5: scheduledjob.GetScheduledJobResponse
	(*ListScheduledJobsRequest)(nil),           // 6: scheduledjob.ListScheduledJobsRequest
	(*ScheduledJobFindResult)(nil),             // 7: scheduledjob.ScheduledJobFindResult
	(*ListScheduledJobsResponse)(nil),          // 8: scheduledjob.ListScheduledJobsResponse
	(*DeleteScheduledJobRequest)(nil),          // 9: scheduledjob.DeleteScheduledJobRequest
	(*DeleteScheduledJobResponse)(nil),         // 10: scheduledjob.DeleteScheduledJobResponse
	nil,                                        // 11: scheduledjob.CreateOneOffScheduledJobRequest.HeadersEntry
	nil,                                        // 12: scheduledjob.CreateOneOffScheduledJobRequest.ParametersEntry
	nil,                                        // 13: scheduledjob.CreateRecurringScheduledJobRequest.HeadersEntry
	nil,                                        // 14: scheduledjob.CreateRecurringScheduledJobRequest.ParametersEntry
	nil,                                        // 15: scheduledjob.ScheduledJob.HeadersEntry
	nil,                                        // 16: scheduledjob.ScheduledJob.ParametersEntry
}
var file_scheduled_job_proto_depIdxs = []int32{
	11, // 0: scheduledjob.CreateOneOffScheduledJobRequest.headers:type_name -> scheduledjob.CreateOneOffScheduledJobRequest.HeadersEntry
	12, // 1: scheduledjob.CreateOneOffScheduledJobRequest.parameters:type_name -> scheduledjob.CreateOneOffScheduledJobRequest.ParametersEntry
	13, // 2: scheduledjob.CreateRecurringScheduledJobRequest.headers:type_name -> scheduledjob.CreateRecurringScheduledJobRequest.HeadersEntry
	14, // 3: scheduledjob.CreateRecurringScheduledJobRequest.parameters:type_name -> scheduledjob.CreateRecurringScheduledJobRequest.ParametersEntry
	15, // 4: scheduledjob.ScheduledJob.headers:type_name -> scheduledjob.ScheduledJob.HeadersEntry
	16, // 5: scheduledjob.ScheduledJob.parameters:type_name -> scheduledjob.ScheduledJob.ParametersEntry
	2,  // 6: scheduledjob.CreateScheduledJobResponse.result:type_name -> scheduledjob.ScheduledJob
	2,  // 7: scheduledjob.GetScheduledJobResponse.result:type_name -> scheduledjob.ScheduledJob
	2,  // 8: scheduledjob.ScheduledJobFindResult.entities:type_name -> scheduledjob.ScheduledJob
	7,  // 9: scheduledjob.ListScheduledJobsResponse.result:type_name -> scheduledjob.ScheduledJobFindResult
	0,  // 10: scheduledjob.ScheduledJobService.CreateOneOffScheduledJob:input_type -> scheduledjob.CreateOneOffScheduledJobRequest
	1,  // 11: scheduledjob.ScheduledJobService.CreateRecurringScheduledJob:input_type -> scheduledjob.CreateRecurringScheduledJobRequest
	4,  // 12: scheduledjob.ScheduledJobService.GetScheduledJob:input_type -> scheduledjob.GetScheduledJobRequest
	6,  // 13: scheduledjob.ScheduledJobService.ListScheduledJobs:input_type -> scheduledjob.ListScheduledJobsRequest
	9,  // 14: scheduledjob.ScheduledJobService.DeleteScheduledJob:input_type -> scheduledjob.DeleteScheduledJobRequest
	3,  // 15: scheduledjob.ScheduledJobService.CreateOneOffScheduledJob:output_type -> scheduledjob.CreateScheduledJobResponse
	3,  // 16: scheduledjob.ScheduledJobService.CreateRecurringScheduledJob:output_type -> scheduledjob.CreateScheduledJobResponse
	5,  // 17: scheduledjob.ScheduledJobService.GetScheduledJob:output_type -> scheduledjob.GetScheduledJobResponse
	8,  // 18: scheduledjob.ScheduledJobService.ListScheduledJobs:output_type -> scheduledjob.ListScheduledJobsResponse
	10, // 19: scheduledjob.ScheduledJobService.DeleteScheduledJob:output_type -> scheduledjob.DeleteScheduledJobResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_scheduled_job_proto_init() }
func file_scheduled_job_proto_init() {
	if File_scheduled_job_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scheduled_job_proto_rawDesc), len(file_scheduled_job_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scheduled_job_proto_goTypes,
		DependencyIndexes: file_scheduled_job_proto_depIdxs,
		MessageInfos:      file_scheduled_job_proto_msgTypes,
	}.Build()
	File_scheduled_job_proto = out.File
	file_scheduled_job_proto_goTypes = nil
	file_scheduled_job_proto_depIdxs = nil
}
