// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: queue.proto

package queue

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueueType int32

const (
	QueueType_STANDARD    QueueType = 0
	QueueType_DELAYED     QueueType = 1
	QueueType_DEAD_LETTER QueueType = 2
)

// Enum value maps for QueueType.
var (
	QueueType_name = map[int32]string{
		0: "STANDARD",
		1: "DELAYED",
		2: "DEAD_LETTER",
	}
	QueueType_value = map[string]int32{
		"STANDARD":    0,
		"DELAYED":     1,
		"DEAD_LETTER": 2,
	}
)

func (x QueueType) Enum() *QueueType {
	p := new(QueueType)
	*p = x
	return p
}

func (x QueueType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueueType) Descriptor() protoreflect.EnumDescriptor {
	return file_queue_proto_enumTypes[0].Descriptor()
}

func (QueueType) Type() protoreflect.EnumType {
	return &file_queue_proto_enumTypes[0]
}

func (x QueueType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueueType.Descriptor instead.
func (QueueType) EnumDescriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{0}
}

type CreateQueueRequest struct {
	state                                 protoimpl.MessageState `protogen:"open.v1"`
	TenantCode                            string                 `protobuf:"bytes,1,opt,name=tenantCode,proto3" json:"tenantCode,omitempty"`
	Code                                  string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name                                  string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type                                  string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	State                                 string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Vnamespace                            string                 `protobuf:"bytes,6,opt,name=vnamespace,proto3" json:"vnamespace,omitempty"`
	DefaultQueueMessageTTL                int32                  `protobuf:"varint,7,opt,name=defaultQueueMessageTTL,proto3" json:"defaultQueueMessageTTL,omitempty"`
	DefaultQueueMessageDelayTime          int32                  `protobuf:"varint,8,opt,name=defaultQueueMessageDelayTime,proto3" json:"defaultQueueMessageDelayTime,omitempty"`
	QueueExpires                          int32                  `protobuf:"varint,9,opt,name=queueExpires,proto3" json:"queueExpires,omitempty"`
	AllowDuplicated                       bool                   `protobuf:"varint,10,opt,name=allowDuplicated,proto3" json:"allowDuplicated,omitempty"`
	MaxAttempts                           int32                  `protobuf:"varint,11,opt,name=maxAttempts,proto3" json:"maxAttempts,omitempty"`
	DesiredPriorityThresholds             map[int32]int32        `protobuf:"bytes,12,rep,name=desiredPriorityThresholds,proto3" json:"desiredPriorityThresholds,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Headers                               map[string]string      `protobuf:"bytes,13,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DeadLetterExchangeId                  string                 `protobuf:"bytes,14,opt,name=deadLetterExchangeId,proto3" json:"deadLetterExchangeId,omitempty"`
	DeadLetterExchangeRoutingKeyOrPattern string                 `protobuf:"bytes,15,opt,name=deadLetterExchangeRoutingKeyOrPattern,proto3" json:"deadLetterExchangeRoutingKeyOrPattern,omitempty"`
	MaxQueueSize                          int32                  `protobuf:"varint,16,opt,name=maxQueueSize,proto3" json:"maxQueueSize,omitempty"`
	MaxDeliveringMessages                 int32                  `protobuf:"varint,17,opt,name=maxDeliveringMessages,proto3" json:"maxDeliveringMessages,omitempty"`
	unknownFields                         protoimpl.UnknownFields
	sizeCache                             protoimpl.SizeCache
}

func (x *CreateQueueRequest) Reset() {
	*x = CreateQueueRequest{}
	mi := &file_queue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQueueRequest) ProtoMessage() {}

func (x *CreateQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQueueRequest.ProtoReflect.Descriptor instead.
func (*CreateQueueRequest) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{0}
}

func (x *CreateQueueRequest) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

func (x *CreateQueueRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateQueueRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateQueueRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateQueueRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CreateQueueRequest) GetVnamespace() string {
	if x != nil {
		return x.Vnamespace
	}
	return ""
}

func (x *CreateQueueRequest) GetDefaultQueueMessageTTL() int32 {
	if x != nil {
		return x.DefaultQueueMessageTTL
	}
	return 0
}

func (x *CreateQueueRequest) GetDefaultQueueMessageDelayTime() int32 {
	if x != nil {
		return x.DefaultQueueMessageDelayTime
	}
	return 0
}

func (x *CreateQueueRequest) GetQueueExpires() int32 {
	if x != nil {
		return x.QueueExpires
	}
	return 0
}

func (x *CreateQueueRequest) GetAllowDuplicated() bool {
	if x != nil {
		return x.AllowDuplicated
	}
	return false
}

func (x *CreateQueueRequest) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *CreateQueueRequest) GetDesiredPriorityThresholds() map[int32]int32 {
	if x != nil {
		return x.DesiredPriorityThresholds
	}
	return nil
}

func (x *CreateQueueRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *CreateQueueRequest) GetDeadLetterExchangeId() string {
	if x != nil {
		return x.DeadLetterExchangeId
	}
	return ""
}

func (x *CreateQueueRequest) GetDeadLetterExchangeRoutingKeyOrPattern() string {
	if x != nil {
		return x.DeadLetterExchangeRoutingKeyOrPattern
	}
	return ""
}

func (x *CreateQueueRequest) GetMaxQueueSize() int32 {
	if x != nil {
		return x.MaxQueueSize
	}
	return 0
}

func (x *CreateQueueRequest) GetMaxDeliveringMessages() int32 {
	if x != nil {
		return x.MaxDeliveringMessages
	}
	return 0
}

type CreateQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Result        *Queue                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQueueResponse) Reset() {
	*x = CreateQueueResponse{}
	mi := &file_queue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQueueResponse) ProtoMessage() {}

func (x *CreateQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQueueResponse.ProtoReflect.Descriptor instead.
func (*CreateQueueResponse) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{1}
}

func (x *CreateQueueResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateQueueResponse) GetResult() *Queue {
	if x != nil {
		return x.Result
	}
	return nil
}

type BulkCreateQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantCode    string                 `protobuf:"bytes,1,opt,name=tenantCode,proto3" json:"tenantCode,omitempty"`
	Queues        []*CreateQueueItem     `protobuf:"bytes,2,rep,name=queues,proto3" json:"queues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkCreateQueueRequest) Reset() {
	*x = BulkCreateQueueRequest{}
	mi := &file_queue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkCreateQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkCreateQueueRequest) ProtoMessage() {}

func (x *BulkCreateQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkCreateQueueRequest.ProtoReflect.Descriptor instead.
func (*BulkCreateQueueRequest) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{2}
}

func (x *BulkCreateQueueRequest) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

func (x *BulkCreateQueueRequest) GetQueues() []*CreateQueueItem {
	if x != nil {
		return x.Queues
	}
	return nil
}

type CreateQueueItem struct {
	state                                 protoimpl.MessageState `protogen:"open.v1"`
	Code                                  string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name                                  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                                  string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	State                                 string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Vnamespace                            string                 `protobuf:"bytes,5,opt,name=vnamespace,proto3" json:"vnamespace,omitempty"`
	DefaultQueueMessageTTL                int32                  `protobuf:"varint,6,opt,name=defaultQueueMessageTTL,proto3" json:"defaultQueueMessageTTL,omitempty"`
	DefaultQueueMessageDelayTime          int32                  `protobuf:"varint,7,opt,name=defaultQueueMessageDelayTime,proto3" json:"defaultQueueMessageDelayTime,omitempty"`
	QueueExpires                          int32                  `protobuf:"varint,8,opt,name=queueExpires,proto3" json:"queueExpires,omitempty"`
	AllowDuplicated                       bool                   `protobuf:"varint,9,opt,name=allowDuplicated,proto3" json:"allowDuplicated,omitempty"`
	MaxAttempts                           int32                  `protobuf:"varint,10,opt,name=maxAttempts,proto3" json:"maxAttempts,omitempty"`
	DesiredPriorityThresholds             map[int32]int32        `protobuf:"bytes,11,rep,name=desiredPriorityThresholds,proto3" json:"desiredPriorityThresholds,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Headers                               map[string]string      `protobuf:"bytes,12,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DeadLetterExchangeId                  string                 `protobuf:"bytes,13,opt,name=deadLetterExchangeId,proto3" json:"deadLetterExchangeId,omitempty"`
	DeadLetterExchangeRoutingKeyOrPattern string                 `protobuf:"bytes,14,opt,name=deadLetterExchangeRoutingKeyOrPattern,proto3" json:"deadLetterExchangeRoutingKeyOrPattern,omitempty"`
	MaxQueueSize                          int32                  `protobuf:"varint,15,opt,name=maxQueueSize,proto3" json:"maxQueueSize,omitempty"`
	MaxDeliveringMessages                 int32                  `protobuf:"varint,16,opt,name=maxDeliveringMessages,proto3" json:"maxDeliveringMessages,omitempty"`
	unknownFields                         protoimpl.UnknownFields
	sizeCache                             protoimpl.SizeCache
}

func (x *CreateQueueItem) Reset() {
	*x = CreateQueueItem{}
	mi := &file_queue_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQueueItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQueueItem) ProtoMessage() {}

func (x *CreateQueueItem) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQueueItem.ProtoReflect.Descriptor instead.
func (*CreateQueueItem) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{3}
}

func (x *CreateQueueItem) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateQueueItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateQueueItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateQueueItem) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CreateQueueItem) GetVnamespace() string {
	if x != nil {
		return x.Vnamespace
	}
	return ""
}

func (x *CreateQueueItem) GetDefaultQueueMessageTTL() int32 {
	if x != nil {
		return x.DefaultQueueMessageTTL
	}
	return 0
}

func (x *CreateQueueItem) GetDefaultQueueMessageDelayTime() int32 {
	if x != nil {
		return x.DefaultQueueMessageDelayTime
	}
	return 0
}

func (x *CreateQueueItem) GetQueueExpires() int32 {
	if x != nil {
		return x.QueueExpires
	}
	return 0
}

func (x *CreateQueueItem) GetAllowDuplicated() bool {
	if x != nil {
		return x.AllowDuplicated
	}
	return false
}

func (x *CreateQueueItem) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *CreateQueueItem) GetDesiredPriorityThresholds() map[int32]int32 {
	if x != nil {
		return x.DesiredPriorityThresholds
	}
	return nil
}

func (x *CreateQueueItem) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *CreateQueueItem) GetDeadLetterExchangeId() string {
	if x != nil {
		return x.DeadLetterExchangeId
	}
	return ""
}

func (x *CreateQueueItem) GetDeadLetterExchangeRoutingKeyOrPattern() string {
	if x != nil {
		return x.DeadLetterExchangeRoutingKeyOrPattern
	}
	return ""
}

func (x *CreateQueueItem) GetMaxQueueSize() int32 {
	if x != nil {
		return x.MaxQueueSize
	}
	return 0
}

func (x *CreateQueueItem) GetMaxDeliveringMessages() int32 {
	if x != nil {
		return x.MaxDeliveringMessages
	}
	return 0
}

type BulkCreateQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Result        []*Queue               `protobuf:"bytes,2,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkCreateQueueResponse) Reset() {
	*x = BulkCreateQueueResponse{}
	mi := &file_queue_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkCreateQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkCreateQueueResponse) ProtoMessage() {}

func (x *BulkCreateQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkCreateQueueResponse.ProtoReflect.Descriptor instead.
func (*BulkCreateQueueResponse) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{4}
}

func (x *BulkCreateQueueResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BulkCreateQueueResponse) GetResult() []*Queue {
	if x != nil {
		return x.Result
	}
	return nil
}

type GetQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantCode    string                 `protobuf:"bytes,1,opt,name=tenantCode,proto3" json:"tenantCode,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Vnamespace    string                 `protobuf:"bytes,3,opt,name=vnamespace,proto3" json:"vnamespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueueRequest) Reset() {
	*x = GetQueueRequest{}
	mi := &file_queue_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueRequest) ProtoMessage() {}

func (x *GetQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueRequest.ProtoReflect.Descriptor instead.
func (*GetQueueRequest) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{5}
}

func (x *GetQueueRequest) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

func (x *GetQueueRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetQueueRequest) GetVnamespace() string {
	if x != nil {
		return x.Vnamespace
	}
	return ""
}

type GetQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Result        *Queue                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueueResponse) Reset() {
	*x = GetQueueResponse{}
	mi := &file_queue_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueResponse) ProtoMessage() {}

func (x *GetQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueResponse.ProtoReflect.Descriptor instead.
func (*GetQueueResponse) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{6}
}

func (x *GetQueueResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetQueueResponse) GetResult() *Queue {
	if x != nil {
		return x.Result
	}
	return nil
}

type GetQueuesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantCode     string                 `protobuf:"bytes,1,opt,name=tenantCode,proto3" json:"tenantCode,omitempty"`
	Q              string                 `protobuf:"bytes,2,opt,name=q,proto3" json:"q,omitempty"`
	Cursor         string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize       int32                  `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Vnamespace     string                 `protobuf:"bytes,5,opt,name=vnamespace,proto3" json:"vnamespace,omitempty"`
	IncludeHeaders bool                   `protobuf:"varint,6,opt,name=includeHeaders,proto3" json:"includeHeaders,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetQueuesRequest) Reset() {
	*x = GetQueuesRequest{}
	mi := &file_queue_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueuesRequest) ProtoMessage() {}

func (x *GetQueuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueuesRequest.ProtoReflect.Descriptor instead.
func (*GetQueuesRequest) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{7}
}

func (x *GetQueuesRequest) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

func (x *GetQueuesRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *GetQueuesRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *GetQueuesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetQueuesRequest) GetVnamespace() string {
	if x != nil {
		return x.Vnamespace
	}
	return ""
}

func (x *GetQueuesRequest) GetIncludeHeaders() bool {
	if x != nil {
		return x.IncludeHeaders
	}
	return false
}

type Queue struct {
	state                                 protoimpl.MessageState `protogen:"open.v1"`
	Id                                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                                  string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name                                  string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type                                  string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	State                                 string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Vnamespace                            string                 `protobuf:"bytes,6,opt,name=vnamespace,proto3" json:"vnamespace,omitempty"`
	CreatedAt                             string                 `protobuf:"bytes,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt                             string                 `protobuf:"bytes,8,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	DefaultQueueMessageTTL                int32                  `protobuf:"varint,9,opt,name=defaultQueueMessageTTL,proto3" json:"defaultQueueMessageTTL,omitempty"`
	DefaultQueueMessageDelayTime          int32                  `protobuf:"varint,10,opt,name=defaultQueueMessageDelayTime,proto3" json:"defaultQueueMessageDelayTime,omitempty"`
	QueueExpires                          int32                  `protobuf:"varint,11,opt,name=queueExpires,proto3" json:"queueExpires,omitempty"`
	ExpireAt                              string                 `protobuf:"bytes,12,opt,name=expireAt,proto3" json:"expireAt,omitempty"`
	AllowDuplicated                       bool                   `protobuf:"varint,13,opt,name=allowDuplicated,proto3" json:"allowDuplicated,omitempty"`
	MaxAttempts                           int32                  `protobuf:"varint,14,opt,name=maxAttempts,proto3" json:"maxAttempts,omitempty"`
	DesiredPriorityThresholds             map[int32]int32        `protobuf:"bytes,15,rep,name=desiredPriorityThresholds,proto3" json:"desiredPriorityThresholds,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	PriorityThresholds                    map[int32]int32        `protobuf:"bytes,16,rep,name=priorityThresholds,proto3" json:"priorityThresholds,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Headers                               map[string]string      `protobuf:"bytes,17,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DeadLetterExchangeId                  string                 `protobuf:"bytes,18,opt,name=deadLetterExchangeId,proto3" json:"deadLetterExchangeId,omitempty"`
	DeadLetterExchangeRoutingKeyOrPattern string                 `protobuf:"bytes,19,opt,name=deadLetterExchangeRoutingKeyOrPattern,proto3" json:"deadLetterExchangeRoutingKeyOrPattern,omitempty"`
	MessagesCount                         int32                  `protobuf:"varint,20,opt,name=messagesCount,proto3" json:"messagesCount,omitempty"`
	MaxQueueSize                          int32                  `protobuf:"varint,21,opt,name=maxQueueSize,proto3" json:"maxQueueSize,omitempty"`
	NodeSchedulerSupervisorId             string                 `protobuf:"bytes,22,opt,name=nodeSchedulerSupervisorId,proto3" json:"nodeSchedulerSupervisorId,omitempty"`
	NodeSchedulerSupervisorCode           string                 `protobuf:"bytes,23,opt,name=nodeSchedulerSupervisorCode,proto3" json:"nodeSchedulerSupervisorCode,omitempty"`
	NodeSchedulerSupervisorName           string                 `protobuf:"bytes,24,opt,name=nodeSchedulerSupervisorName,proto3" json:"nodeSchedulerSupervisorName,omitempty"`
	NodeSchedulerQueueSupervisionState    string                 `protobuf:"bytes,25,opt,name=nodeSchedulerQueueSupervisionState,proto3" json:"nodeSchedulerQueueSupervisionState,omitempty"`
	MaxDeliveringMessages                 int32                  `protobuf:"varint,26,opt,name=maxDeliveringMessages,proto3" json:"maxDeliveringMessages,omitempty"`
	CurrentDeliveringMessages             int32                  `protobuf:"varint,27,opt,name=currentDeliveringMessages,proto3" json:"currentDeliveringMessages,omitempty"`
	unknownFields                         protoimpl.UnknownFields
	sizeCache                             protoimpl.SizeCache
}

func (x *Queue) Reset() {
	*x = Queue{}
	mi := &file_queue_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Queue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Queue) ProtoMessage() {}

func (x *Queue) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Queue.ProtoReflect.Descriptor instead.
func (*Queue) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{8}
}

func (x *Queue) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Queue) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Queue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Queue) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Queue) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Queue) GetVnamespace() string {
	if x != nil {
		return x.Vnamespace
	}
	return ""
}

func (x *Queue) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Queue) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Queue) GetDefaultQueueMessageTTL() int32 {
	if x != nil {
		return x.DefaultQueueMessageTTL
	}
	return 0
}

func (x *Queue) GetDefaultQueueMessageDelayTime() int32 {
	if x != nil {
		return x.DefaultQueueMessageDelayTime
	}
	return 0
}

func (x *Queue) GetQueueExpires() int32 {
	if x != nil {
		return x.QueueExpires
	}
	return 0
}

func (x *Queue) GetExpireAt() string {
	if x != nil {
		return x.ExpireAt
	}
	return ""
}

func (x *Queue) GetAllowDuplicated() bool {
	if x != nil {
		return x.AllowDuplicated
	}
	return false
}

func (x *Queue) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *Queue) GetDesiredPriorityThresholds() map[int32]int32 {
	if x != nil {
		return x.DesiredPriorityThresholds
	}
	return nil
}

func (x *Queue) GetPriorityThresholds() map[int32]int32 {
	if x != nil {
		return x.PriorityThresholds
	}
	return nil
}

func (x *Queue) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Queue) GetDeadLetterExchangeId() string {
	if x != nil {
		return x.DeadLetterExchangeId
	}
	return ""
}

func (x *Queue) GetDeadLetterExchangeRoutingKeyOrPattern() string {
	if x != nil {
		return x.DeadLetterExchangeRoutingKeyOrPattern
	}
	return ""
}

func (x *Queue) GetMessagesCount() int32 {
	if x != nil {
		return x.MessagesCount
	}
	return 0
}

func (x *Queue) GetMaxQueueSize() int32 {
	if x != nil {
		return x.MaxQueueSize
	}
	return 0
}

func (x *Queue) GetNodeSchedulerSupervisorId() string {
	if x != nil {
		return x.NodeSchedulerSupervisorId
	}
	return ""
}

func (x *Queue) GetNodeSchedulerSupervisorCode() string {
	if x != nil {
		return x.NodeSchedulerSupervisorCode
	}
	return ""
}

func (x *Queue) GetNodeSchedulerSupervisorName() string {
	if x != nil {
		return x.NodeSchedulerSupervisorName
	}
	return ""
}

func (x *Queue) GetNodeSchedulerQueueSupervisionState() string {
	if x != nil {
		return x.NodeSchedulerQueueSupervisionState
	}
	return ""
}

func (x *Queue) GetMaxDeliveringMessages() int32 {
	if x != nil {
		return x.MaxDeliveringMessages
	}
	return 0
}

func (x *Queue) GetCurrentDeliveringMessages() int32 {
	if x != nil {
		return x.CurrentDeliveringMessages
	}
	return 0
}

type QueueFindResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*Queue               `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueFindResult) Reset() {
	*x = QueueFindResult{}
	mi := &file_queue_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueFindResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueFindResult) ProtoMessage() {}

func (x *QueueFindResult) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueFindResult.ProtoReflect.Descriptor instead.
func (*QueueFindResult) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{9}
}

func (x *QueueFindResult) GetEntities() []*Queue {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *QueueFindResult) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type GetQueuesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Result        *QueueFindResult       `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueuesResponse) Reset() {
	*x = GetQueuesResponse{}
	mi := &file_queue_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueuesResponse) ProtoMessage() {}

func (x *GetQueuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueuesResponse.ProtoReflect.Descriptor instead.
func (*GetQueuesResponse) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{10}
}

func (x *GetQueuesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetQueuesResponse) GetResult() *QueueFindResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type DeleteQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantCode    string                 `protobuf:"bytes,1,opt,name=tenantCode,proto3" json:"tenantCode,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Vnamespace    string                 `protobuf:"bytes,3,opt,name=vnamespace,proto3" json:"vnamespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQueueRequest) Reset() {
	*x = DeleteQueueRequest{}
	mi := &file_queue_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQueueRequest) ProtoMessage() {}

func (x *DeleteQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQueueRequest.ProtoReflect.Descriptor instead.
func (*DeleteQueueRequest) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteQueueRequest) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

func (x *DeleteQueueRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DeleteQueueRequest) GetVnamespace() string {
	if x != nil {
		return x.Vnamespace
	}
	return ""
}

type DeleteQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQueueResponse) Reset() {
	*x = DeleteQueueResponse{}
	mi := &file_queue_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQueueResponse) ProtoMessage() {}

func (x *DeleteQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQueueResponse.ProtoReflect.Descriptor instead.
func (*DeleteQueueResponse) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteQueueResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EnqueueMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantCode    string                 `protobuf:"bytes,1,opt,name=tenantCode,proto3" json:"tenantCode,omitempty"`
	QueueCode     string                 `protobuf:"bytes,2,opt,name=queueCode,proto3" json:"queueCode,omitempty"`
	Vnamespace    string                 `protobuf:"bytes,3,opt,name=vnamespace,proto3" json:"vnamespace,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	ContentType   string                 `protobuf:"bytes,5,opt,name=contentType,proto3" json:"contentType,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Priority      int32                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	Handler       string                 `protobuf:"bytes,8,opt,name=handler,proto3" json:"handler,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,9,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueMessageRequest) Reset() {
	*x = EnqueueMessageRequest{}
	mi := &file_queue_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueMessageRequest) ProtoMessage() {}

func (x *EnqueueMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueMessageRequest.ProtoReflect.Descriptor instead.
func (*EnqueueMessageRequest) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{13}
}

func (x *EnqueueMessageRequest) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

func (x *EnqueueMessageRequest) GetQueueCode() string {
	if x != nil {
		return x.QueueCode
	}
	return ""
}

func (x *EnqueueMessageRequest) GetVnamespace() string {
	if x != nil {
		return x.Vnamespace
	}
	return ""
}

func (x *EnqueueMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *EnqueueMessageRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *EnqueueMessageRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *EnqueueMessageRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *EnqueueMessageRequest) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

func (x *EnqueueMessageRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type EnqueueMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=messageId,proto3" json:"messageId,omitempty"`
	Result        map[string]string      `protobuf:"bytes,3,rep,name=result,proto3" json:"result,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueMessageResponse) Reset() {
	*x = EnqueueMessageResponse{}
	mi := &file_queue_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueMessageResponse) ProtoMessage() {}

func (x *EnqueueMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueMessageResponse.ProtoReflect.Descriptor instead.
func (*EnqueueMessageResponse) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{14}
}

func (x *EnqueueMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EnqueueMessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *EnqueueMessageResponse) GetResult() map[string]string {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_queue_proto protoreflect.FileDescriptor

const file_queue_proto_rawDesc = "" +
	"\n" +
	"\vqueue.proto\x12\x05queue\"\xba\a\n" +
	"\x12CreateQueueRequest\x12\x1e\n" +
	"\n" +
	"tenantCode\x18\x01 \x01(\tR\n" +
	"tenantCode\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x1e\n" +
	"\n" +
	"vnamespace\x18\x06 \x01(\tR\n" +
	"vnamespace\x126\n" +
	"\x16defaultQueueMessageTTL\x18\a \x01(\x05R\x16defaultQueueMessageTTL\x12B\n" +
	"\x1cdefaultQueueMessageDelayTime\x18\b \x01(\x05R\x1cdefaultQueueMessageDelayTime\x12\"\n" +
	"\fqueueExpires\x18\t \x01(\x05R\fqueueExpires\x12(\n" +
	"\x0fallowDuplicated\x18\n" +
	" \x01(\bR\x0fallowDuplicated\x12 \n" +
	"\vmaxAttempts\x18\v \x01(\x05R\vmaxAttempts\x12v\n" +
	"\x19desiredPriorityThresholds\x18\f \x03(\v28.queue.CreateQueueRequest.DesiredPriorityThresholdsEntryR\x19desiredPriorityThresholds\x12@\n" +
	"\aheaders\x18\r \x03(\v2&.queue.CreateQueueRequest.HeadersEntryR\aheaders\x122\n" +
	"\x14deadLetterExchangeId\x18\x0e \x01(\tR\x14deadLetterExchangeId\x12T\n" +
	"%deadLetterExchangeRoutingKeyOrPattern\x18\x0f \x01(\tR%deadLetterExchangeRoutingKeyOrPattern\x12\"\n" +
	"\fmaxQueueSize\x18\x10 \x01(\x05R\fmaxQueueSize\x124\n" +
	"\x15maxDeliveringMessages\x18\x11 \x01(\x05R\x15maxDeliveringMessages\x1aL\n" +
	"\x1eDesiredPriorityThresholdsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"U\n" +
	"\x13CreateQueueResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12$\n" +
	"\x06result\x18\x02 \x01(\v2\f.queue.QueueR\x06result\"h\n" +
	"\x16BulkCreateQueueRequest\x12\x1e\n" +
	"\n" +
	"tenantCode\x18\x01 \x01(\tR\n" +
	"tenantCode\x12.\n" +
	"\x06queues\x18\x02 \x03(\v2\x16.queue.CreateQueueItemR\x06queues\"\x91\a\n" +
	"\x0fCreateQueueItem\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x1e\n" +
	"\n" +
	"vnamespace\x18\x05 \x01(\tR\n" +
	"vnamespace\x126\n" +
	"\x16defaultQueueMessageTTL\x18\x06 \x01(\x05R\x16defaultQueueMessageTTL\x12B\n" +
	"\x1cdefaultQueueMessageDelayTime\x18\a \x01(\x05R\x1cdefaultQueueMessageDelayTime\x12\"\n" +
	"\fqueueExpires\x18\b \x01(\x05R\fqueueExpires\x12(\n" +
	"\x0fallowDuplicated\x18\t \x01(\bR\x0fallowDuplicated\x12 \n" +
	"\vmaxAttempts\x18\n" +
	" \x01(\x05R\vmaxAttempts\x12s\n" +
	"\x19desiredPriorityThresholds\x18\v \x03(\v25.queue.CreateQueueItem.DesiredPriorityThresholdsEntryR\x19desiredPriorityThresholds\x12=\n" +
	"\aheaders\x18\f \x03(\v2#.queue.CreateQueueItem.HeadersEntryR\aheaders\x122\n" +
	"\x14deadLetterExchangeId\x18\r \x01(\tR\x14deadLetterExchangeId\x12T\n" +
	"%deadLetterExchangeRoutingKeyOrPattern\x18\x0e \x01(\tR%deadLetterExchangeRoutingKeyOrPattern\x12\"\n" +
	"\fmaxQueueSize\x18\x0f \x01(\x05R\fmaxQueueSize\x124\n" +
	"\x15maxDeliveringMessages\x18\x10 \x01(\x05R\x15maxDeliveringMessages\x1aL\n" +
	"\x1eDesiredPriorityThresholdsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Y\n" +
	"\x17BulkCreateQueueResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12$\n" +
	"\x06result\x18\x02 \x03(\v2\f.queue.QueueR\x06result\"e\n" +
	"\x0fGetQueueRequest\x12\x1e\n" +
	"\n" +
	"tenantCode\x18\x01 \x01(\tR\n" +
	"tenantCode\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1e\n" +
	"\n" +
	"vnamespace\x18\x03 \x01(\tR\n" +
	"vnamespace\"R\n" +
	"\x10GetQueueResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12$\n" +
	"\x06result\x18\x02 \x01(\v2\f.queue.QueueR\x06result\"\xbc\x01\n" +
	"\x10GetQueuesRequest\x12\x1e\n" +
	"\n" +
	"tenantCode\x18\x01 \x01(\tR\n" +
	"tenantCode\x12\f\n" +
	"\x01q\x18\x02 \x01(\tR\x01q\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x05R\bpageSize\x12\x1e\n" +
	"\n" +
	"vnamespace\x18\x05 \x01(\tR\n" +
	"vnamespace\x12&\n" +
	"\x0eincludeHeaders\x18\x06 \x01(\bR\x0eincludeHeaders\"\xee\v\n" +
	"\x05Queue\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x1e\n" +
	"\n" +
	"vnamespace\x18\x06 \x01(\tR\n" +
	"vnamespace\x12\x1c\n" +
	"\tcreatedAt\x18\a \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\b \x01(\tR\tupdatedAt\x126\n" +
	"\x16defaultQueueMessageTTL\x18\t \x01(\x05R\x16defaultQueueMessageTTL\x12B\n" +
	"\x1cdefaultQueueMessageDelayTime\x18\n" +
	" \x01(\x05R\x1cdefaultQueueMessageDelayTime\x12\"\n" +
	"\fqueueExpires\x18\v \x01(\x05R\fqueueExpires\x12\x1a\n" +
	"\bexpireAt\x18\f \x01(\tR\bexpireAt\x12(\n" +
	"\x0fallowDuplicated\x18\r \x01(\bR\x0fallowDuplicated\x12 \n" +
	"\vmaxAttempts\x18\x0e \x01(\x05R\vmaxAttempts\x12i\n" +
	"\x19desiredPriorityThresholds\x18\x0f \x03(\v2+.queue.Queue.DesiredPriorityThresholdsEntryR\x19desiredPriorityThresholds\x12T\n" +
	"\x12priorityThresholds\x18\x10 \x03(\v2$.queue.Queue.PriorityThresholdsEntryR\x12priorityThresholds\x123\n" +
	"\aheaders\x18\x11 \x03(\v2\x19.queue.Queue.HeadersEntryR\aheaders\x122\n" +
	"\x14deadLetterExchangeId\x18\x12 \x01(\tR\x14deadLetterExchangeId\x12T\n" +
	"%deadLetterExchangeRoutingKeyOrPattern\x18\x13 \x01(\tR%deadLetterExchangeRoutingKeyOrPattern\x12$\n" +
	"\rmessagesCount\x18\x14 \x01(\x05R\rmessagesCount\x12\"\n" +
	"\fmaxQueueSize\x18\x15 \x01(\x05R\fmaxQueueSize\x12<\n" +
	"\x19nodeSchedulerSupervisorId\x18\x16 \x01(\tR\x19nodeSchedulerSupervisorId\x12@\n" +
	"\x1bnodeSchedulerSupervisorCode\x18\x17 \x01(\tR\x1bnodeSchedulerSupervisorCode\x12@\n" +
	"\x1bnodeSchedulerSupervisorName\x18\x18 \x01(\tR\x1bnodeSchedulerSupervisorName\x12N\n" +
	"\"nodeSchedulerQueueSupervisionState\x18\x19 \x01(\tR\"nodeSchedulerQueueSupervisionState\x124\n" +
	"\x15maxDeliveringMessages\x18\x1a \x01(\x05R\x15maxDeliveringMessages\x12<\n" +
	"\x19currentDeliveringMessages\x18\x1b \x01(\x05R\x19currentDeliveringMessages\x1aL\n" +
	"\x1eDesiredPriorityThresholdsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aE\n" +
	"\x17PriorityThresholdsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"S\n" +
	"\x0fQueueFindResult\x12(\n" +
	"\bentities\x18\x01 \x03(\v2\f.queue.QueueR\bentities\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\"]\n" +
	"\x11GetQueuesResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12.\n" +
	"\x06result\x18\x02 \x01(\v2\x16.queue.QueueFindResultR\x06result\"h\n" +
	"\x12DeleteQueueRequest\x12\x1e\n" +
	"\n" +
	"tenantCode\x18\x01 \x01(\tR\n" +
	"tenantCode\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1e\n" +
	"\n" +
	"vnamespace\x18\x03 \x01(\tR\n" +
	"vnamespace\"/\n" +
	"\x13DeleteQueueResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xf5\x03\n" +
	"\x15EnqueueMessageRequest\x12\x1e\n" +
	"\n" +
	"tenantCode\x18\x01 \x01(\tR\n" +
	"tenantCode\x12\x1c\n" +
	"\tqueueCode\x18\x02 \x01(\tR\tqueueCode\x12\x1e\n" +
	"\n" +
	"vnamespace\x18\x03 \x01(\tR\n" +
	"vnamespace\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12 \n" +
	"\vcontentType\x18\x05 \x01(\tR\vcontentType\x12C\n" +
	"\aheaders\x18\x06 \x03(\v2).queue.EnqueueMessageRequest.HeadersEntryR\aheaders\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority\x12\x18\n" +
	"\ahandler\x18\b \x01(\tR\ahandler\x12L\n" +
	"\n" +
	"parameters\x18\t \x03(\v2,.queue.EnqueueMessageRequest.ParametersEntryR\n" +
	"parameters\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xce\x01\n" +
	"\x16EnqueueMessageResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1c\n" +
	"\tmessageId\x18\x02 \x01(\tR\tmessageId\x12A\n" +
	"\x06result\x18\x03 \x03(\v2).queue.EnqueueMessageResponse.ResultEntryR\x06result\x1a9\n" +
	"\vResultEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*7\n" +
	"\tQueueType\x12\f\n" +
	"\bSTANDARD\x10\x00\x12\v\n" +
	"\aDELAYED\x10\x01\x12\x0f\n" +
	"\vDEAD_LETTER\x10\x022\xb8\x03\n" +
	"\fQueueService\x12D\n" +
	"\vCreateQueue\x12\x19.queue.CreateQueueRequest\x1a\x1a.queue.CreateQueueResponse\x12P\n" +
	"\x0fBulkCreateQueue\x12\x1d.queue.BulkCreateQueueRequest\x1a\x1e.queue.BulkCreateQueueResponse\x12;\n" +
	"\bGetQueue\x12\x16.queue.GetQueueRequest\x1a\x17.queue.GetQueueResponse\x12>\n" +
	"\tGetQueues\x12\x17.queue.GetQueuesRequest\x1a\x18.queue.GetQueuesResponse\x12D\n" +
	"\vDeleteQueue\x12\x19.queue.DeleteQueueRequest\x1a\x1a.queue.DeleteQueueResponse\x12M\n" +
	"\x0eEnqueueMessage\x12\x1c.queue.EnqueueMessageRequest\x1a\x1d.queue.EnqueueMessageResponseB\x10Z\x0epb/queue;queueb\x06proto3"

var (
	file_queue_proto_rawDescOnce sync.Once
	file_queue_proto_rawDescData []byte
)

func file_queue_proto_rawDescGZIP() []byte {
	file_queue_proto_rawDescOnce.Do(func() {
		file_queue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_queue_proto_rawDesc), len(file_queue_proto_rawDesc)))
	})
	return file_queue_proto_rawDescData
}

var file_queue_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_queue_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_queue_proto_goTypes = []any{
	(QueueType)(0),                  // 0: queue.QueueType
	(*CreateQueueRequest)(nil),      // 1: queue.CreateQueueRequest
	(*CreateQueueResponse)(nil),     // 2: queue.CreateQueueResponse
	(*BulkCreateQueueRequest)(nil),  // 3: queue.BulkCreateQueueRequest
	(*CreateQueueItem)(nil),         // 4: queue.CreateQueueItem
	(*BulkCreateQueueResponse)(nil), // 5: queue.BulkCreateQueueResponse
	(*GetQueueRequest)(nil),         // 6: queue.GetQueueRequest
	(*GetQueueResponse)(nil),        // 7: queue.GetQueueResponse
	(*GetQueuesRequest)(nil),        // 8: queue.GetQueuesRequest
	(*Queue)(nil),                   // 9: queue.Queue
	(*QueueFindResult)(nil),         // 10: queue.QueueFindResult
	(*GetQueuesResponse)(nil),       // 11: queue.GetQueuesResponse
	(*DeleteQueueRequest)(nil),      // 12: queue.DeleteQueueRequest
	(*DeleteQueueResponse)(nil),     // 13: queue.DeleteQueueResponse
	(*EnqueueMessageRequest)(nil),   // 14: queue.EnqueueMessageRequest
	(*EnqueueMessageResponse)(nil),  // 15: queue.EnqueueMessageResponse
	nil,                             // 16: queue.CreateQueueRequest.DesiredPriorityThresholdsEntry
	nil,                             // 17: queue.CreateQueueRequest.HeadersEntry
	nil,                             // 18: queue.CreateQueueItem.DesiredPriorityThresholdsEntry
	nil,                             // 19: queue.CreateQueueItem.HeadersEntry
	nil,                             // 20: queue.Queue.DesiredPriorityThresholdsEntry
	nil,                             // 21: queue.Queue.PriorityThresholdsEntry
	nil,                             // 22: queue.Queue.HeadersEntry
	nil,                             // 23: queue.EnqueueMessageRequest.HeadersEntry
	nil,                             // 24: queue.EnqueueMessageRequest.ParametersEntry
	nil,                             // 25: queue.EnqueueMessageResponse.ResultEntry
}
var file_queue_proto_depIdxs = []int32{
	16, // 0: queue.CreateQueueRequest.desiredPriorityThresholds:type_name -> queue.CreateQueueRequest.DesiredPriorityThresholdsEntry
	17, // 1: queue.CreateQueueRequest.headers:type_name -> queue.CreateQueueRequest.HeadersEntry
	9,  // 2: queue.CreateQueueResponse.result:type_name -> queue.Queue
	4,  // 3: queue.BulkCreateQueueRequest.queues:type_name -> queue.CreateQueueItem
	18, // 4: queue.CreateQueueItem.desiredPriorityThresholds:type_name -> queue.CreateQueueItem.DesiredPriorityThresholdsEntry
	19, // 5: queue.CreateQueueItem.headers:type_name -> queue.CreateQueueItem.HeadersEntry
	9,  // 6: queue.BulkCreateQueueResponse.result:type_name -> queue.Queue
	9,  // 7: queue.GetQueueResponse.result:type_name -> queue.Queue
	20, // 8: queue.Queue.desiredPriorityThresholds:type_name -> queue.Queue.DesiredPriorityThresholdsEntry
	21, // 9: queue.Queue.priorityThresholds:type_name -> queue.Queue.PriorityThresholdsEntry
	22, // 10: queue.Queue.headers:type_name -> queue.Queue.HeadersEntry
	9,  // 11: queue.QueueFindResult.entities:type_name -> queue.Queue
	10, // 12: queue.GetQueuesResponse.result:type_name -> queue.QueueFindResult
	23, // 13: queue.EnqueueMessageRequest.headers:type_name -> queue.EnqueueMessageRequest.HeadersEntry
	24, // 14: queue.EnqueueMessageRequest.parameters:type_name -> queue.EnqueueMessageRequest.ParametersEntry
	25, // 15: queue.EnqueueMessageResponse.result:type_name -> queue.EnqueueMessageResponse.ResultEntry
	1,  // 16: queue.QueueService.CreateQueue:input_type -> queue.CreateQueueRequest
	3,  // 17: queue.QueueService.BulkCreateQueue:input_type -> queue.BulkCreateQueueRequest
	6,  // 18: queue.QueueService.GetQueue:input_type -> queue.GetQueueRequest
	8,  // 19: queue.QueueService.GetQueues:input_type -> queue.GetQueuesRequest
	12, // 20: queue.QueueService.DeleteQueue:input_type -> queue.DeleteQueueRequest
	14, // 21: queue.QueueService.EnqueueMessage:input_type -> queue.EnqueueMessageRequest
	2,  // 22: queue.QueueService.CreateQueue:output_type -> queue.CreateQueueResponse
	5,  // 23: queue.QueueService.BulkCreateQueue:output_type -> queue.BulkCreateQueueResponse
	7,  // 24: queue.QueueService.GetQueue:output_type -> queue.GetQueueResponse
	11, // 25: queue.QueueService.GetQueues:output_type -> queue.GetQueuesResponse
	13, // 26: queue.QueueService.DeleteQueue:output_type -> queue.DeleteQueueResponse
	15, // 27: queue.QueueService.EnqueueMessage:output_type -> queue.EnqueueMessageResponse
	22, // [22:28] is the sub-list for method output_type
	16, // [16:22] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_queue_proto_init() }
func file_queue_proto_init() {
	if File_queue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_queue_proto_rawDesc), len(file_queue_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_queue_proto_goTypes,
		DependencyIndexes: file_queue_proto_depIdxs,
		EnumInfos:         file_queue_proto_enumTypes,
		MessageInfos:      file_queue_proto_msgTypes,
	}.Build()
	File_queue_proto = out.File
	file_queue_proto_goTypes = nil
	file_queue_proto_depIdxs = nil
}
