// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/infrastructure/server/grpc/proto/definitions/auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for login
type LoginRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UsernameOrEmail string                 `protobuf:"bytes,1,opt,name=usernameOrEmail,proto3" json:"usernameOrEmail,omitempty"`
	Password        string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_auth_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetUsernameOrEmail() string {
	if x != nil {
		return x.UsernameOrEmail
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// Response message for login
type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request message for logout
type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_auth_proto_rawDescGZIP(), []int{2}
}

// Response message for logout
type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_auth_proto_rawDescGZIP(), []int{3}
}

func (x *LogoutResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_infrastructure_server_grpc_proto_definitions_auth_proto protoreflect.FileDescriptor

const file_internal_infrastructure_server_grpc_proto_definitions_auth_proto_rawDesc = "" +
	"\n" +
	"@internal/infrastructure/server/grpc/proto/definitions/auth.proto\x12\x04auth\"T\n" +
	"\fLoginRequest\x12(\n" +
	"\x0fusernameOrEmail\x18\x01 \x01(\tR\x0fusernameOrEmail\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"?\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x0f\n" +
	"\rLogoutRequest\"*\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2t\n" +
	"\vAuthService\x120\n" +
	"\x05Login\x12\x12.auth.LoginRequest\x1a\x13.auth.LoginResponse\x123\n" +
	"\x06Logout\x12\x13.auth.LogoutRequest\x1a\x14.auth.LogoutResponseB\x0eZ\fpb/auth;authb\x06proto3"

var (
	file_internal_infrastructure_server_grpc_proto_definitions_auth_proto_rawDescOnce sync.Once
	file_internal_infrastructure_server_grpc_proto_definitions_auth_proto_rawDescData []byte
)

func file_internal_infrastructure_server_grpc_proto_definitions_auth_proto_rawDescGZIP() []byte {
	file_internal_infrastructure_server_grpc_proto_definitions_auth_proto_rawDescOnce.Do(func() {
		file_internal_infrastructure_server_grpc_proto_definitions_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_infrastructure_server_grpc_proto_definitions_auth_proto_rawDesc), len(file_internal_infrastructure_server_grpc_proto_definitions_auth_proto_rawDesc)))
	})
	return file_internal_infrastructure_server_grpc_proto_definitions_auth_proto_rawDescData
}

var file_internal_infrastructure_server_grpc_proto_definitions_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_infrastructure_server_grpc_proto_definitions_auth_proto_goTypes = []any{
	(*LoginRequest)(nil),   // 0: auth.LoginRequest
	(*LoginResponse)(nil),  // 1: auth.LoginResponse
	(*LogoutRequest)(nil),  // 2: auth.LogoutRequest
	(*LogoutResponse)(nil), // 3: auth.LogoutResponse
}
var file_internal_infrastructure_server_grpc_proto_definitions_auth_proto_depIdxs = []int32{
	0, // 0: auth.AuthService.Login:input_type -> auth.LoginRequest
	2, // 1: auth.AuthService.Logout:input_type -> auth.LogoutRequest
	1, // 2: auth.AuthService.Login:output_type -> auth.LoginResponse
	3, // 3: auth.AuthService.Logout:output_type -> auth.LogoutResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_infrastructure_server_grpc_proto_definitions_auth_proto_init() }
func file_internal_infrastructure_server_grpc_proto_definitions_auth_proto_init() {
	if File_internal_infrastructure_server_grpc_proto_definitions_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_infrastructure_server_grpc_proto_definitions_auth_proto_rawDesc), len(file_internal_infrastructure_server_grpc_proto_definitions_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_infrastructure_server_grpc_proto_definitions_auth_proto_goTypes,
		DependencyIndexes: file_internal_infrastructure_server_grpc_proto_definitions_auth_proto_depIdxs,
		MessageInfos:      file_internal_infrastructure_server_grpc_proto_definitions_auth_proto_msgTypes,
	}.Build()
	File_internal_infrastructure_server_grpc_proto_definitions_auth_proto = out.File
	file_internal_infrastructure_server_grpc_proto_definitions_auth_proto_goTypes = nil
	file_internal_infrastructure_server_grpc_proto_definitions_auth_proto_depIdxs = nil
}
