// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: nodescheduler.proto

package nodescheduler

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetNodeSchedulersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Q             string                 `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeSchedulersRequest) Reset() {
	*x = GetNodeSchedulersRequest{}
	mi := &file_nodescheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeSchedulersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeSchedulersRequest) ProtoMessage() {}

func (x *GetNodeSchedulersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodescheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeSchedulersRequest.ProtoReflect.Descriptor instead.
func (*GetNodeSchedulersRequest) Descriptor() ([]byte, []int) {
	return file_nodescheduler_proto_rawDescGZIP(), []int{0}
}

func (x *GetNodeSchedulersRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *GetNodeSchedulersRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *GetNodeSchedulersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type NodeScheduler struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ID               string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	TTL              int64                  `protobuf:"varint,3,opt,name=TTL,proto3" json:"TTL,omitempty"`
	LastHeartbeat    string                 `protobuf:"bytes,4,opt,name=LastHeartbeat,proto3" json:"LastHeartbeat,omitempty"`
	Information      map[string]string      `protobuf:"bytes,5,rep,name=Information,proto3" json:"Information,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ConnectionStatus string                 `protobuf:"bytes,6,opt,name=ConnectionStatus,proto3" json:"ConnectionStatus,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,7,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,8,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NodeScheduler) Reset() {
	*x = NodeScheduler{}
	mi := &file_nodescheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeScheduler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeScheduler) ProtoMessage() {}

func (x *NodeScheduler) ProtoReflect() protoreflect.Message {
	mi := &file_nodescheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeScheduler.ProtoReflect.Descriptor instead.
func (*NodeScheduler) Descriptor() ([]byte, []int) {
	return file_nodescheduler_proto_rawDescGZIP(), []int{1}
}

func (x *NodeScheduler) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *NodeScheduler) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeScheduler) GetTTL() int64 {
	if x != nil {
		return x.TTL
	}
	return 0
}

func (x *NodeScheduler) GetLastHeartbeat() string {
	if x != nil {
		return x.LastHeartbeat
	}
	return ""
}

func (x *NodeScheduler) GetInformation() map[string]string {
	if x != nil {
		return x.Information
	}
	return nil
}

func (x *NodeScheduler) GetConnectionStatus() string {
	if x != nil {
		return x.ConnectionStatus
	}
	return ""
}

func (x *NodeScheduler) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *NodeScheduler) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type NodeSchedulerFindResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*NodeScheduler       `protobuf:"bytes,1,rep,name=Entities,proto3" json:"Entities,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=Cursor,proto3" json:"Cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeSchedulerFindResult) Reset() {
	*x = NodeSchedulerFindResult{}
	mi := &file_nodescheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeSchedulerFindResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeSchedulerFindResult) ProtoMessage() {}

func (x *NodeSchedulerFindResult) ProtoReflect() protoreflect.Message {
	mi := &file_nodescheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeSchedulerFindResult.ProtoReflect.Descriptor instead.
func (*NodeSchedulerFindResult) Descriptor() ([]byte, []int) {
	return file_nodescheduler_proto_rawDescGZIP(), []int{2}
}

func (x *NodeSchedulerFindResult) GetEntities() []*NodeScheduler {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *NodeSchedulerFindResult) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type GetNodeSchedulersResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Message       string                   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Result        *NodeSchedulerFindResult `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeSchedulersResponse) Reset() {
	*x = GetNodeSchedulersResponse{}
	mi := &file_nodescheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeSchedulersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeSchedulersResponse) ProtoMessage() {}

func (x *GetNodeSchedulersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodescheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeSchedulersResponse.ProtoReflect.Descriptor instead.
func (*GetNodeSchedulersResponse) Descriptor() ([]byte, []int) {
	return file_nodescheduler_proto_rawDescGZIP(), []int{3}
}

func (x *GetNodeSchedulersResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetNodeSchedulersResponse) GetResult() *NodeSchedulerFindResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type GetNodeSchedulerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeSchedulerRequest) Reset() {
	*x = GetNodeSchedulerRequest{}
	mi := &file_nodescheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeSchedulerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeSchedulerRequest) ProtoMessage() {}

func (x *GetNodeSchedulerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodescheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeSchedulerRequest.ProtoReflect.Descriptor instead.
func (*GetNodeSchedulerRequest) Descriptor() ([]byte, []int) {
	return file_nodescheduler_proto_rawDescGZIP(), []int{4}
}

func (x *GetNodeSchedulerRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type GetNodeSchedulerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Result        *NodeScheduler         `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeSchedulerResponse) Reset() {
	*x = GetNodeSchedulerResponse{}
	mi := &file_nodescheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeSchedulerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeSchedulerResponse) ProtoMessage() {}

func (x *GetNodeSchedulerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodescheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeSchedulerResponse.ProtoReflect.Descriptor instead.
func (*GetNodeSchedulerResponse) Descriptor() ([]byte, []int) {
	return file_nodescheduler_proto_rawDescGZIP(), []int{5}
}

func (x *GetNodeSchedulerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetNodeSchedulerResponse) GetResult() *NodeScheduler {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_nodescheduler_proto protoreflect.FileDescriptor

const file_nodescheduler_proto_rawDesc = "" +
	"\n" +
	"\x13nodescheduler.proto\x12\rnodescheduler\"\\\n" +
	"\x18GetNodeSchedulersRequest\x12\f\n" +
	"\x01q\x18\x01 \x01(\tR\x01q\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x05R\bpageSize\"\xe4\x02\n" +
	"\rNodeScheduler\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x10\n" +
	"\x03TTL\x18\x03 \x01(\x03R\x03TTL\x12$\n" +
	"\rLastHeartbeat\x18\x04 \x01(\tR\rLastHeartbeat\x12O\n" +
	"\vInformation\x18\x05 \x03(\v2-.nodescheduler.NodeScheduler.InformationEntryR\vInformation\x12*\n" +
	"\x10ConnectionStatus\x18\x06 \x01(\tR\x10ConnectionStatus\x12\x1c\n" +
	"\tCreatedAt\x18\a \x01(\tR\tCreatedAt\x12\x1c\n" +
	"\tUpdatedAt\x18\b \x01(\tR\tUpdatedAt\x1a>\n" +
	"\x10InformationEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"k\n" +
	"\x17NodeSchedulerFindResult\x128\n" +
	"\bEntities\x18\x01 \x03(\v2\x1c.nodescheduler.NodeSchedulerR\bEntities\x12\x16\n" +
	"\x06Cursor\x18\x02 \x01(\tR\x06Cursor\"u\n" +
	"\x19GetNodeSchedulersResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12>\n" +
	"\x06result\x18\x02 \x01(\v2&.nodescheduler.NodeSchedulerFindResultR\x06result\")\n" +
	"\x17GetNodeSchedulerRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"j\n" +
	"\x18GetNodeSchedulerResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x124\n" +
	"\x06result\x18\x02 \x01(\v2\x1c.nodescheduler.NodeSchedulerR\x06result2\xe3\x01\n" +
	"\x14NodeSchedulerService\x12f\n" +
	"\x11GetNodeSchedulers\x12'.nodescheduler.GetNodeSchedulersRequest\x1a(.nodescheduler.GetNodeSchedulersResponse\x12c\n" +
	"\x10GetNodeScheduler\x12&.nodescheduler.GetNodeSchedulerRequest\x1a'.nodescheduler.GetNodeSchedulerResponseB Z\x1epb/nodescheduler;nodeschedulerb\x06proto3"

var (
	file_nodescheduler_proto_rawDescOnce sync.Once
	file_nodescheduler_proto_rawDescData []byte
)

func file_nodescheduler_proto_rawDescGZIP() []byte {
	file_nodescheduler_proto_rawDescOnce.Do(func() {
		file_nodescheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nodescheduler_proto_rawDesc), len(file_nodescheduler_proto_rawDesc)))
	})
	return file_nodescheduler_proto_rawDescData
}

var file_nodescheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_nodescheduler_proto_goTypes = []any{
	(*GetNodeSchedulersRequest)(nil),  // 0: nodescheduler.GetNodeSchedulersRequest
	(*NodeScheduler)(nil),             // 1: nodescheduler.NodeScheduler
	(*NodeSchedulerFindResult)(nil),   // 2: nodescheduler.NodeSchedulerFindResult
	(*GetNodeSchedulersResponse)(nil), // 3: nodescheduler.GetNodeSchedulersResponse
	(*GetNodeSchedulerRequest)(nil),   // 4: nodescheduler.GetNodeSchedulerRequest
	(*GetNodeSchedulerResponse)(nil),  // 5: nodescheduler.GetNodeSchedulerResponse
	nil,                               // 6: nodescheduler.NodeScheduler.InformationEntry
}
var file_nodescheduler_proto_depIdxs = []int32{
	6, // 0: nodescheduler.NodeScheduler.Information:type_name -> nodescheduler.NodeScheduler.InformationEntry
	1, // 1: nodescheduler.NodeSchedulerFindResult.Entities:type_name -> nodescheduler.NodeScheduler
	2, // 2: nodescheduler.GetNodeSchedulersResponse.result:type_name -> nodescheduler.NodeSchedulerFindResult
	1, // 3: nodescheduler.GetNodeSchedulerResponse.result:type_name -> nodescheduler.NodeScheduler
	0, // 4: nodescheduler.NodeSchedulerService.GetNodeSchedulers:input_type -> nodescheduler.GetNodeSchedulersRequest
	4, // 5: nodescheduler.NodeSchedulerService.GetNodeScheduler:input_type -> nodescheduler.GetNodeSchedulerRequest
	3, // 6: nodescheduler.NodeSchedulerService.GetNodeSchedulers:output_type -> nodescheduler.GetNodeSchedulersResponse
	5, // 7: nodescheduler.NodeSchedulerService.GetNodeScheduler:output_type -> nodescheduler.GetNodeSchedulerResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_nodescheduler_proto_init() }
func file_nodescheduler_proto_init() {
	if File_nodescheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nodescheduler_proto_rawDesc), len(file_nodescheduler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nodescheduler_proto_goTypes,
		DependencyIndexes: file_nodescheduler_proto_depIdxs,
		MessageInfos:      file_nodescheduler_proto_msgTypes,
	}.Build()
	File_nodescheduler_proto = out.File
	file_nodescheduler_proto_goTypes = nil
	file_nodescheduler_proto_depIdxs = nil
}
