// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: nodescheduler.proto

package nodescheduler

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeSchedulerService_GetNodeSchedulers_FullMethodName = "/nodescheduler.NodeSchedulerService/GetNodeSchedulers"
	NodeSchedulerService_GetNodeScheduler_FullMethodName  = "/nodescheduler.NodeSchedulerService/GetNodeScheduler"
)

// NodeSchedulerServiceClient is the client API for NodeSchedulerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeSchedulerServiceClient interface {
	GetNodeSchedulers(ctx context.Context, in *GetNodeSchedulersRequest, opts ...grpc.CallOption) (*GetNodeSchedulersResponse, error)
	GetNodeScheduler(ctx context.Context, in *GetNodeSchedulerRequest, opts ...grpc.CallOption) (*GetNodeSchedulerResponse, error)
}

type nodeSchedulerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeSchedulerServiceClient(cc grpc.ClientConnInterface) NodeSchedulerServiceClient {
	return &nodeSchedulerServiceClient{cc}
}

func (c *nodeSchedulerServiceClient) GetNodeSchedulers(ctx context.Context, in *GetNodeSchedulersRequest, opts ...grpc.CallOption) (*GetNodeSchedulersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeSchedulersResponse)
	err := c.cc.Invoke(ctx, NodeSchedulerService_GetNodeSchedulers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeSchedulerServiceClient) GetNodeScheduler(ctx context.Context, in *GetNodeSchedulerRequest, opts ...grpc.CallOption) (*GetNodeSchedulerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeSchedulerResponse)
	err := c.cc.Invoke(ctx, NodeSchedulerService_GetNodeScheduler_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeSchedulerServiceServer is the server API for NodeSchedulerService service.
// All implementations must embed UnimplementedNodeSchedulerServiceServer
// for forward compatibility.
type NodeSchedulerServiceServer interface {
	GetNodeSchedulers(context.Context, *GetNodeSchedulersRequest) (*GetNodeSchedulersResponse, error)
	GetNodeScheduler(context.Context, *GetNodeSchedulerRequest) (*GetNodeSchedulerResponse, error)
	mustEmbedUnimplementedNodeSchedulerServiceServer()
}

// UnimplementedNodeSchedulerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeSchedulerServiceServer struct{}

func (UnimplementedNodeSchedulerServiceServer) GetNodeSchedulers(context.Context, *GetNodeSchedulersRequest) (*GetNodeSchedulersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeSchedulers not implemented")
}
func (UnimplementedNodeSchedulerServiceServer) GetNodeScheduler(context.Context, *GetNodeSchedulerRequest) (*GetNodeSchedulerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeScheduler not implemented")
}
func (UnimplementedNodeSchedulerServiceServer) mustEmbedUnimplementedNodeSchedulerServiceServer() {}
func (UnimplementedNodeSchedulerServiceServer) testEmbeddedByValue()                              {}

// UnsafeNodeSchedulerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeSchedulerServiceServer will
// result in compilation errors.
type UnsafeNodeSchedulerServiceServer interface {
	mustEmbedUnimplementedNodeSchedulerServiceServer()
}

func RegisterNodeSchedulerServiceServer(s grpc.ServiceRegistrar, srv NodeSchedulerServiceServer) {
	// If the following call pancis, it indicates UnimplementedNodeSchedulerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeSchedulerService_ServiceDesc, srv)
}

func _NodeSchedulerService_GetNodeSchedulers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeSchedulersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeSchedulerServiceServer).GetNodeSchedulers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeSchedulerService_GetNodeSchedulers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeSchedulerServiceServer).GetNodeSchedulers(ctx, req.(*GetNodeSchedulersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeSchedulerService_GetNodeScheduler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeSchedulerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeSchedulerServiceServer).GetNodeScheduler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeSchedulerService_GetNodeScheduler_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeSchedulerServiceServer).GetNodeScheduler(ctx, req.(*GetNodeSchedulerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeSchedulerService_ServiceDesc is the grpc.ServiceDesc for NodeSchedulerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeSchedulerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nodescheduler.NodeSchedulerService",
	HandlerType: (*NodeSchedulerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNodeSchedulers",
			Handler:    _NodeSchedulerService_GetNodeSchedulers_Handler,
		},
		{
			MethodName: "GetNodeScheduler",
			Handler:    _NodeSchedulerService_GetNodeScheduler_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nodescheduler.proto",
}
