syntax = "proto3";

package scheduledjob;

option go_package = "pb/scheduledjob;scheduledjob";

service ScheduledJobService {
  rpc CreateOneOffScheduledJob (CreateOneOffScheduledJobRequest) returns (CreateScheduledJobResponse);
  rpc CreateRecurringScheduledJob (CreateRecurringScheduledJobRequest) returns (CreateScheduledJobResponse);
  rpc GetScheduledJob (GetScheduledJobRequest) returns (GetScheduledJobResponse);
  rpc ListScheduledJobs (ListScheduledJobsRequest) returns (ListScheduledJobsResponse);
  rpc DeleteScheduledJob (DeleteScheduledJobRequest) returns (DeleteScheduledJobResponse);
}

message CreateOneOffScheduledJobRequest {
  string tenantCode = 1;
  string queueCode = 2;
  string vnamespace = 3;
  string content = 4;
  string contentType = 5;
  map<string, string> headers = 6;
  string handler = 7;
  map<string, string> parameters = 8;
  int32 priority = 9;
  string runAt = 10;     // Specific UTC Date/Time ISO string
  string runAfter = 11;  // Duration string (e.g., "5m")
  string code = 12;      // Optional unique idempotency code
}

message CreateRecurringScheduledJobRequest {
  string tenantCode = 1;
  string queueCode = 2;
  string vnamespace = 3;
  string content = 4;
  string contentType = 5;
  map<string, string> headers = 6;
  string handler = 7;
  map<string, string> parameters = 8;
  int32 priority = 9;
  string every = 10;           // Duration string (e.g., "5m", "1h")
  string cronExpression = 11;  // Cron expression (e.g., "0 0 * * *")
  string code = 12;            // Optional unique idempotency code
}

message ScheduledJob {
  string id = 1;
  string code = 2;
  string tenantId = 3;
  string queueId = 4;
  string queueCode = 5;
  string vnamespace = 6;
  string content = 7;
  string contentType = 8;
  map<string, string> headers = 9;
  string handler = 10;
  map<string, string> parameters = 11;
  int32 priority = 12;
  string state = 13;
  string type = 14;
  string every = 15;
  string cronExpression = 16;
  string runAt = 17;
  string runAfter = 18;
  string nextRunAt = 19;
  string createdAt = 20;
  string updatedAt = 21;
}

message CreateScheduledJobResponse {
  string message = 1;
  ScheduledJob result = 2;
}

message GetScheduledJobRequest {
  string tenantCode = 1;
  string id = 2;
}

message GetScheduledJobResponse {
  string message = 1;
  ScheduledJob result = 2;
}

message ListScheduledJobsRequest {
  string tenantCode = 1;
  string vnamespace = 2;
  string cursor = 3;
  int32 pageSize = 4;
}

message ScheduledJobFindResult {
  repeated ScheduledJob entities = 1;
  string cursor = 2;
}

message ListScheduledJobsResponse {
  string message = 1;
  ScheduledJobFindResult result = 2;
}

message DeleteScheduledJobRequest {
  string tenantCode = 1;
  string id = 2;
}

message DeleteScheduledJobResponse {
  string message = 1;
}
