// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: scheduled_job.proto

package scheduledjob

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ScheduledJobServiceClient is the client API for ScheduledJobService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScheduledJobServiceClient interface {
	CreateOneOffScheduledJob(ctx context.Context, in *CreateOneOffScheduledJobRequest, opts ...grpc.CallOption) (*CreateScheduledJobResponse, error)
	CreateRecurringScheduledJob(ctx context.Context, in *CreateRecurringScheduledJobRequest, opts ...grpc.CallOption) (*CreateScheduledJobResponse, error)
	GetScheduledJob(ctx context.Context, in *GetScheduledJobRequest, opts ...grpc.CallOption) (*GetScheduledJobResponse, error)
	ListScheduledJobs(ctx context.Context, in *ListScheduledJobsRequest, opts ...grpc.CallOption) (*ListScheduledJobsResponse, error)
	DeleteScheduledJob(ctx context.Context, in *DeleteScheduledJobRequest, opts ...grpc.CallOption) (*DeleteScheduledJobResponse, error)
}

type scheduledJobServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScheduledJobServiceClient(cc grpc.ClientConnInterface) ScheduledJobServiceClient {
	return &scheduledJobServiceClient{cc}
}

func (c *scheduledJobServiceClient) CreateOneOffScheduledJob(ctx context.Context, in *CreateOneOffScheduledJobRequest, opts ...grpc.CallOption) (*CreateScheduledJobResponse, error) {
	out := new(CreateScheduledJobResponse)
	err := c.cc.Invoke(ctx, "/scheduledjob.ScheduledJobService/CreateOneOffScheduledJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduledJobServiceClient) CreateRecurringScheduledJob(ctx context.Context, in *CreateRecurringScheduledJobRequest, opts ...grpc.CallOption) (*CreateScheduledJobResponse, error) {
	out := new(CreateScheduledJobResponse)
	err := c.cc.Invoke(ctx, "/scheduledjob.ScheduledJobService/CreateRecurringScheduledJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduledJobServiceClient) GetScheduledJob(ctx context.Context, in *GetScheduledJobRequest, opts ...grpc.CallOption) (*GetScheduledJobResponse, error) {
	out := new(GetScheduledJobResponse)
	err := c.cc.Invoke(ctx, "/scheduledjob.ScheduledJobService/GetScheduledJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduledJobServiceClient) ListScheduledJobs(ctx context.Context, in *ListScheduledJobsRequest, opts ...grpc.CallOption) (*ListScheduledJobsResponse, error) {
	out := new(ListScheduledJobsResponse)
	err := c.cc.Invoke(ctx, "/scheduledjob.ScheduledJobService/ListScheduledJobs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduledJobServiceClient) DeleteScheduledJob(ctx context.Context, in *DeleteScheduledJobRequest, opts ...grpc.CallOption) (*DeleteScheduledJobResponse, error) {
	out := new(DeleteScheduledJobResponse)
	err := c.cc.Invoke(ctx, "/scheduledjob.ScheduledJobService/DeleteScheduledJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScheduledJobServiceServer is the server API for ScheduledJobService service.
// All implementations must embed UnimplementedScheduledJobServiceServer
// for forward compatibility
type ScheduledJobServiceServer interface {
	CreateOneOffScheduledJob(context.Context, *CreateOneOffScheduledJobRequest) (*CreateScheduledJobResponse, error)
	CreateRecurringScheduledJob(context.Context, *CreateRecurringScheduledJobRequest) (*CreateScheduledJobResponse, error)
	GetScheduledJob(context.Context, *GetScheduledJobRequest) (*GetScheduledJobResponse, error)
	ListScheduledJobs(context.Context, *ListScheduledJobsRequest) (*ListScheduledJobsResponse, error)
	DeleteScheduledJob(context.Context, *DeleteScheduledJobRequest) (*DeleteScheduledJobResponse, error)
	mustEmbedUnimplementedScheduledJobServiceServer()
}

// UnimplementedScheduledJobServiceServer must be embedded to have forward compatible implementations.
type UnimplementedScheduledJobServiceServer struct {
}

func (UnimplementedScheduledJobServiceServer) CreateOneOffScheduledJob(context.Context, *CreateOneOffScheduledJobRequest) (*CreateScheduledJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOneOffScheduledJob not implemented")
}
func (UnimplementedScheduledJobServiceServer) CreateRecurringScheduledJob(context.Context, *CreateRecurringScheduledJobRequest) (*CreateScheduledJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRecurringScheduledJob not implemented")
}
func (UnimplementedScheduledJobServiceServer) GetScheduledJob(context.Context, *GetScheduledJobRequest) (*GetScheduledJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScheduledJob not implemented")
}
func (UnimplementedScheduledJobServiceServer) ListScheduledJobs(context.Context, *ListScheduledJobsRequest) (*ListScheduledJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListScheduledJobs not implemented")
}
func (UnimplementedScheduledJobServiceServer) DeleteScheduledJob(context.Context, *DeleteScheduledJobRequest) (*DeleteScheduledJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteScheduledJob not implemented")
}
func (UnimplementedScheduledJobServiceServer) mustEmbedUnimplementedScheduledJobServiceServer() {}

// UnsafeScheduledJobServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScheduledJobServiceServer will
// result in compilation errors.
type UnsafeScheduledJobServiceServer interface {
	mustEmbedUnimplementedScheduledJobServiceServer()
}

func RegisterScheduledJobServiceServer(s grpc.ServiceRegistrar, srv ScheduledJobServiceServer) {
	s.RegisterService(&ScheduledJobService_ServiceDesc, srv)
}

func _ScheduledJobService_CreateOneOffScheduledJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOneOffScheduledJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduledJobServiceServer).CreateOneOffScheduledJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scheduledjob.ScheduledJobService/CreateOneOffScheduledJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduledJobServiceServer).CreateOneOffScheduledJob(ctx, req.(*CreateOneOffScheduledJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduledJobService_CreateRecurringScheduledJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRecurringScheduledJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduledJobServiceServer).CreateRecurringScheduledJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scheduledjob.ScheduledJobService/CreateRecurringScheduledJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduledJobServiceServer).CreateRecurringScheduledJob(ctx, req.(*CreateRecurringScheduledJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduledJobService_GetScheduledJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScheduledJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduledJobServiceServer).GetScheduledJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scheduledjob.ScheduledJobService/GetScheduledJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduledJobServiceServer).GetScheduledJob(ctx, req.(*GetScheduledJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduledJobService_ListScheduledJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListScheduledJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduledJobServiceServer).ListScheduledJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scheduledjob.ScheduledJobService/ListScheduledJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduledJobServiceServer).ListScheduledJobs(ctx, req.(*ListScheduledJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduledJobService_DeleteScheduledJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteScheduledJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduledJobServiceServer).DeleteScheduledJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scheduledjob.ScheduledJobService/DeleteScheduledJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduledJobServiceServer).DeleteScheduledJob(ctx, req.(*DeleteScheduledJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScheduledJobService_ServiceDesc is the grpc.ServiceDesc for ScheduledJobService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScheduledJobService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scheduledjob.ScheduledJobService",
	HandlerType: (*ScheduledJobServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOneOffScheduledJob",
			Handler:    _ScheduledJobService_CreateOneOffScheduledJob_Handler,
		},
		{
			MethodName: "CreateRecurringScheduledJob",
			Handler:    _ScheduledJobService_CreateRecurringScheduledJob_Handler,
		},
		{
			MethodName: "GetScheduledJob",
			Handler:    _ScheduledJobService_GetScheduledJob_Handler,
		},
		{
			MethodName: "ListScheduledJobs",
			Handler:    _ScheduledJobService_ListScheduledJobs_Handler,
		},
		{
			MethodName: "DeleteScheduledJob",
			Handler:    _ScheduledJobService_DeleteScheduledJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scheduled_job.proto",
}
