// source: nodescheduler.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

goog.exportSymbol('proto.nodescheduler.GetNodeSchedulerRequest', null, global);
goog.exportSymbol('proto.nodescheduler.GetNodeSchedulerResponse', null, global);
goog.exportSymbol('proto.nodescheduler.GetNodeSchedulersRequest', null, global);
goog.exportSymbol('proto.nodescheduler.GetNodeSchedulersResponse', null, global);
goog.exportSymbol('proto.nodescheduler.NodeScheduler', null, global);
goog.exportSymbol('proto.nodescheduler.NodeSchedulerFindResult', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nodescheduler.GetNodeSchedulersRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.nodescheduler.GetNodeSchedulersRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nodescheduler.GetNodeSchedulersRequest.displayName = 'proto.nodescheduler.GetNodeSchedulersRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nodescheduler.NodeScheduler = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.nodescheduler.NodeScheduler, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nodescheduler.NodeScheduler.displayName = 'proto.nodescheduler.NodeScheduler';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nodescheduler.NodeSchedulerFindResult = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.nodescheduler.NodeSchedulerFindResult.repeatedFields_, null);
};
goog.inherits(proto.nodescheduler.NodeSchedulerFindResult, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nodescheduler.NodeSchedulerFindResult.displayName = 'proto.nodescheduler.NodeSchedulerFindResult';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nodescheduler.GetNodeSchedulersResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.nodescheduler.GetNodeSchedulersResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nodescheduler.GetNodeSchedulersResponse.displayName = 'proto.nodescheduler.GetNodeSchedulersResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nodescheduler.GetNodeSchedulerRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.nodescheduler.GetNodeSchedulerRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nodescheduler.GetNodeSchedulerRequest.displayName = 'proto.nodescheduler.GetNodeSchedulerRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nodescheduler.GetNodeSchedulerResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.nodescheduler.GetNodeSchedulerResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nodescheduler.GetNodeSchedulerResponse.displayName = 'proto.nodescheduler.GetNodeSchedulerResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nodescheduler.GetNodeSchedulersRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.nodescheduler.GetNodeSchedulersRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nodescheduler.GetNodeSchedulersRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nodescheduler.GetNodeSchedulersRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    q: jspb.Message.getFieldWithDefault(msg, 1, ""),
    cursor: jspb.Message.getFieldWithDefault(msg, 2, ""),
    pagesize: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nodescheduler.GetNodeSchedulersRequest}
 */
proto.nodescheduler.GetNodeSchedulersRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nodescheduler.GetNodeSchedulersRequest;
  return proto.nodescheduler.GetNodeSchedulersRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nodescheduler.GetNodeSchedulersRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nodescheduler.GetNodeSchedulersRequest}
 */
proto.nodescheduler.GetNodeSchedulersRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setQ(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCursor(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPagesize(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nodescheduler.GetNodeSchedulersRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nodescheduler.GetNodeSchedulersRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nodescheduler.GetNodeSchedulersRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nodescheduler.GetNodeSchedulersRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getQ();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCursor();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPagesize();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * optional string q = 1;
 * @return {string}
 */
proto.nodescheduler.GetNodeSchedulersRequest.prototype.getQ = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.nodescheduler.GetNodeSchedulersRequest} returns this
 */
proto.nodescheduler.GetNodeSchedulersRequest.prototype.setQ = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string cursor = 2;
 * @return {string}
 */
proto.nodescheduler.GetNodeSchedulersRequest.prototype.getCursor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.nodescheduler.GetNodeSchedulersRequest} returns this
 */
proto.nodescheduler.GetNodeSchedulersRequest.prototype.setCursor = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 pageSize = 3;
 * @return {number}
 */
proto.nodescheduler.GetNodeSchedulersRequest.prototype.getPagesize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.nodescheduler.GetNodeSchedulersRequest} returns this
 */
proto.nodescheduler.GetNodeSchedulersRequest.prototype.setPagesize = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nodescheduler.NodeScheduler.prototype.toObject = function(opt_includeInstance) {
  return proto.nodescheduler.NodeScheduler.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nodescheduler.NodeScheduler} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nodescheduler.NodeScheduler.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    ttl: jspb.Message.getFieldWithDefault(msg, 3, 0),
    lastheartbeat: jspb.Message.getFieldWithDefault(msg, 4, ""),
    informationMap: (f = msg.getInformationMap()) ? f.toObject(includeInstance, undefined) : [],
    connectionstatus: jspb.Message.getFieldWithDefault(msg, 6, ""),
    createdat: jspb.Message.getFieldWithDefault(msg, 7, ""),
    updatedat: jspb.Message.getFieldWithDefault(msg, 8, ""),
    assignedtenantnodeindex: jspb.Message.getFieldWithDefault(msg, 9, 0),
    runningstatus: jspb.Message.getFieldWithDefault(msg, 10, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nodescheduler.NodeScheduler}
 */
proto.nodescheduler.NodeScheduler.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nodescheduler.NodeScheduler;
  return proto.nodescheduler.NodeScheduler.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nodescheduler.NodeScheduler} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nodescheduler.NodeScheduler}
 */
proto.nodescheduler.NodeScheduler.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTtl(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setLastheartbeat(value);
      break;
    case 5:
      var value = msg.getInformationMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setConnectionstatus(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setCreatedat(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setUpdatedat(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAssignedtenantnodeindex(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setRunningstatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nodescheduler.NodeScheduler.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nodescheduler.NodeScheduler.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nodescheduler.NodeScheduler} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nodescheduler.NodeScheduler.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTtl();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getLastheartbeat();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getInformationMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(5, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getConnectionstatus();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getCreatedat();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getUpdatedat();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getAssignedtenantnodeindex();
  if (f !== 0) {
    writer.writeInt32(
      9,
      f
    );
  }
  f = message.getRunningstatus();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
};


/**
 * optional string ID = 1;
 * @return {string}
 */
proto.nodescheduler.NodeScheduler.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.nodescheduler.NodeScheduler} returns this
 */
proto.nodescheduler.NodeScheduler.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string Name = 2;
 * @return {string}
 */
proto.nodescheduler.NodeScheduler.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.nodescheduler.NodeScheduler} returns this
 */
proto.nodescheduler.NodeScheduler.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int64 TTL = 3;
 * @return {number}
 */
proto.nodescheduler.NodeScheduler.prototype.getTtl = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.nodescheduler.NodeScheduler} returns this
 */
proto.nodescheduler.NodeScheduler.prototype.setTtl = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string LastHeartbeat = 4;
 * @return {string}
 */
proto.nodescheduler.NodeScheduler.prototype.getLastheartbeat = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.nodescheduler.NodeScheduler} returns this
 */
proto.nodescheduler.NodeScheduler.prototype.setLastheartbeat = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * map<string, string> Information = 5;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.nodescheduler.NodeScheduler.prototype.getInformationMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 5, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.nodescheduler.NodeScheduler} returns this
 */
proto.nodescheduler.NodeScheduler.prototype.clearInformationMap = function() {
  this.getInformationMap().clear();
  return this;};


/**
 * optional string ConnectionStatus = 6;
 * @return {string}
 */
proto.nodescheduler.NodeScheduler.prototype.getConnectionstatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.nodescheduler.NodeScheduler} returns this
 */
proto.nodescheduler.NodeScheduler.prototype.setConnectionstatus = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string CreatedAt = 7;
 * @return {string}
 */
proto.nodescheduler.NodeScheduler.prototype.getCreatedat = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.nodescheduler.NodeScheduler} returns this
 */
proto.nodescheduler.NodeScheduler.prototype.setCreatedat = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string UpdatedAt = 8;
 * @return {string}
 */
proto.nodescheduler.NodeScheduler.prototype.getUpdatedat = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.nodescheduler.NodeScheduler} returns this
 */
proto.nodescheduler.NodeScheduler.prototype.setUpdatedat = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional int32 AssignedTenantNodeIndex = 9;
 * @return {number}
 */
proto.nodescheduler.NodeScheduler.prototype.getAssignedtenantnodeindex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.nodescheduler.NodeScheduler} returns this
 */
proto.nodescheduler.NodeScheduler.prototype.setAssignedtenantnodeindex = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional string RunningStatus = 10;
 * @return {string}
 */
proto.nodescheduler.NodeScheduler.prototype.getRunningstatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.nodescheduler.NodeScheduler} returns this
 */
proto.nodescheduler.NodeScheduler.prototype.setRunningstatus = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.nodescheduler.NodeSchedulerFindResult.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nodescheduler.NodeSchedulerFindResult.prototype.toObject = function(opt_includeInstance) {
  return proto.nodescheduler.NodeSchedulerFindResult.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nodescheduler.NodeSchedulerFindResult} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nodescheduler.NodeSchedulerFindResult.toObject = function(includeInstance, msg) {
  var f, obj = {
    entitiesList: jspb.Message.toObjectList(msg.getEntitiesList(),
    proto.nodescheduler.NodeScheduler.toObject, includeInstance),
    cursor: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nodescheduler.NodeSchedulerFindResult}
 */
proto.nodescheduler.NodeSchedulerFindResult.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nodescheduler.NodeSchedulerFindResult;
  return proto.nodescheduler.NodeSchedulerFindResult.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nodescheduler.NodeSchedulerFindResult} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nodescheduler.NodeSchedulerFindResult}
 */
proto.nodescheduler.NodeSchedulerFindResult.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.nodescheduler.NodeScheduler;
      reader.readMessage(value,proto.nodescheduler.NodeScheduler.deserializeBinaryFromReader);
      msg.addEntities(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCursor(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nodescheduler.NodeSchedulerFindResult.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nodescheduler.NodeSchedulerFindResult.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nodescheduler.NodeSchedulerFindResult} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nodescheduler.NodeSchedulerFindResult.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEntitiesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.nodescheduler.NodeScheduler.serializeBinaryToWriter
    );
  }
  f = message.getCursor();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * repeated NodeScheduler Entities = 1;
 * @return {!Array<!proto.nodescheduler.NodeScheduler>}
 */
proto.nodescheduler.NodeSchedulerFindResult.prototype.getEntitiesList = function() {
  return /** @type{!Array<!proto.nodescheduler.NodeScheduler>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.nodescheduler.NodeScheduler, 1));
};


/**
 * @param {!Array<!proto.nodescheduler.NodeScheduler>} value
 * @return {!proto.nodescheduler.NodeSchedulerFindResult} returns this
*/
proto.nodescheduler.NodeSchedulerFindResult.prototype.setEntitiesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.nodescheduler.NodeScheduler=} opt_value
 * @param {number=} opt_index
 * @return {!proto.nodescheduler.NodeScheduler}
 */
proto.nodescheduler.NodeSchedulerFindResult.prototype.addEntities = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.nodescheduler.NodeScheduler, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.nodescheduler.NodeSchedulerFindResult} returns this
 */
proto.nodescheduler.NodeSchedulerFindResult.prototype.clearEntitiesList = function() {
  return this.setEntitiesList([]);
};


/**
 * optional string Cursor = 2;
 * @return {string}
 */
proto.nodescheduler.NodeSchedulerFindResult.prototype.getCursor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.nodescheduler.NodeSchedulerFindResult} returns this
 */
proto.nodescheduler.NodeSchedulerFindResult.prototype.setCursor = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nodescheduler.GetNodeSchedulersResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.nodescheduler.GetNodeSchedulersResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nodescheduler.GetNodeSchedulersResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nodescheduler.GetNodeSchedulersResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    message: jspb.Message.getFieldWithDefault(msg, 1, ""),
    result: (f = msg.getResult()) && proto.nodescheduler.NodeSchedulerFindResult.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nodescheduler.GetNodeSchedulersResponse}
 */
proto.nodescheduler.GetNodeSchedulersResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nodescheduler.GetNodeSchedulersResponse;
  return proto.nodescheduler.GetNodeSchedulersResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nodescheduler.GetNodeSchedulersResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nodescheduler.GetNodeSchedulersResponse}
 */
proto.nodescheduler.GetNodeSchedulersResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    case 2:
      var value = new proto.nodescheduler.NodeSchedulerFindResult;
      reader.readMessage(value,proto.nodescheduler.NodeSchedulerFindResult.deserializeBinaryFromReader);
      msg.setResult(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nodescheduler.GetNodeSchedulersResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nodescheduler.GetNodeSchedulersResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nodescheduler.GetNodeSchedulersResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nodescheduler.GetNodeSchedulersResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getResult();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.nodescheduler.NodeSchedulerFindResult.serializeBinaryToWriter
    );
  }
};


/**
 * optional string message = 1;
 * @return {string}
 */
proto.nodescheduler.GetNodeSchedulersResponse.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.nodescheduler.GetNodeSchedulersResponse} returns this
 */
proto.nodescheduler.GetNodeSchedulersResponse.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional NodeSchedulerFindResult result = 2;
 * @return {?proto.nodescheduler.NodeSchedulerFindResult}
 */
proto.nodescheduler.GetNodeSchedulersResponse.prototype.getResult = function() {
  return /** @type{?proto.nodescheduler.NodeSchedulerFindResult} */ (
    jspb.Message.getWrapperField(this, proto.nodescheduler.NodeSchedulerFindResult, 2));
};


/**
 * @param {?proto.nodescheduler.NodeSchedulerFindResult|undefined} value
 * @return {!proto.nodescheduler.GetNodeSchedulersResponse} returns this
*/
proto.nodescheduler.GetNodeSchedulersResponse.prototype.setResult = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.nodescheduler.GetNodeSchedulersResponse} returns this
 */
proto.nodescheduler.GetNodeSchedulersResponse.prototype.clearResult = function() {
  return this.setResult(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nodescheduler.GetNodeSchedulersResponse.prototype.hasResult = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nodescheduler.GetNodeSchedulerRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.nodescheduler.GetNodeSchedulerRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nodescheduler.GetNodeSchedulerRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nodescheduler.GetNodeSchedulerRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nodescheduler.GetNodeSchedulerRequest}
 */
proto.nodescheduler.GetNodeSchedulerRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nodescheduler.GetNodeSchedulerRequest;
  return proto.nodescheduler.GetNodeSchedulerRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nodescheduler.GetNodeSchedulerRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nodescheduler.GetNodeSchedulerRequest}
 */
proto.nodescheduler.GetNodeSchedulerRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nodescheduler.GetNodeSchedulerRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nodescheduler.GetNodeSchedulerRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nodescheduler.GetNodeSchedulerRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nodescheduler.GetNodeSchedulerRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string ID = 1;
 * @return {string}
 */
proto.nodescheduler.GetNodeSchedulerRequest.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.nodescheduler.GetNodeSchedulerRequest} returns this
 */
proto.nodescheduler.GetNodeSchedulerRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nodescheduler.GetNodeSchedulerResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.nodescheduler.GetNodeSchedulerResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nodescheduler.GetNodeSchedulerResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nodescheduler.GetNodeSchedulerResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    message: jspb.Message.getFieldWithDefault(msg, 1, ""),
    result: (f = msg.getResult()) && proto.nodescheduler.NodeScheduler.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nodescheduler.GetNodeSchedulerResponse}
 */
proto.nodescheduler.GetNodeSchedulerResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nodescheduler.GetNodeSchedulerResponse;
  return proto.nodescheduler.GetNodeSchedulerResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nodescheduler.GetNodeSchedulerResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nodescheduler.GetNodeSchedulerResponse}
 */
proto.nodescheduler.GetNodeSchedulerResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    case 2:
      var value = new proto.nodescheduler.NodeScheduler;
      reader.readMessage(value,proto.nodescheduler.NodeScheduler.deserializeBinaryFromReader);
      msg.setResult(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nodescheduler.GetNodeSchedulerResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nodescheduler.GetNodeSchedulerResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nodescheduler.GetNodeSchedulerResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nodescheduler.GetNodeSchedulerResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getResult();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.nodescheduler.NodeScheduler.serializeBinaryToWriter
    );
  }
};


/**
 * optional string message = 1;
 * @return {string}
 */
proto.nodescheduler.GetNodeSchedulerResponse.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.nodescheduler.GetNodeSchedulerResponse} returns this
 */
proto.nodescheduler.GetNodeSchedulerResponse.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional NodeScheduler result = 2;
 * @return {?proto.nodescheduler.NodeScheduler}
 */
proto.nodescheduler.GetNodeSchedulerResponse.prototype.getResult = function() {
  return /** @type{?proto.nodescheduler.NodeScheduler} */ (
    jspb.Message.getWrapperField(this, proto.nodescheduler.NodeScheduler, 2));
};


/**
 * @param {?proto.nodescheduler.NodeScheduler|undefined} value
 * @return {!proto.nodescheduler.GetNodeSchedulerResponse} returns this
*/
proto.nodescheduler.GetNodeSchedulerResponse.prototype.setResult = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.nodescheduler.GetNodeSchedulerResponse} returns this
 */
proto.nodescheduler.GetNodeSchedulerResponse.prototype.clearResult = function() {
  return this.setResult(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nodescheduler.GetNodeSchedulerResponse.prototype.hasResult = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.nodescheduler);
