// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: server/internal/infrastructure/server/grpc/proto/definitions/tenant.proto

package tenant

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TenantInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantInfoRequest) Reset() {
	*x = TenantInfoRequest{}
	mi := &file_server_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantInfoRequest) ProtoMessage() {}

func (x *TenantInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantInfoRequest.ProtoReflect.Descriptor instead.
func (*TenantInfoRequest) Descriptor() ([]byte, []int) {
	return file_server_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDescGZIP(), []int{0}
}

func (x *TenantInfoRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type TenantInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`
	ShardId       int64                  `protobuf:"varint,3,opt,name=ShardId,proto3" json:"ShardId,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=Status,proto3" json:"Status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantInfoResponse) Reset() {
	*x = TenantInfoResponse{}
	mi := &file_server_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantInfoResponse) ProtoMessage() {}

func (x *TenantInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantInfoResponse.ProtoReflect.Descriptor instead.
func (*TenantInfoResponse) Descriptor() ([]byte, []int) {
	return file_server_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDescGZIP(), []int{1}
}

func (x *TenantInfoResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *TenantInfoResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *TenantInfoResponse) GetShardId() int64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *TenantInfoResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TenantInfoResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TenantInfoResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type AssertTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssertTenantRequest) Reset() {
	*x = AssertTenantRequest{}
	mi := &file_server_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssertTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssertTenantRequest) ProtoMessage() {}

func (x *AssertTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssertTenantRequest.ProtoReflect.Descriptor instead.
func (*AssertTenantRequest) Descriptor() ([]byte, []int) {
	return file_server_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDescGZIP(), []int{2}
}

func (x *AssertTenantRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type AssertTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`
	ShardId       int64                  `protobuf:"varint,3,opt,name=ShardId,proto3" json:"ShardId,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=Status,proto3" json:"Status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssertTenantResponse) Reset() {
	*x = AssertTenantResponse{}
	mi := &file_server_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssertTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssertTenantResponse) ProtoMessage() {}

func (x *AssertTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssertTenantResponse.ProtoReflect.Descriptor instead.
func (*AssertTenantResponse) Descriptor() ([]byte, []int) {
	return file_server_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDescGZIP(), []int{3}
}

func (x *AssertTenantResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *AssertTenantResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AssertTenantResponse) GetShardId() int64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *AssertTenantResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AssertTenantResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AssertTenantResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_server_internal_infrastructure_server_grpc_proto_definitions_tenant_proto protoreflect.FileDescriptor

const file_server_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDesc = "" +
	"\n" +
	"Iserver/internal/infrastructure/server/grpc/proto/definitions/tenant.proto\x12\x06tenant\"#\n" +
	"\x11TenantInfoRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"\xa6\x01\n" +
	"\x12TenantInfoResponse\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04Code\x18\x02 \x01(\tR\x04Code\x12\x18\n" +
	"\aShardId\x18\x03 \x01(\x03R\aShardId\x12\x16\n" +
	"\x06Status\x18\x04 \x01(\tR\x06Status\x12\x1c\n" +
	"\tCreatedAt\x18\x05 \x01(\tR\tCreatedAt\x12\x1c\n" +
	"\tUpdatedAt\x18\x06 \x01(\tR\tUpdatedAt\")\n" +
	"\x13AssertTenantRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"\xa8\x01\n" +
	"\x14AssertTenantResponse\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04Code\x18\x02 \x01(\tR\x04Code\x12\x18\n" +
	"\aShardId\x18\x03 \x01(\x03R\aShardId\x12\x16\n" +
	"\x06Status\x18\x04 \x01(\tR\x06Status\x12\x1c\n" +
	"\tCreatedAt\x18\x05 \x01(\tR\tCreatedAt\x12\x1c\n" +
	"\tUpdatedAt\x18\x06 \x01(\tR\tUpdatedAt2\xa2\x01\n" +
	"\rTenantService\x12F\n" +
	"\rGetTenantInfo\x12\x19.tenant.TenantInfoRequest\x1a\x1a.tenant.TenantInfoResponse\x12I\n" +
	"\fAssertTenant\x12\x1b.tenant.AssertTenantRequest\x1a\x1c.tenant.AssertTenantResponseB\x12Z\x10pb/tenant;tenantb\x06proto3"

var (
	file_server_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDescOnce sync.Once
	file_server_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDescData []byte
)

func file_server_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDescGZIP() []byte {
	file_server_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDescOnce.Do(func() {
		file_server_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDesc), len(file_server_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDesc)))
	})
	return file_server_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDescData
}

var file_server_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_server_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_goTypes = []any{
	(*TenantInfoRequest)(nil),    // 0: tenant.TenantInfoRequest
	(*TenantInfoResponse)(nil),   // 1: tenant.TenantInfoResponse
	(*AssertTenantRequest)(nil),  // 2: tenant.AssertTenantRequest
	(*AssertTenantResponse)(nil), // 3: tenant.AssertTenantResponse
}
var file_server_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_depIdxs = []int32{
	0, // 0: tenant.TenantService.GetTenantInfo:input_type -> tenant.TenantInfoRequest
	2, // 1: tenant.TenantService.AssertTenant:input_type -> tenant.AssertTenantRequest
	1, // 2: tenant.TenantService.GetTenantInfo:output_type -> tenant.TenantInfoResponse
	3, // 3: tenant.TenantService.AssertTenant:output_type -> tenant.AssertTenantResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_server_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_init() }
func file_server_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_init() {
	if File_server_internal_infrastructure_server_grpc_proto_definitions_tenant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDesc), len(file_server_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_goTypes,
		DependencyIndexes: file_server_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_depIdxs,
		MessageInfos:      file_server_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes,
	}.Build()
	File_server_internal_infrastructure_server_grpc_proto_definitions_tenant_proto = out.File
	file_server_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_goTypes = nil
	file_server_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_depIdxs = nil
}
