// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/infrastructure/server/grpc/proto/definitions/tenant.proto

package tenant

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TenantInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantInfoRequest) Reset() {
	*x = TenantInfoRequest{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantInfoRequest) ProtoMessage() {}

func (x *TenantInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantInfoRequest.ProtoReflect.Descriptor instead.
func (*TenantInfoRequest) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDescGZIP(), []int{0}
}

func (x *TenantInfoRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type TenantSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantSummaryRequest) Reset() {
	*x = TenantSummaryRequest{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantSummaryRequest) ProtoMessage() {}

func (x *TenantSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantSummaryRequest.ProtoReflect.Descriptor instead.
func (*TenantSummaryRequest) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDescGZIP(), []int{1}
}

func (x *TenantSummaryRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type TenantSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ID             string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	TenantId       string                 `protobuf:"bytes,2,opt,name=TenantId,proto3" json:"TenantId,omitempty"`
	Code           string                 `protobuf:"bytes,3,opt,name=Code,proto3" json:"Code,omitempty"`
	ExchangesCount int32                  `protobuf:"varint,4,opt,name=ExchangesCount,proto3" json:"ExchangesCount,omitempty"`
	QueuesCount    int32                  `protobuf:"varint,5,opt,name=QueuesCount,proto3" json:"QueuesCount,omitempty"`
	MessagesCount  int32                  `protobuf:"varint,6,opt,name=MessagesCount,proto3" json:"MessagesCount,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,7,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,8,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TenantSummary) Reset() {
	*x = TenantSummary{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantSummary) ProtoMessage() {}

func (x *TenantSummary) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantSummary.ProtoReflect.Descriptor instead.
func (*TenantSummary) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDescGZIP(), []int{2}
}

func (x *TenantSummary) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *TenantSummary) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TenantSummary) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *TenantSummary) GetExchangesCount() int32 {
	if x != nil {
		return x.ExchangesCount
	}
	return 0
}

func (x *TenantSummary) GetQueuesCount() int32 {
	if x != nil {
		return x.QueuesCount
	}
	return 0
}

func (x *TenantSummary) GetMessagesCount() int32 {
	if x != nil {
		return x.MessagesCount
	}
	return 0
}

func (x *TenantSummary) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TenantSummary) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type TenantSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Result        *TenantSummary         `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantSummaryResponse) Reset() {
	*x = TenantSummaryResponse{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantSummaryResponse) ProtoMessage() {}

func (x *TenantSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantSummaryResponse.ProtoReflect.Descriptor instead.
func (*TenantSummaryResponse) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDescGZIP(), []int{3}
}

func (x *TenantSummaryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TenantSummaryResponse) GetResult() *TenantSummary {
	if x != nil {
		return x.Result
	}
	return nil
}

type SelfMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IP            string                 `protobuf:"bytes,1,opt,name=IP,proto3" json:"IP,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=Port,proto3" json:"Port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelfMember) Reset() {
	*x = SelfMember{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelfMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelfMember) ProtoMessage() {}

func (x *SelfMember) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelfMember.ProtoReflect.Descriptor instead.
func (*SelfMember) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDescGZIP(), []int{4}
}

func (x *SelfMember) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

func (x *SelfMember) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SelfMember    *SelfMember            `protobuf:"bytes,1,opt,name=SelfMember,proto3" json:"SelfMember,omitempty"`
	ShardID       uint64                 `protobuf:"varint,2,opt,name=ShardID,proto3" json:"ShardID,omitempty"`
	Roles         []string               `protobuf:"bytes,3,rep,name=Roles,proto3" json:"Roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDescGZIP(), []int{5}
}

func (x *Node) GetSelfMember() *SelfMember {
	if x != nil {
		return x.SelfMember
	}
	return nil
}

func (x *Node) GetShardID() uint64 {
	if x != nil {
		return x.ShardID
	}
	return 0
}

func (x *Node) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type TenantInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Result        *Tenant                `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Node          *Node                  `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantInfoResponse) Reset() {
	*x = TenantInfoResponse{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantInfoResponse) ProtoMessage() {}

func (x *TenantInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantInfoResponse.ProtoReflect.Descriptor instead.
func (*TenantInfoResponse) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDescGZIP(), []int{6}
}

func (x *TenantInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TenantInfoResponse) GetResult() *Tenant {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *TenantInfoResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type DeleteTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTenantRequest) Reset() {
	*x = DeleteTenantRequest{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTenantRequest) ProtoMessage() {}

func (x *DeleteTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTenantRequest.ProtoReflect.Descriptor instead.
func (*DeleteTenantRequest) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteTenantRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type DeleteTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTenantResponse) Reset() {
	*x = DeleteTenantResponse{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTenantResponse) ProtoMessage() {}

func (x *DeleteTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTenantResponse.ProtoReflect.Descriptor instead.
func (*DeleteTenantResponse) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteTenantResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetTenantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Q             string                 `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantsRequest) Reset() {
	*x = GetTenantsRequest{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantsRequest) ProtoMessage() {}

func (x *GetTenantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantsRequest.ProtoReflect.Descriptor instead.
func (*GetTenantsRequest) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDescGZIP(), []int{9}
}

func (x *GetTenantsRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *GetTenantsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *GetTenantsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type Tenant struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ID             string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Code           string                 `protobuf:"bytes,3,opt,name=Code,proto3" json:"Code,omitempty"`
	ShardId        int64                  `protobuf:"varint,4,opt,name=ShardId,proto3" json:"ShardId,omitempty"`
	Status         string                 `protobuf:"bytes,5,opt,name=Status,proto3" json:"Status,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,7,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	ExchangesCount int32                  `protobuf:"varint,8,opt,name=ExchangesCount,proto3" json:"ExchangesCount,omitempty"`
	QueuesCount    int32                  `protobuf:"varint,9,opt,name=QueuesCount,proto3" json:"QueuesCount,omitempty"`
	MessagesCount  int32                  `protobuf:"varint,10,opt,name=MessagesCount,proto3" json:"MessagesCount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Tenant) Reset() {
	*x = Tenant{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tenant) ProtoMessage() {}

func (x *Tenant) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tenant.ProtoReflect.Descriptor instead.
func (*Tenant) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDescGZIP(), []int{10}
}

func (x *Tenant) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Tenant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tenant) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Tenant) GetShardId() int64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *Tenant) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Tenant) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Tenant) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Tenant) GetExchangesCount() int32 {
	if x != nil {
		return x.ExchangesCount
	}
	return 0
}

func (x *Tenant) GetQueuesCount() int32 {
	if x != nil {
		return x.QueuesCount
	}
	return 0
}

func (x *Tenant) GetMessagesCount() int32 {
	if x != nil {
		return x.MessagesCount
	}
	return 0
}

type FindResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*Tenant              `protobuf:"bytes,1,rep,name=Entities,proto3" json:"Entities,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=Cursor,proto3" json:"Cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindResult) Reset() {
	*x = FindResult{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindResult) ProtoMessage() {}

func (x *FindResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindResult.ProtoReflect.Descriptor instead.
func (*FindResult) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDescGZIP(), []int{11}
}

func (x *FindResult) GetEntities() []*Tenant {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *FindResult) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type GetTenantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Result        *FindResult            `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantsResponse) Reset() {
	*x = GetTenantsResponse{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantsResponse) ProtoMessage() {}

func (x *GetTenantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantsResponse.ProtoReflect.Descriptor instead.
func (*GetTenantsResponse) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDescGZIP(), []int{12}
}

func (x *GetTenantsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetTenantsResponse) GetResult() *FindResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type AssertTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssertTenantRequest) Reset() {
	*x = AssertTenantRequest{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssertTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssertTenantRequest) ProtoMessage() {}

func (x *AssertTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssertTenantRequest.ProtoReflect.Descriptor instead.
func (*AssertTenantRequest) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDescGZIP(), []int{13}
}

func (x *AssertTenantRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AssertTenantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AssertBulkTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenants       []*AssertTenantRequest `protobuf:"bytes,1,rep,name=tenants,proto3" json:"tenants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssertBulkTenantRequest) Reset() {
	*x = AssertBulkTenantRequest{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssertBulkTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssertBulkTenantRequest) ProtoMessage() {}

func (x *AssertBulkTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssertBulkTenantRequest.ProtoReflect.Descriptor instead.
func (*AssertBulkTenantRequest) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDescGZIP(), []int{14}
}

func (x *AssertBulkTenantRequest) GetTenants() []*AssertTenantRequest {
	if x != nil {
		return x.Tenants
	}
	return nil
}

type AssertBulkTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Result        []*Tenant              `protobuf:"bytes,2,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssertBulkTenantResponse) Reset() {
	*x = AssertBulkTenantResponse{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssertBulkTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssertBulkTenantResponse) ProtoMessage() {}

func (x *AssertBulkTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssertBulkTenantResponse.ProtoReflect.Descriptor instead.
func (*AssertBulkTenantResponse) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDescGZIP(), []int{15}
}

func (x *AssertBulkTenantResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AssertBulkTenantResponse) GetResult() []*Tenant {
	if x != nil {
		return x.Result
	}
	return nil
}

type AssertTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Result        *Tenant                `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssertTenantResponse) Reset() {
	*x = AssertTenantResponse{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssertTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssertTenantResponse) ProtoMessage() {}

func (x *AssertTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssertTenantResponse.ProtoReflect.Descriptor instead.
func (*AssertTenantResponse) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDescGZIP(), []int{16}
}

func (x *AssertTenantResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AssertTenantResponse) GetResult() *Tenant {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_internal_infrastructure_server_grpc_proto_definitions_tenant_proto protoreflect.FileDescriptor

const file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDesc = "" +
	"\n" +
	"Binternal/infrastructure/server/grpc/proto/definitions/tenant.proto\x12\x06tenant\"#\n" +
	"\x11TenantInfoRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"&\n" +
	"\x14TenantSummaryRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"\xfb\x01\n" +
	"\rTenantSummary\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x1a\n" +
	"\bTenantId\x18\x02 \x01(\tR\bTenantId\x12\x12\n" +
	"\x04Code\x18\x03 \x01(\tR\x04Code\x12&\n" +
	"\x0eExchangesCount\x18\x04 \x01(\x05R\x0eExchangesCount\x12 \n" +
	"\vQueuesCount\x18\x05 \x01(\x05R\vQueuesCount\x12$\n" +
	"\rMessagesCount\x18\x06 \x01(\x05R\rMessagesCount\x12\x1c\n" +
	"\tCreatedAt\x18\a \x01(\tR\tCreatedAt\x12\x1c\n" +
	"\tUpdatedAt\x18\b \x01(\tR\tUpdatedAt\"`\n" +
	"\x15TenantSummaryResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12-\n" +
	"\x06result\x18\x02 \x01(\v2\x15.tenant.TenantSummaryR\x06result\"0\n" +
	"\n" +
	"SelfMember\x12\x0e\n" +
	"\x02IP\x18\x01 \x01(\tR\x02IP\x12\x12\n" +
	"\x04Port\x18\x02 \x01(\x05R\x04Port\"j\n" +
	"\x04Node\x122\n" +
	"\n" +
	"SelfMember\x18\x01 \x01(\v2\x12.tenant.SelfMemberR\n" +
	"SelfMember\x12\x18\n" +
	"\aShardID\x18\x02 \x01(\x04R\aShardID\x12\x14\n" +
	"\x05Roles\x18\x03 \x03(\tR\x05Roles\"x\n" +
	"\x12TenantInfoResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12&\n" +
	"\x06result\x18\x02 \x01(\v2\x0e.tenant.TenantR\x06result\x12 \n" +
	"\x04node\x18\x03 \x01(\v2\f.tenant.NodeR\x04node\"%\n" +
	"\x13DeleteTenantRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"0\n" +
	"\x14DeleteTenantResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"U\n" +
	"\x11GetTenantsRequest\x12\f\n" +
	"\x01q\x18\x01 \x01(\tR\x01q\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x05R\bpageSize\"\x9e\x02\n" +
	"\x06Tenant\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x12\n" +
	"\x04Code\x18\x03 \x01(\tR\x04Code\x12\x18\n" +
	"\aShardId\x18\x04 \x01(\x03R\aShardId\x12\x16\n" +
	"\x06Status\x18\x05 \x01(\tR\x06Status\x12\x1c\n" +
	"\tCreatedAt\x18\x06 \x01(\tR\tCreatedAt\x12\x1c\n" +
	"\tUpdatedAt\x18\a \x01(\tR\tUpdatedAt\x12&\n" +
	"\x0eExchangesCount\x18\b \x01(\x05R\x0eExchangesCount\x12 \n" +
	"\vQueuesCount\x18\t \x01(\x05R\vQueuesCount\x12$\n" +
	"\rMessagesCount\x18\n" +
	" \x01(\x05R\rMessagesCount\"P\n" +
	"\n" +
	"FindResult\x12*\n" +
	"\bEntities\x18\x01 \x03(\v2\x0e.tenant.TenantR\bEntities\x12\x16\n" +
	"\x06Cursor\x18\x02 \x01(\tR\x06Cursor\"Z\n" +
	"\x12GetTenantsResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12*\n" +
	"\x06result\x18\x02 \x01(\v2\x12.tenant.FindResultR\x06result\"=\n" +
	"\x13AssertTenantRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"P\n" +
	"\x17AssertBulkTenantRequest\x125\n" +
	"\atenants\x18\x01 \x03(\v2\x1b.tenant.AssertTenantRequestR\atenants\"\\\n" +
	"\x18AssertBulkTenantResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12&\n" +
	"\x06result\x18\x02 \x03(\v2\x0e.tenant.TenantR\x06result\"X\n" +
	"\x14AssertTenantResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12&\n" +
	"\x06result\x18\x02 \x01(\v2\x0e.tenant.TenantR\x06result2\xda\x03\n" +
	"\rTenantService\x12F\n" +
	"\rGetTenantInfo\x12\x19.tenant.TenantInfoRequest\x1a\x1a.tenant.TenantInfoResponse\x12O\n" +
	"\x10GetTenantSummary\x12\x1c.tenant.TenantSummaryRequest\x1a\x1d.tenant.TenantSummaryResponse\x12I\n" +
	"\fAssertTenant\x12\x1b.tenant.AssertTenantRequest\x1a\x1c.tenant.AssertTenantResponse\x12U\n" +
	"\x10AssertBulkTenant\x12\x1f.tenant.AssertBulkTenantRequest\x1a .tenant.AssertBulkTenantResponse\x12I\n" +
	"\fDeleteTenant\x12\x1b.tenant.DeleteTenantRequest\x1a\x1c.tenant.DeleteTenantResponse\x12C\n" +
	"\n" +
	"GetTenants\x12\x19.tenant.GetTenantsRequest\x1a\x1a.tenant.GetTenantsResponseB\x12Z\x10pb/tenant;tenantb\x06proto3"

var (
	file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDescOnce sync.Once
	file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDescData []byte
)

func file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDescGZIP() []byte {
	file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDescOnce.Do(func() {
		file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDesc), len(file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDesc)))
	})
	return file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDescData
}

var file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_goTypes = []any{
	(*TenantInfoRequest)(nil),        // 0: tenant.TenantInfoRequest
	(*TenantSummaryRequest)(nil),     // 1: tenant.TenantSummaryRequest
	(*TenantSummary)(nil),            // 2: tenant.TenantSummary
	(*TenantSummaryResponse)(nil),    // 3: tenant.TenantSummaryResponse
	(*SelfMember)(nil),               // 4: tenant.SelfMember
	(*Node)(nil),                     // 5: tenant.Node
	(*TenantInfoResponse)(nil),       // 6: tenant.TenantInfoResponse
	(*DeleteTenantRequest)(nil),      // 7: tenant.DeleteTenantRequest
	(*DeleteTenantResponse)(nil),     // 8: tenant.DeleteTenantResponse
	(*GetTenantsRequest)(nil),        // 9: tenant.GetTenantsRequest
	(*Tenant)(nil),                   // 10: tenant.Tenant
	(*FindResult)(nil),               // 11: tenant.FindResult
	(*GetTenantsResponse)(nil),       // 12: tenant.GetTenantsResponse
	(*AssertTenantRequest)(nil),      // 13: tenant.AssertTenantRequest
	(*AssertBulkTenantRequest)(nil),  // 14: tenant.AssertBulkTenantRequest
	(*AssertBulkTenantResponse)(nil), // 15: tenant.AssertBulkTenantResponse
	(*AssertTenantResponse)(nil),     // 16: tenant.AssertTenantResponse
}
var file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_depIdxs = []int32{
	2,  // 0: tenant.TenantSummaryResponse.result:type_name -> tenant.TenantSummary
	4,  // 1: tenant.Node.SelfMember:type_name -> tenant.SelfMember
	10, // 2: tenant.TenantInfoResponse.result:type_name -> tenant.Tenant
	5,  // 3: tenant.TenantInfoResponse.node:type_name -> tenant.Node
	10, // 4: tenant.FindResult.Entities:type_name -> tenant.Tenant
	11, // 5: tenant.GetTenantsResponse.result:type_name -> tenant.FindResult
	13, // 6: tenant.AssertBulkTenantRequest.tenants:type_name -> tenant.AssertTenantRequest
	10, // 7: tenant.AssertBulkTenantResponse.result:type_name -> tenant.Tenant
	10, // 8: tenant.AssertTenantResponse.result:type_name -> tenant.Tenant
	0,  // 9: tenant.TenantService.GetTenantInfo:input_type -> tenant.TenantInfoRequest
	1,  // 10: tenant.TenantService.GetTenantSummary:input_type -> tenant.TenantSummaryRequest
	13, // 11: tenant.TenantService.AssertTenant:input_type -> tenant.AssertTenantRequest
	14, // 12: tenant.TenantService.AssertBulkTenant:input_type -> tenant.AssertBulkTenantRequest
	7,  // 13: tenant.TenantService.DeleteTenant:input_type -> tenant.DeleteTenantRequest
	9,  // 14: tenant.TenantService.GetTenants:input_type -> tenant.GetTenantsRequest
	6,  // 15: tenant.TenantService.GetTenantInfo:output_type -> tenant.TenantInfoResponse
	3,  // 16: tenant.TenantService.GetTenantSummary:output_type -> tenant.TenantSummaryResponse
	16, // 17: tenant.TenantService.AssertTenant:output_type -> tenant.AssertTenantResponse
	15, // 18: tenant.TenantService.AssertBulkTenant:output_type -> tenant.AssertBulkTenantResponse
	8,  // 19: tenant.TenantService.DeleteTenant:output_type -> tenant.DeleteTenantResponse
	12, // 20: tenant.TenantService.GetTenants:output_type -> tenant.GetTenantsResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_init() }
func file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_init() {
	if File_internal_infrastructure_server_grpc_proto_definitions_tenant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDesc), len(file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_goTypes,
		DependencyIndexes: file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_depIdxs,
		MessageInfos:      file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_msgTypes,
	}.Build()
	File_internal_infrastructure_server_grpc_proto_definitions_tenant_proto = out.File
	file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_goTypes = nil
	file_internal_infrastructure_server_grpc_proto_definitions_tenant_proto_depIdxs = nil
}
