package models

import "time"

// OAuthApp represents a Service Account / OAuth 2.0 Application registered within a tenant.
// SECURITY: ClientSecretHash stores a bcrypt hash. Plain-text secret is NEVER stored in database.
type OAuthApp struct {
	ID               string    `orm:"primary-key"`
	ClientID         string    `orm:"unique"`
	ClientSecretHash string    // bcrypt hash — NEVER returned via API
	Name             string    `orm:"data-only"`
	TenantID         string    `orm:"group-index"`
	Description      string    `orm:"data-only"`
	AllowedScopes    []string  `orm:"data-only"`
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (OAuthApp) TableName() string { return "oauth_apps" }

// CreateOAuthApp is the input DTO for creating a new OAuth application.
type CreateOAuthApp struct {
	ID            string
	ClientID      string   // pre-generated by BO layer
	ClientSecret  string   // plain text — hashed before storage; discarded after
	Name          string
	TenantID      string
	Description   string
	AllowedScopes []string
	Now           time.Time
}

// OAuthAppResponse is the safe read-only API response (no secret hash, no plain secret).
type OAuthAppResponse struct {
	ID            string    `json:"id"`
	ClientID      string    `json:"clientId"`
	Name          string    `json:"name"`
	TenantID      string    `json:"tenantId"`
	Description   string    `json:"description"`
	AllowedScopes []string  `json:"allowedScopes"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
}

// OAuthAppCreatedResponse is used ONLY for Create and RotateSecret responses.
// It includes the ONE-TIME plain-text clientSecret field.
type OAuthAppCreatedResponse struct {
	OAuthAppResponse
	ClientSecret string `json:"clientSecret"` // Returned ONCE, NEVER stored.
}
