package models

import "time"

// OAuthApp represents a Service Account / OAuth 2.0 Application registered within a tenant.
// It enables third-party integrations to authenticate via the Client Credentials flow.
//
// SECURITY CONTRACT:
//   - ClientSecretHash stores a bcrypt(cost=12) hash of the secret.
//   - The plain-text secret is NEVER stored anywhere. It is generated, returned ONCE
//     in the HTTP response, and then discarded.
type OAuthApp struct {
	ID               string   `orm:"primary-key"`
	ClientID         string   `orm:"unique"`                          // Public identifier — random 32-byte hex
	ClientSecretHash string                                              // bcrypt hash — NEVER returned via API
	Name             string   `orm:"unique-compound:0"`
	TenantID         string   `orm:"unique-compound:0,group-index"`   // compound(Name,TenantID) + O(1) group scan
	Description      string   `orm:"data-only"`
	AllowedScopes    []string `orm:"data-only"`
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (OAuthApp) TableName() string { return "oauth_apps" }

// CreateOAuthApp is the input DTO used internally when creating a new OAuth application.
// ClientID and ClientSecret are pre-generated by the BO layer before this is passed to the repo.
type CreateOAuthApp struct {
	ID            string
	ClientID      string   // Pre-generated random 32-byte hex
	ClientSecret  string   // Plain text — hashed before storage, discarded after
	Name          string
	TenantID      string
	Description   string
	AllowedScopes []string
	Now           time.Time
}

// OAuthAppResponse is the safe, read-only API response shape.
// It contains NO secret hash and NO plain-text secret.
// Used for: List, Get responses.
type OAuthAppResponse struct {
	ID            string    `json:"id"`
	ClientID      string    `json:"clientId"`
	Name          string    `json:"name"`
	TenantID      string    `json:"tenantId"`
	Description   string    `json:"description"`
	AllowedScopes []string  `json:"allowedScopes"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
}

// OAuthAppCreatedResponse is used EXCLUSIVELY for:
//   - POST /oauth-apps         (Create)
//   - POST /oauth-apps/:id/rotate-secret (RotateSecret)
//
// It includes the ONE-TIME plain-text ClientSecret.
// After the HTTP response is sent, the secret MUST be discarded — it cannot be recovered.
type OAuthAppCreatedResponse struct {
	OAuthAppResponse
	ClientSecret string `json:"clientSecret"` // Returned ONCE. Never stored.
}
