package models

import (
	"time"
)

// UserSession represents a user's session in the system.
type UserSession struct {
	ID           string    `orm:"primary-key"` // Will be auto-generated by the repository if empty
	UserName     string    `orm:"unique"`
	CurrentToken string    // No specific ORM constraint tag, persisted as is.
	// TTL stores the absolute expiration timestamp (Unix seconds).
	// The repository's TTL mechanism will use this to calculate remaining duration.
	TTL       int64     `orm:"ttl"`
	CreatedAt time.Time // Informational
	UpdatedAt time.Time // Informational
}

// TableName specifies the custom table name for UserSession.
func (UserSession) TableName() string {
	return "user_sessions"
}
