// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/infrastructure/server/grpc/proto/definitions/exchange.proto

package exchange

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateExchangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantCode    string                 `protobuf:"bytes,1,opt,name=tenantCode,proto3" json:"tenantCode,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Vnamespace    string                 `protobuf:"bytes,5,opt,name=vnamespace,proto3" json:"vnamespace,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExchangeRequest) Reset() {
	*x = CreateExchangeRequest{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExchangeRequest) ProtoMessage() {}

func (x *CreateExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExchangeRequest.ProtoReflect.Descriptor instead.
func (*CreateExchangeRequest) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_rawDescGZIP(), []int{0}
}

func (x *CreateExchangeRequest) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

func (x *CreateExchangeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateExchangeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateExchangeRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateExchangeRequest) GetVnamespace() string {
	if x != nil {
		return x.Vnamespace
	}
	return ""
}

func (x *CreateExchangeRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type CreateExchangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Result        *Exchange              `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExchangeResponse) Reset() {
	*x = CreateExchangeResponse{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExchangeResponse) ProtoMessage() {}

func (x *CreateExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExchangeResponse.ProtoReflect.Descriptor instead.
func (*CreateExchangeResponse) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_rawDescGZIP(), []int{1}
}

func (x *CreateExchangeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateExchangeResponse) GetResult() *Exchange {
	if x != nil {
		return x.Result
	}
	return nil
}

type BulkCreateExchangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantCode    string                 `protobuf:"bytes,1,opt,name=tenantCode,proto3" json:"tenantCode,omitempty"`
	Exchanges     []*CreateExchangeItem  `protobuf:"bytes,2,rep,name=exchanges,proto3" json:"exchanges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkCreateExchangeRequest) Reset() {
	*x = BulkCreateExchangeRequest{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkCreateExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkCreateExchangeRequest) ProtoMessage() {}

func (x *BulkCreateExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkCreateExchangeRequest.ProtoReflect.Descriptor instead.
func (*BulkCreateExchangeRequest) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_rawDescGZIP(), []int{2}
}

func (x *BulkCreateExchangeRequest) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

func (x *BulkCreateExchangeRequest) GetExchanges() []*CreateExchangeItem {
	if x != nil {
		return x.Exchanges
	}
	return nil
}

type CreateExchangeItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Vnamespace    string                 `protobuf:"bytes,4,opt,name=vnamespace,proto3" json:"vnamespace,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExchangeItem) Reset() {
	*x = CreateExchangeItem{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExchangeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExchangeItem) ProtoMessage() {}

func (x *CreateExchangeItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExchangeItem.ProtoReflect.Descriptor instead.
func (*CreateExchangeItem) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_rawDescGZIP(), []int{3}
}

func (x *CreateExchangeItem) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateExchangeItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateExchangeItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateExchangeItem) GetVnamespace() string {
	if x != nil {
		return x.Vnamespace
	}
	return ""
}

func (x *CreateExchangeItem) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type BulkCreateExchangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Result        []*Exchange            `protobuf:"bytes,2,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkCreateExchangeResponse) Reset() {
	*x = BulkCreateExchangeResponse{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkCreateExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkCreateExchangeResponse) ProtoMessage() {}

func (x *BulkCreateExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkCreateExchangeResponse.ProtoReflect.Descriptor instead.
func (*BulkCreateExchangeResponse) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_rawDescGZIP(), []int{4}
}

func (x *BulkCreateExchangeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BulkCreateExchangeResponse) GetResult() []*Exchange {
	if x != nil {
		return x.Result
	}
	return nil
}

type GetExchangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantCode    string                 `protobuf:"bytes,1,opt,name=tenantCode,proto3" json:"tenantCode,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Vnamespace    string                 `protobuf:"bytes,3,opt,name=vnamespace,proto3" json:"vnamespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExchangeRequest) Reset() {
	*x = GetExchangeRequest{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExchangeRequest) ProtoMessage() {}

func (x *GetExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExchangeRequest.ProtoReflect.Descriptor instead.
func (*GetExchangeRequest) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_rawDescGZIP(), []int{5}
}

func (x *GetExchangeRequest) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

func (x *GetExchangeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetExchangeRequest) GetVnamespace() string {
	if x != nil {
		return x.Vnamespace
	}
	return ""
}

type GetExchangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Result        *Exchange              `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExchangeResponse) Reset() {
	*x = GetExchangeResponse{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExchangeResponse) ProtoMessage() {}

func (x *GetExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExchangeResponse.ProtoReflect.Descriptor instead.
func (*GetExchangeResponse) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_rawDescGZIP(), []int{6}
}

func (x *GetExchangeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetExchangeResponse) GetResult() *Exchange {
	if x != nil {
		return x.Result
	}
	return nil
}

type GetExchangesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantCode    string                 `protobuf:"bytes,1,opt,name=tenantCode,proto3" json:"tenantCode,omitempty"`
	Q             string                 `protobuf:"bytes,2,opt,name=q,proto3" json:"q,omitempty"`
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Vnamespace    string                 `protobuf:"bytes,5,opt,name=vnamespace,proto3" json:"vnamespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExchangesRequest) Reset() {
	*x = GetExchangesRequest{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExchangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExchangesRequest) ProtoMessage() {}

func (x *GetExchangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExchangesRequest.ProtoReflect.Descriptor instead.
func (*GetExchangesRequest) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_rawDescGZIP(), []int{7}
}

func (x *GetExchangesRequest) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

func (x *GetExchangesRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *GetExchangesRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *GetExchangesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetExchangesRequest) GetVnamespace() string {
	if x != nil {
		return x.Vnamespace
	}
	return ""
}

type Exchange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=Type,proto3" json:"Type,omitempty"`
	VNamespace    string                 `protobuf:"bytes,5,opt,name=VNamespace,proto3" json:"VNamespace,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,8,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exchange) Reset() {
	*x = Exchange{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exchange) ProtoMessage() {}

func (x *Exchange) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exchange.ProtoReflect.Descriptor instead.
func (*Exchange) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_rawDescGZIP(), []int{8}
}

func (x *Exchange) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Exchange) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Exchange) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Exchange) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Exchange) GetVNamespace() string {
	if x != nil {
		return x.VNamespace
	}
	return ""
}

func (x *Exchange) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Exchange) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Exchange) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type ExchangeFindResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*Exchange            `protobuf:"bytes,1,rep,name=Entities,proto3" json:"Entities,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=Cursor,proto3" json:"Cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeFindResult) Reset() {
	*x = ExchangeFindResult{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeFindResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeFindResult) ProtoMessage() {}

func (x *ExchangeFindResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeFindResult.ProtoReflect.Descriptor instead.
func (*ExchangeFindResult) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_rawDescGZIP(), []int{9}
}

func (x *ExchangeFindResult) GetEntities() []*Exchange {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *ExchangeFindResult) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type GetExchangesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Result        *ExchangeFindResult    `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExchangesResponse) Reset() {
	*x = GetExchangesResponse{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExchangesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExchangesResponse) ProtoMessage() {}

func (x *GetExchangesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExchangesResponse.ProtoReflect.Descriptor instead.
func (*GetExchangesResponse) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_rawDescGZIP(), []int{10}
}

func (x *GetExchangesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetExchangesResponse) GetResult() *ExchangeFindResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type DeleteExchangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantCode    string                 `protobuf:"bytes,1,opt,name=tenantCode,proto3" json:"tenantCode,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Vnamespace    string                 `protobuf:"bytes,3,opt,name=vnamespace,proto3" json:"vnamespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExchangeRequest) Reset() {
	*x = DeleteExchangeRequest{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExchangeRequest) ProtoMessage() {}

func (x *DeleteExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExchangeRequest.ProtoReflect.Descriptor instead.
func (*DeleteExchangeRequest) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteExchangeRequest) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

func (x *DeleteExchangeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DeleteExchangeRequest) GetVnamespace() string {
	if x != nil {
		return x.Vnamespace
	}
	return ""
}

type DeleteExchangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExchangeResponse) Reset() {
	*x = DeleteExchangeResponse{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExchangeResponse) ProtoMessage() {}

func (x *DeleteExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExchangeResponse.ProtoReflect.Descriptor instead.
func (*DeleteExchangeResponse) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteExchangeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PublishMessageRequest struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	TenantCode                     string                 `protobuf:"bytes,1,opt,name=tenantCode,proto3" json:"tenantCode,omitempty"`
	ExchangeCode                   string                 `protobuf:"bytes,2,opt,name=exchangeCode,proto3" json:"exchangeCode,omitempty"`
	RoutingKeyOrPatternOrQueueCode string                 `protobuf:"bytes,3,opt,name=routingKeyOrPatternOrQueueCode,proto3" json:"routingKeyOrPatternOrQueueCode,omitempty"`
	Vnamespace                     string                 `protobuf:"bytes,4,opt,name=vnamespace,proto3" json:"vnamespace,omitempty"`
	Message                        *QueueMessage          `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *PublishMessageRequest) Reset() {
	*x = PublishMessageRequest{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishMessageRequest) ProtoMessage() {}

func (x *PublishMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishMessageRequest.ProtoReflect.Descriptor instead.
func (*PublishMessageRequest) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_rawDescGZIP(), []int{13}
}

func (x *PublishMessageRequest) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

func (x *PublishMessageRequest) GetExchangeCode() string {
	if x != nil {
		return x.ExchangeCode
	}
	return ""
}

func (x *PublishMessageRequest) GetRoutingKeyOrPatternOrQueueCode() string {
	if x != nil {
		return x.RoutingKeyOrPatternOrQueueCode
	}
	return ""
}

func (x *PublishMessageRequest) GetVnamespace() string {
	if x != nil {
		return x.Vnamespace
	}
	return ""
}

func (x *PublishMessageRequest) GetMessage() *QueueMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type QueueMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=messageId,proto3" json:"messageId,omitempty"`
	Handler       string                 `protobuf:"bytes,2,opt,name=handler,proto3" json:"handler,omitempty"`
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Headers       map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ContentType   string                 `protobuf:"bytes,6,opt,name=contentType,proto3" json:"contentType,omitempty"`
	Content       []byte                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueMessage) Reset() {
	*x = QueueMessage{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueMessage) ProtoMessage() {}

func (x *QueueMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueMessage.ProtoReflect.Descriptor instead.
func (*QueueMessage) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_rawDescGZIP(), []int{14}
}

func (x *QueueMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *QueueMessage) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

func (x *QueueMessage) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *QueueMessage) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *QueueMessage) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *QueueMessage) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *QueueMessage) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type PublishMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	QueueMessages map[string]string      `protobuf:"bytes,2,rep,name=queueMessages,proto3" json:"queueMessages,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // queueCode -> messageID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishMessageResponse) Reset() {
	*x = PublishMessageResponse{}
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishMessageResponse) ProtoMessage() {}

func (x *PublishMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishMessageResponse.ProtoReflect.Descriptor instead.
func (*PublishMessageResponse) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_rawDescGZIP(), []int{15}
}

func (x *PublishMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PublishMessageResponse) GetQueueMessages() map[string]string {
	if x != nil {
		return x.QueueMessages
	}
	return nil
}

var File_internal_infrastructure_server_grpc_proto_definitions_exchange_proto protoreflect.FileDescriptor

const file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_rawDesc = "" +
	"\n" +
	"Dinternal/infrastructure/server/grpc/proto/definitions/exchange.proto\x12\bexchange\"\x97\x02\n" +
	"\x15CreateExchangeRequest\x12\x1e\n" +
	"\n" +
	"tenantCode\x18\x01 \x01(\tR\n" +
	"tenantCode\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"vnamespace\x18\x05 \x01(\tR\n" +
	"vnamespace\x12F\n" +
	"\aheaders\x18\x06 \x03(\v2,.exchange.CreateExchangeRequest.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"^\n" +
	"\x16CreateExchangeResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12*\n" +
	"\x06result\x18\x02 \x01(\v2\x12.exchange.ExchangeR\x06result\"w\n" +
	"\x19BulkCreateExchangeRequest\x12\x1e\n" +
	"\n" +
	"tenantCode\x18\x01 \x01(\tR\n" +
	"tenantCode\x12:\n" +
	"\texchanges\x18\x02 \x03(\v2\x1c.exchange.CreateExchangeItemR\texchanges\"\xf1\x01\n" +
	"\x12CreateExchangeItem\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"vnamespace\x18\x04 \x01(\tR\n" +
	"vnamespace\x12C\n" +
	"\aheaders\x18\x05 \x03(\v2).exchange.CreateExchangeItem.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"b\n" +
	"\x1aBulkCreateExchangeResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12*\n" +
	"\x06result\x18\x02 \x03(\v2\x12.exchange.ExchangeR\x06result\"h\n" +
	"\x12GetExchangeRequest\x12\x1e\n" +
	"\n" +
	"tenantCode\x18\x01 \x01(\tR\n" +
	"tenantCode\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1e\n" +
	"\n" +
	"vnamespace\x18\x03 \x01(\tR\n" +
	"vnamespace\"[\n" +
	"\x13GetExchangeResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12*\n" +
	"\x06result\x18\x02 \x01(\v2\x12.exchange.ExchangeR\x06result\"\x97\x01\n" +
	"\x13GetExchangesRequest\x12\x1e\n" +
	"\n" +
	"tenantCode\x18\x01 \x01(\tR\n" +
	"tenantCode\x12\f\n" +
	"\x01q\x18\x02 \x01(\tR\x01q\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x05R\bpageSize\x12\x1e\n" +
	"\n" +
	"vnamespace\x18\x05 \x01(\tR\n" +
	"vnamespace\"\xa9\x02\n" +
	"\bExchange\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04Code\x18\x02 \x01(\tR\x04Code\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12\x12\n" +
	"\x04Type\x18\x04 \x01(\tR\x04Type\x12\x1e\n" +
	"\n" +
	"VNamespace\x18\x05 \x01(\tR\n" +
	"VNamespace\x12\x1c\n" +
	"\tCreatedAt\x18\x06 \x01(\tR\tCreatedAt\x12\x1c\n" +
	"\tUpdatedAt\x18\a \x01(\tR\tUpdatedAt\x129\n" +
	"\aheaders\x18\b \x03(\v2\x1f.exchange.Exchange.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\\\n" +
	"\x12ExchangeFindResult\x12.\n" +
	"\bEntities\x18\x01 \x03(\v2\x12.exchange.ExchangeR\bEntities\x12\x16\n" +
	"\x06Cursor\x18\x02 \x01(\tR\x06Cursor\"f\n" +
	"\x14GetExchangesResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x124\n" +
	"\x06result\x18\x02 \x01(\v2\x1c.exchange.ExchangeFindResultR\x06result\"k\n" +
	"\x15DeleteExchangeRequest\x12\x1e\n" +
	"\n" +
	"tenantCode\x18\x01 \x01(\tR\n" +
	"tenantCode\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1e\n" +
	"\n" +
	"vnamespace\x18\x03 \x01(\tR\n" +
	"vnamespace\"2\n" +
	"\x16DeleteExchangeResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xf5\x01\n" +
	"\x15PublishMessageRequest\x12\x1e\n" +
	"\n" +
	"tenantCode\x18\x01 \x01(\tR\n" +
	"tenantCode\x12\"\n" +
	"\fexchangeCode\x18\x02 \x01(\tR\fexchangeCode\x12F\n" +
	"\x1eroutingKeyOrPatternOrQueueCode\x18\x03 \x01(\tR\x1eroutingKeyOrPatternOrQueueCode\x12\x1e\n" +
	"\n" +
	"vnamespace\x18\x04 \x01(\tR\n" +
	"vnamespace\x120\n" +
	"\amessage\x18\x05 \x01(\v2\x16.exchange.QueueMessageR\amessage\"\xa0\x03\n" +
	"\fQueueMessage\x12\x1c\n" +
	"\tmessageId\x18\x01 \x01(\tR\tmessageId\x12\x18\n" +
	"\ahandler\x18\x02 \x01(\tR\ahandler\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12F\n" +
	"\n" +
	"parameters\x18\x04 \x03(\v2&.exchange.QueueMessage.ParametersEntryR\n" +
	"parameters\x12=\n" +
	"\aheaders\x18\x05 \x03(\v2#.exchange.QueueMessage.HeadersEntryR\aheaders\x12 \n" +
	"\vcontentType\x18\x06 \x01(\tR\vcontentType\x12\x18\n" +
	"\acontent\x18\a \x01(\fR\acontent\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcf\x01\n" +
	"\x16PublishMessageResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12Y\n" +
	"\rqueueMessages\x18\x02 \x03(\v23.exchange.PublishMessageResponse.QueueMessagesEntryR\rqueueMessages\x1a@\n" +
	"\x12QueueMessagesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x8c\x04\n" +
	"\x0fExchangeService\x12S\n" +
	"\x0eCreateExchange\x12\x1f.exchange.CreateExchangeRequest\x1a .exchange.CreateExchangeResponse\x12_\n" +
	"\x12BulkCreateExchange\x12#.exchange.BulkCreateExchangeRequest\x1a$.exchange.BulkCreateExchangeResponse\x12J\n" +
	"\vGetExchange\x12\x1c.exchange.GetExchangeRequest\x1a\x1d.exchange.GetExchangeResponse\x12M\n" +
	"\fGetExchanges\x12\x1d.exchange.GetExchangesRequest\x1a\x1e.exchange.GetExchangesResponse\x12S\n" +
	"\x0eDeleteExchange\x12\x1f.exchange.DeleteExchangeRequest\x1a .exchange.DeleteExchangeResponse\x12S\n" +
	"\x0ePublishMessage\x12\x1f.exchange.PublishMessageRequest\x1a .exchange.PublishMessageResponseB\x16Z\x14pb/exchange;exchangeb\x06proto3"

var (
	file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_rawDescOnce sync.Once
	file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_rawDescData []byte
)

func file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_rawDescGZIP() []byte {
	file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_rawDescOnce.Do(func() {
		file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_rawDesc), len(file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_rawDesc)))
	})
	return file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_rawDescData
}

var file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_goTypes = []any{
	(*CreateExchangeRequest)(nil),      // 0: exchange.CreateExchangeRequest
	(*CreateExchangeResponse)(nil),     // 1: exchange.CreateExchangeResponse
	(*BulkCreateExchangeRequest)(nil),  // 2: exchange.BulkCreateExchangeRequest
	(*CreateExchangeItem)(nil),         // 3: exchange.CreateExchangeItem
	(*BulkCreateExchangeResponse)(nil), // 4: exchange.BulkCreateExchangeResponse
	(*GetExchangeRequest)(nil),         // 5: exchange.GetExchangeRequest
	(*GetExchangeResponse)(nil),        // 6: exchange.GetExchangeResponse
	(*GetExchangesRequest)(nil),        // 7: exchange.GetExchangesRequest
	(*Exchange)(nil),                   // 8: exchange.Exchange
	(*ExchangeFindResult)(nil),         // 9: exchange.ExchangeFindResult
	(*GetExchangesResponse)(nil),       // 10: exchange.GetExchangesResponse
	(*DeleteExchangeRequest)(nil),      // 11: exchange.DeleteExchangeRequest
	(*DeleteExchangeResponse)(nil),     // 12: exchange.DeleteExchangeResponse
	(*PublishMessageRequest)(nil),      // 13: exchange.PublishMessageRequest
	(*QueueMessage)(nil),               // 14: exchange.QueueMessage
	(*PublishMessageResponse)(nil),     // 15: exchange.PublishMessageResponse
	nil,                                // 16: exchange.CreateExchangeRequest.HeadersEntry
	nil,                                // 17: exchange.CreateExchangeItem.HeadersEntry
	nil,                                // 18: exchange.Exchange.HeadersEntry
	nil,                                // 19: exchange.QueueMessage.ParametersEntry
	nil,                                // 20: exchange.QueueMessage.HeadersEntry
	nil,                                // 21: exchange.PublishMessageResponse.QueueMessagesEntry
}
var file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_depIdxs = []int32{
	16, // 0: exchange.CreateExchangeRequest.headers:type_name -> exchange.CreateExchangeRequest.HeadersEntry
	8,  // 1: exchange.CreateExchangeResponse.result:type_name -> exchange.Exchange
	3,  // 2: exchange.BulkCreateExchangeRequest.exchanges:type_name -> exchange.CreateExchangeItem
	17, // 3: exchange.CreateExchangeItem.headers:type_name -> exchange.CreateExchangeItem.HeadersEntry
	8,  // 4: exchange.BulkCreateExchangeResponse.result:type_name -> exchange.Exchange
	8,  // 5: exchange.GetExchangeResponse.result:type_name -> exchange.Exchange
	18, // 6: exchange.Exchange.headers:type_name -> exchange.Exchange.HeadersEntry
	8,  // 7: exchange.ExchangeFindResult.Entities:type_name -> exchange.Exchange
	9,  // 8: exchange.GetExchangesResponse.result:type_name -> exchange.ExchangeFindResult
	14, // 9: exchange.PublishMessageRequest.message:type_name -> exchange.QueueMessage
	19, // 10: exchange.QueueMessage.parameters:type_name -> exchange.QueueMessage.ParametersEntry
	20, // 11: exchange.QueueMessage.headers:type_name -> exchange.QueueMessage.HeadersEntry
	21, // 12: exchange.PublishMessageResponse.queueMessages:type_name -> exchange.PublishMessageResponse.QueueMessagesEntry
	0,  // 13: exchange.ExchangeService.CreateExchange:input_type -> exchange.CreateExchangeRequest
	2,  // 14: exchange.ExchangeService.BulkCreateExchange:input_type -> exchange.BulkCreateExchangeRequest
	5,  // 15: exchange.ExchangeService.GetExchange:input_type -> exchange.GetExchangeRequest
	7,  // 16: exchange.ExchangeService.GetExchanges:input_type -> exchange.GetExchangesRequest
	11, // 17: exchange.ExchangeService.DeleteExchange:input_type -> exchange.DeleteExchangeRequest
	13, // 18: exchange.ExchangeService.PublishMessage:input_type -> exchange.PublishMessageRequest
	1,  // 19: exchange.ExchangeService.CreateExchange:output_type -> exchange.CreateExchangeResponse
	4,  // 20: exchange.ExchangeService.BulkCreateExchange:output_type -> exchange.BulkCreateExchangeResponse
	6,  // 21: exchange.ExchangeService.GetExchange:output_type -> exchange.GetExchangeResponse
	10, // 22: exchange.ExchangeService.GetExchanges:output_type -> exchange.GetExchangesResponse
	12, // 23: exchange.ExchangeService.DeleteExchange:output_type -> exchange.DeleteExchangeResponse
	15, // 24: exchange.ExchangeService.PublishMessage:output_type -> exchange.PublishMessageResponse
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_init() }
func file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_init() {
	if File_internal_infrastructure_server_grpc_proto_definitions_exchange_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_rawDesc), len(file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_goTypes,
		DependencyIndexes: file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_depIdxs,
		MessageInfos:      file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_msgTypes,
	}.Build()
	File_internal_infrastructure_server_grpc_proto_definitions_exchange_proto = out.File
	file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_goTypes = nil
	file_internal_infrastructure_server_grpc_proto_definitions_exchange_proto_depIdxs = nil
}
