// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.4
// source: server/internal/infrastructure/server/grpc/proto/definitions/workflow_definition.proto

package workflowdefinition

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkflowDefinitionService_CreateWorkflowDefinition_FullMethodName = "/workflowdefinition.WorkflowDefinitionService/CreateWorkflowDefinition"
	WorkflowDefinitionService_UpdateWorkflowDefinition_FullMethodName = "/workflowdefinition.WorkflowDefinitionService/UpdateWorkflowDefinition"
	WorkflowDefinitionService_GetWorkflowDefinition_FullMethodName    = "/workflowdefinition.WorkflowDefinitionService/GetWorkflowDefinition"
	WorkflowDefinitionService_ListWorkflowDefinitions_FullMethodName  = "/workflowdefinition.WorkflowDefinitionService/ListWorkflowDefinitions"
	WorkflowDefinitionService_DeleteWorkflowDefinition_FullMethodName = "/workflowdefinition.WorkflowDefinitionService/DeleteWorkflowDefinition"
)

// WorkflowDefinitionServiceClient is the client API for WorkflowDefinitionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkflowDefinitionServiceClient interface {
	CreateWorkflowDefinition(ctx context.Context, in *CreateWorkflowDefinitionRequest, opts ...grpc.CallOption) (*CreateWorkflowDefinitionResponse, error)
	UpdateWorkflowDefinition(ctx context.Context, in *UpdateWorkflowDefinitionRequest, opts ...grpc.CallOption) (*UpdateWorkflowDefinitionResponse, error)
	GetWorkflowDefinition(ctx context.Context, in *GetWorkflowDefinitionRequest, opts ...grpc.CallOption) (*GetWorkflowDefinitionResponse, error)
	ListWorkflowDefinitions(ctx context.Context, in *ListWorkflowDefinitionsRequest, opts ...grpc.CallOption) (*ListWorkflowDefinitionsResponse, error)
	DeleteWorkflowDefinition(ctx context.Context, in *DeleteWorkflowDefinitionRequest, opts ...grpc.CallOption) (*DeleteWorkflowDefinitionResponse, error)
}

type workflowDefinitionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkflowDefinitionServiceClient(cc grpc.ClientConnInterface) WorkflowDefinitionServiceClient {
	return &workflowDefinitionServiceClient{cc}
}

func (c *workflowDefinitionServiceClient) CreateWorkflowDefinition(ctx context.Context, in *CreateWorkflowDefinitionRequest, opts ...grpc.CallOption) (*CreateWorkflowDefinitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWorkflowDefinitionResponse)
	err := c.cc.Invoke(ctx, WorkflowDefinitionService_CreateWorkflowDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowDefinitionServiceClient) UpdateWorkflowDefinition(ctx context.Context, in *UpdateWorkflowDefinitionRequest, opts ...grpc.CallOption) (*UpdateWorkflowDefinitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateWorkflowDefinitionResponse)
	err := c.cc.Invoke(ctx, WorkflowDefinitionService_UpdateWorkflowDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowDefinitionServiceClient) GetWorkflowDefinition(ctx context.Context, in *GetWorkflowDefinitionRequest, opts ...grpc.CallOption) (*GetWorkflowDefinitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkflowDefinitionResponse)
	err := c.cc.Invoke(ctx, WorkflowDefinitionService_GetWorkflowDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowDefinitionServiceClient) ListWorkflowDefinitions(ctx context.Context, in *ListWorkflowDefinitionsRequest, opts ...grpc.CallOption) (*ListWorkflowDefinitionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkflowDefinitionsResponse)
	err := c.cc.Invoke(ctx, WorkflowDefinitionService_ListWorkflowDefinitions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowDefinitionServiceClient) DeleteWorkflowDefinition(ctx context.Context, in *DeleteWorkflowDefinitionRequest, opts ...grpc.CallOption) (*DeleteWorkflowDefinitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteWorkflowDefinitionResponse)
	err := c.cc.Invoke(ctx, WorkflowDefinitionService_DeleteWorkflowDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkflowDefinitionServiceServer is the server API for WorkflowDefinitionService service.
// All implementations must embed UnimplementedWorkflowDefinitionServiceServer
// for forward compatibility.
type WorkflowDefinitionServiceServer interface {
	CreateWorkflowDefinition(context.Context, *CreateWorkflowDefinitionRequest) (*CreateWorkflowDefinitionResponse, error)
	UpdateWorkflowDefinition(context.Context, *UpdateWorkflowDefinitionRequest) (*UpdateWorkflowDefinitionResponse, error)
	GetWorkflowDefinition(context.Context, *GetWorkflowDefinitionRequest) (*GetWorkflowDefinitionResponse, error)
	ListWorkflowDefinitions(context.Context, *ListWorkflowDefinitionsRequest) (*ListWorkflowDefinitionsResponse, error)
	DeleteWorkflowDefinition(context.Context, *DeleteWorkflowDefinitionRequest) (*DeleteWorkflowDefinitionResponse, error)
	mustEmbedUnimplementedWorkflowDefinitionServiceServer()
}

// UnimplementedWorkflowDefinitionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkflowDefinitionServiceServer struct{}

func (UnimplementedWorkflowDefinitionServiceServer) CreateWorkflowDefinition(context.Context, *CreateWorkflowDefinitionRequest) (*CreateWorkflowDefinitionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWorkflowDefinition not implemented")
}
func (UnimplementedWorkflowDefinitionServiceServer) UpdateWorkflowDefinition(context.Context, *UpdateWorkflowDefinitionRequest) (*UpdateWorkflowDefinitionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateWorkflowDefinition not implemented")
}
func (UnimplementedWorkflowDefinitionServiceServer) GetWorkflowDefinition(context.Context, *GetWorkflowDefinitionRequest) (*GetWorkflowDefinitionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkflowDefinition not implemented")
}
func (UnimplementedWorkflowDefinitionServiceServer) ListWorkflowDefinitions(context.Context, *ListWorkflowDefinitionsRequest) (*ListWorkflowDefinitionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkflowDefinitions not implemented")
}
func (UnimplementedWorkflowDefinitionServiceServer) DeleteWorkflowDefinition(context.Context, *DeleteWorkflowDefinitionRequest) (*DeleteWorkflowDefinitionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteWorkflowDefinition not implemented")
}
func (UnimplementedWorkflowDefinitionServiceServer) mustEmbedUnimplementedWorkflowDefinitionServiceServer() {
}
func (UnimplementedWorkflowDefinitionServiceServer) testEmbeddedByValue() {}

// UnsafeWorkflowDefinitionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkflowDefinitionServiceServer will
// result in compilation errors.
type UnsafeWorkflowDefinitionServiceServer interface {
	mustEmbedUnimplementedWorkflowDefinitionServiceServer()
}

func RegisterWorkflowDefinitionServiceServer(s grpc.ServiceRegistrar, srv WorkflowDefinitionServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkflowDefinitionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkflowDefinitionService_ServiceDesc, srv)
}

func _WorkflowDefinitionService_CreateWorkflowDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWorkflowDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowDefinitionServiceServer).CreateWorkflowDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowDefinitionService_CreateWorkflowDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowDefinitionServiceServer).CreateWorkflowDefinition(ctx, req.(*CreateWorkflowDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowDefinitionService_UpdateWorkflowDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWorkflowDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowDefinitionServiceServer).UpdateWorkflowDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowDefinitionService_UpdateWorkflowDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowDefinitionServiceServer).UpdateWorkflowDefinition(ctx, req.(*UpdateWorkflowDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowDefinitionService_GetWorkflowDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkflowDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowDefinitionServiceServer).GetWorkflowDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowDefinitionService_GetWorkflowDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowDefinitionServiceServer).GetWorkflowDefinition(ctx, req.(*GetWorkflowDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowDefinitionService_ListWorkflowDefinitions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkflowDefinitionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowDefinitionServiceServer).ListWorkflowDefinitions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowDefinitionService_ListWorkflowDefinitions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowDefinitionServiceServer).ListWorkflowDefinitions(ctx, req.(*ListWorkflowDefinitionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowDefinitionService_DeleteWorkflowDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWorkflowDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowDefinitionServiceServer).DeleteWorkflowDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowDefinitionService_DeleteWorkflowDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowDefinitionServiceServer).DeleteWorkflowDefinition(ctx, req.(*DeleteWorkflowDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkflowDefinitionService_ServiceDesc is the grpc.ServiceDesc for WorkflowDefinitionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkflowDefinitionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "workflowdefinition.WorkflowDefinitionService",
	HandlerType: (*WorkflowDefinitionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWorkflowDefinition",
			Handler:    _WorkflowDefinitionService_CreateWorkflowDefinition_Handler,
		},
		{
			MethodName: "UpdateWorkflowDefinition",
			Handler:    _WorkflowDefinitionService_UpdateWorkflowDefinition_Handler,
		},
		{
			MethodName: "GetWorkflowDefinition",
			Handler:    _WorkflowDefinitionService_GetWorkflowDefinition_Handler,
		},
		{
			MethodName: "ListWorkflowDefinitions",
			Handler:    _WorkflowDefinitionService_ListWorkflowDefinitions_Handler,
		},
		{
			MethodName: "DeleteWorkflowDefinition",
			Handler:    _WorkflowDefinitionService_DeleteWorkflowDefinition_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/internal/infrastructure/server/grpc/proto/definitions/workflow_definition.proto",
}
