// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: server/internal/infrastructure/server/grpc/proto/definitions/workflow_definition.proto

package workflowdefinition

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkflowDefinitionProto struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code               string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Vnamespace         string                 `protobuf:"bytes,3,opt,name=vnamespace,proto3" json:"vnamespace,omitempty"`
	Name               string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description        string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Version            int32                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	Payload            []byte                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	PayloadFormat      string                 `protobuf:"bytes,8,opt,name=payloadFormat,proto3" json:"payloadFormat,omitempty"`
	MaxDurationSeconds int32                  `protobuf:"varint,9,opt,name=maxDurationSeconds,proto3" json:"maxDurationSeconds,omitempty"`
	IsActive           bool                   `protobuf:"varint,10,opt,name=isActive,proto3" json:"isActive,omitempty"`
	Scope              string                 `protobuf:"bytes,11,opt,name=scope,proto3" json:"scope,omitempty"`
	TenantId           string                 `protobuf:"bytes,12,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,13,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt          string                 `protobuf:"bytes,14,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WorkflowDefinitionProto) Reset() {
	*x = WorkflowDefinitionProto{}
	mi := &file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowDefinitionProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowDefinitionProto) ProtoMessage() {}

func (x *WorkflowDefinitionProto) ProtoReflect() protoreflect.Message {
	mi := &file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowDefinitionProto.ProtoReflect.Descriptor instead.
func (*WorkflowDefinitionProto) Descriptor() ([]byte, []int) {
	return file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_rawDescGZIP(), []int{0}
}

func (x *WorkflowDefinitionProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkflowDefinitionProto) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *WorkflowDefinitionProto) GetVnamespace() string {
	if x != nil {
		return x.Vnamespace
	}
	return ""
}

func (x *WorkflowDefinitionProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkflowDefinitionProto) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WorkflowDefinitionProto) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *WorkflowDefinitionProto) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WorkflowDefinitionProto) GetPayloadFormat() string {
	if x != nil {
		return x.PayloadFormat
	}
	return ""
}

func (x *WorkflowDefinitionProto) GetMaxDurationSeconds() int32 {
	if x != nil {
		return x.MaxDurationSeconds
	}
	return 0
}

func (x *WorkflowDefinitionProto) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *WorkflowDefinitionProto) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *WorkflowDefinitionProto) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *WorkflowDefinitionProto) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *WorkflowDefinitionProto) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateWorkflowDefinitionRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Code               string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description        string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Version            int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	Payload            []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	PayloadFormat      string                 `protobuf:"bytes,6,opt,name=payloadFormat,proto3" json:"payloadFormat,omitempty"`
	MaxDurationSeconds int32                  `protobuf:"varint,7,opt,name=maxDurationSeconds,proto3" json:"maxDurationSeconds,omitempty"`
	IsActive           bool                   `protobuf:"varint,8,opt,name=isActive,proto3" json:"isActive,omitempty"`
	Scope              string                 `protobuf:"bytes,9,opt,name=scope,proto3" json:"scope,omitempty"`
	TenantCode         string                 `protobuf:"bytes,10,opt,name=tenantCode,proto3" json:"tenantCode,omitempty"`
	Vnamespace         string                 `protobuf:"bytes,11,opt,name=vnamespace,proto3" json:"vnamespace,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateWorkflowDefinitionRequest) Reset() {
	*x = CreateWorkflowDefinitionRequest{}
	mi := &file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkflowDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkflowDefinitionRequest) ProtoMessage() {}

func (x *CreateWorkflowDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkflowDefinitionRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkflowDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWorkflowDefinitionRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateWorkflowDefinitionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWorkflowDefinitionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateWorkflowDefinitionRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CreateWorkflowDefinitionRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CreateWorkflowDefinitionRequest) GetPayloadFormat() string {
	if x != nil {
		return x.PayloadFormat
	}
	return ""
}

func (x *CreateWorkflowDefinitionRequest) GetMaxDurationSeconds() int32 {
	if x != nil {
		return x.MaxDurationSeconds
	}
	return 0
}

func (x *CreateWorkflowDefinitionRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CreateWorkflowDefinitionRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *CreateWorkflowDefinitionRequest) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

func (x *CreateWorkflowDefinitionRequest) GetVnamespace() string {
	if x != nil {
		return x.Vnamespace
	}
	return ""
}

type CreateWorkflowDefinitionResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Message       string                   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Result        *WorkflowDefinitionProto `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkflowDefinitionResponse) Reset() {
	*x = CreateWorkflowDefinitionResponse{}
	mi := &file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkflowDefinitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkflowDefinitionResponse) ProtoMessage() {}

func (x *CreateWorkflowDefinitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkflowDefinitionResponse.ProtoReflect.Descriptor instead.
func (*CreateWorkflowDefinitionResponse) Descriptor() ([]byte, []int) {
	return file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_rawDescGZIP(), []int{2}
}

func (x *CreateWorkflowDefinitionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateWorkflowDefinitionResponse) GetResult() *WorkflowDefinitionProto {
	if x != nil {
		return x.Result
	}
	return nil
}

type UpdateWorkflowDefinitionRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description        string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Version            int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	Payload            []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	PayloadFormat      string                 `protobuf:"bytes,6,opt,name=payloadFormat,proto3" json:"payloadFormat,omitempty"`
	MaxDurationSeconds int32                  `protobuf:"varint,7,opt,name=maxDurationSeconds,proto3" json:"maxDurationSeconds,omitempty"`
	IsActive           bool                   `protobuf:"varint,8,opt,name=isActive,proto3" json:"isActive,omitempty"`
	Scope              string                 `protobuf:"bytes,9,opt,name=scope,proto3" json:"scope,omitempty"`
	TenantCode         string                 `protobuf:"bytes,10,opt,name=tenantCode,proto3" json:"tenantCode,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateWorkflowDefinitionRequest) Reset() {
	*x = UpdateWorkflowDefinitionRequest{}
	mi := &file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkflowDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkflowDefinitionRequest) ProtoMessage() {}

func (x *UpdateWorkflowDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkflowDefinitionRequest.ProtoReflect.Descriptor instead.
func (*UpdateWorkflowDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateWorkflowDefinitionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateWorkflowDefinitionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateWorkflowDefinitionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateWorkflowDefinitionRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *UpdateWorkflowDefinitionRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UpdateWorkflowDefinitionRequest) GetPayloadFormat() string {
	if x != nil {
		return x.PayloadFormat
	}
	return ""
}

func (x *UpdateWorkflowDefinitionRequest) GetMaxDurationSeconds() int32 {
	if x != nil {
		return x.MaxDurationSeconds
	}
	return 0
}

func (x *UpdateWorkflowDefinitionRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *UpdateWorkflowDefinitionRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *UpdateWorkflowDefinitionRequest) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

type UpdateWorkflowDefinitionResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Message       string                   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Result        *WorkflowDefinitionProto `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkflowDefinitionResponse) Reset() {
	*x = UpdateWorkflowDefinitionResponse{}
	mi := &file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkflowDefinitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkflowDefinitionResponse) ProtoMessage() {}

func (x *UpdateWorkflowDefinitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkflowDefinitionResponse.ProtoReflect.Descriptor instead.
func (*UpdateWorkflowDefinitionResponse) Descriptor() ([]byte, []int) {
	return file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateWorkflowDefinitionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateWorkflowDefinitionResponse) GetResult() *WorkflowDefinitionProto {
	if x != nil {
		return x.Result
	}
	return nil
}

type GetWorkflowDefinitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Scope         string                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	TenantCode    string                 `protobuf:"bytes,4,opt,name=tenantCode,proto3" json:"tenantCode,omitempty"`
	Vnamespace    string                 `protobuf:"bytes,5,opt,name=vnamespace,proto3" json:"vnamespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowDefinitionRequest) Reset() {
	*x = GetWorkflowDefinitionRequest{}
	mi := &file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowDefinitionRequest) ProtoMessage() {}

func (x *GetWorkflowDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowDefinitionRequest.ProtoReflect.Descriptor instead.
func (*GetWorkflowDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_rawDescGZIP(), []int{5}
}

func (x *GetWorkflowDefinitionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetWorkflowDefinitionRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetWorkflowDefinitionRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *GetWorkflowDefinitionRequest) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

func (x *GetWorkflowDefinitionRequest) GetVnamespace() string {
	if x != nil {
		return x.Vnamespace
	}
	return ""
}

type GetWorkflowDefinitionResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Message       string                   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Result        *WorkflowDefinitionProto `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowDefinitionResponse) Reset() {
	*x = GetWorkflowDefinitionResponse{}
	mi := &file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowDefinitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowDefinitionResponse) ProtoMessage() {}

func (x *GetWorkflowDefinitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowDefinitionResponse.ProtoReflect.Descriptor instead.
func (*GetWorkflowDefinitionResponse) Descriptor() ([]byte, []int) {
	return file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_rawDescGZIP(), []int{6}
}

func (x *GetWorkflowDefinitionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetWorkflowDefinitionResponse) GetResult() *WorkflowDefinitionProto {
	if x != nil {
		return x.Result
	}
	return nil
}

type ListWorkflowDefinitionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	TenantCode    string                 `protobuf:"bytes,2,opt,name=tenantCode,proto3" json:"tenantCode,omitempty"`
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowDefinitionsRequest) Reset() {
	*x = ListWorkflowDefinitionsRequest{}
	mi := &file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowDefinitionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowDefinitionsRequest) ProtoMessage() {}

func (x *ListWorkflowDefinitionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowDefinitionsRequest.ProtoReflect.Descriptor instead.
func (*ListWorkflowDefinitionsRequest) Descriptor() ([]byte, []int) {
	return file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_rawDescGZIP(), []int{7}
}

func (x *ListWorkflowDefinitionsRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *ListWorkflowDefinitionsRequest) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

func (x *ListWorkflowDefinitionsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListWorkflowDefinitionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type WorkflowDefinitionFindResult struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Entities      []*WorkflowDefinitionProto `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	Cursor        string                     `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowDefinitionFindResult) Reset() {
	*x = WorkflowDefinitionFindResult{}
	mi := &file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowDefinitionFindResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowDefinitionFindResult) ProtoMessage() {}

func (x *WorkflowDefinitionFindResult) ProtoReflect() protoreflect.Message {
	mi := &file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowDefinitionFindResult.ProtoReflect.Descriptor instead.
func (*WorkflowDefinitionFindResult) Descriptor() ([]byte, []int) {
	return file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_rawDescGZIP(), []int{8}
}

func (x *WorkflowDefinitionFindResult) GetEntities() []*WorkflowDefinitionProto {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *WorkflowDefinitionFindResult) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type ListWorkflowDefinitionsResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Message       string                        `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Result        *WorkflowDefinitionFindResult `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowDefinitionsResponse) Reset() {
	*x = ListWorkflowDefinitionsResponse{}
	mi := &file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowDefinitionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowDefinitionsResponse) ProtoMessage() {}

func (x *ListWorkflowDefinitionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowDefinitionsResponse.ProtoReflect.Descriptor instead.
func (*ListWorkflowDefinitionsResponse) Descriptor() ([]byte, []int) {
	return file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_rawDescGZIP(), []int{9}
}

func (x *ListWorkflowDefinitionsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListWorkflowDefinitionsResponse) GetResult() *WorkflowDefinitionFindResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type DeleteWorkflowDefinitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Scope         string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	TenantCode    string                 `protobuf:"bytes,3,opt,name=tenantCode,proto3" json:"tenantCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkflowDefinitionRequest) Reset() {
	*x = DeleteWorkflowDefinitionRequest{}
	mi := &file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkflowDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkflowDefinitionRequest) ProtoMessage() {}

func (x *DeleteWorkflowDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkflowDefinitionRequest.ProtoReflect.Descriptor instead.
func (*DeleteWorkflowDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteWorkflowDefinitionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteWorkflowDefinitionRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *DeleteWorkflowDefinitionRequest) GetTenantCode() string {
	if x != nil {
		return x.TenantCode
	}
	return ""
}

type DeleteWorkflowDefinitionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkflowDefinitionResponse) Reset() {
	*x = DeleteWorkflowDefinitionResponse{}
	mi := &file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkflowDefinitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkflowDefinitionResponse) ProtoMessage() {}

func (x *DeleteWorkflowDefinitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkflowDefinitionResponse.ProtoReflect.Descriptor instead.
func (*DeleteWorkflowDefinitionResponse) Descriptor() ([]byte, []int) {
	return file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteWorkflowDefinitionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto protoreflect.FileDescriptor

const file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_rawDesc = "" +
	"\n" +
	"Vserver/internal/infrastructure/server/grpc/proto/definitions/workflow_definition.proto\x12\x12workflowdefinition\"\xa7\x03\n" +
	"\x17WorkflowDefinitionProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1e\n" +
	"\n" +
	"vnamespace\x18\x03 \x01(\tR\n" +
	"vnamespace\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x05R\aversion\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\x12$\n" +
	"\rpayloadFormat\x18\b \x01(\tR\rpayloadFormat\x12.\n" +
	"\x12maxDurationSeconds\x18\t \x01(\x05R\x12maxDurationSeconds\x12\x1a\n" +
	"\bisActive\x18\n" +
	" \x01(\bR\bisActive\x12\x14\n" +
	"\x05scope\x18\v \x01(\tR\x05scope\x12\x1a\n" +
	"\btenantId\x18\f \x01(\tR\btenantId\x12\x1c\n" +
	"\tcreatedAt\x18\r \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x0e \x01(\tR\tupdatedAt\"\xe7\x02\n" +
	"\x1fCreateWorkflowDefinitionRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12$\n" +
	"\rpayloadFormat\x18\x06 \x01(\tR\rpayloadFormat\x12.\n" +
	"\x12maxDurationSeconds\x18\a \x01(\x05R\x12maxDurationSeconds\x12\x1a\n" +
	"\bisActive\x18\b \x01(\bR\bisActive\x12\x14\n" +
	"\x05scope\x18\t \x01(\tR\x05scope\x12\x1e\n" +
	"\n" +
	"tenantCode\x18\n" +
	" \x01(\tR\n" +
	"tenantCode\x12\x1e\n" +
	"\n" +
	"vnamespace\x18\v \x01(\tR\n" +
	"vnamespace\"\x81\x01\n" +
	" CreateWorkflowDefinitionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12C\n" +
	"\x06result\x18\x02 \x01(\v2+.workflowdefinition.WorkflowDefinitionProtoR\x06result\"\xc3\x02\n" +
	"\x1fUpdateWorkflowDefinitionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12$\n" +
	"\rpayloadFormat\x18\x06 \x01(\tR\rpayloadFormat\x12.\n" +
	"\x12maxDurationSeconds\x18\a \x01(\x05R\x12maxDurationSeconds\x12\x1a\n" +
	"\bisActive\x18\b \x01(\bR\bisActive\x12\x14\n" +
	"\x05scope\x18\t \x01(\tR\x05scope\x12\x1e\n" +
	"\n" +
	"tenantCode\x18\n" +
	" \x01(\tR\n" +
	"tenantCode\"\x81\x01\n" +
	" UpdateWorkflowDefinitionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12C\n" +
	"\x06result\x18\x02 \x01(\v2+.workflowdefinition.WorkflowDefinitionProtoR\x06result\"\x98\x01\n" +
	"\x1cGetWorkflowDefinitionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\x12\x1e\n" +
	"\n" +
	"tenantCode\x18\x04 \x01(\tR\n" +
	"tenantCode\x12\x1e\n" +
	"\n" +
	"vnamespace\x18\x05 \x01(\tR\n" +
	"vnamespace\"~\n" +
	"\x1dGetWorkflowDefinitionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12C\n" +
	"\x06result\x18\x02 \x01(\v2+.workflowdefinition.WorkflowDefinitionProtoR\x06result\"\x8a\x01\n" +
	"\x1eListWorkflowDefinitionsRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x1e\n" +
	"\n" +
	"tenantCode\x18\x02 \x01(\tR\n" +
	"tenantCode\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x05R\bpageSize\"\x7f\n" +
	"\x1cWorkflowDefinitionFindResult\x12G\n" +
	"\bentities\x18\x01 \x03(\v2+.workflowdefinition.WorkflowDefinitionProtoR\bentities\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\"\x85\x01\n" +
	"\x1fListWorkflowDefinitionsResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12H\n" +
	"\x06result\x18\x02 \x01(\v20.workflowdefinition.WorkflowDefinitionFindResultR\x06result\"g\n" +
	"\x1fDeleteWorkflowDefinitionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\x12\x1e\n" +
	"\n" +
	"tenantCode\x18\x03 \x01(\tR\n" +
	"tenantCode\"<\n" +
	" DeleteWorkflowDefinitionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xb6\x05\n" +
	"\x19WorkflowDefinitionService\x12\x85\x01\n" +
	"\x18CreateWorkflowDefinition\x123.workflowdefinition.CreateWorkflowDefinitionRequest\x1a4.workflowdefinition.CreateWorkflowDefinitionResponse\x12\x85\x01\n" +
	"\x18UpdateWorkflowDefinition\x123.workflowdefinition.UpdateWorkflowDefinitionRequest\x1a4.workflowdefinition.UpdateWorkflowDefinitionResponse\x12|\n" +
	"\x15GetWorkflowDefinition\x120.workflowdefinition.GetWorkflowDefinitionRequest\x1a1.workflowdefinition.GetWorkflowDefinitionResponse\x12\x82\x01\n" +
	"\x17ListWorkflowDefinitions\x122.workflowdefinition.ListWorkflowDefinitionsRequest\x1a3.workflowdefinition.ListWorkflowDefinitionsResponse\x12\x85\x01\n" +
	"\x18DeleteWorkflowDefinition\x123.workflowdefinition.DeleteWorkflowDefinitionRequest\x1a4.workflowdefinition.DeleteWorkflowDefinitionResponseB*Z(pb/workflowdefinition;workflowdefinitionb\x06proto3"

var (
	file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_rawDescOnce sync.Once
	file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_rawDescData []byte
)

func file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_rawDescGZIP() []byte {
	file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_rawDescOnce.Do(func() {
		file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_rawDesc), len(file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_rawDesc)))
	})
	return file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_rawDescData
}

var file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_goTypes = []any{
	(*WorkflowDefinitionProto)(nil),          // 0: workflowdefinition.WorkflowDefinitionProto
	(*CreateWorkflowDefinitionRequest)(nil),  // 1: workflowdefinition.CreateWorkflowDefinitionRequest
	(*CreateWorkflowDefinitionResponse)(nil), // 2: workflowdefinition.CreateWorkflowDefinitionResponse
	(*UpdateWorkflowDefinitionRequest)(nil),  // 3: workflowdefinition.UpdateWorkflowDefinitionRequest
	(*UpdateWorkflowDefinitionResponse)(nil), // 4: workflowdefinition.UpdateWorkflowDefinitionResponse
	(*GetWorkflowDefinitionRequest)(nil),     // 5: workflowdefinition.GetWorkflowDefinitionRequest
	(*GetWorkflowDefinitionResponse)(nil),    // 6: workflowdefinition.GetWorkflowDefinitionResponse
	(*ListWorkflowDefinitionsRequest)(nil),   // 7: workflowdefinition.ListWorkflowDefinitionsRequest
	(*WorkflowDefinitionFindResult)(nil),     // 8: workflowdefinition.WorkflowDefinitionFindResult
	(*ListWorkflowDefinitionsResponse)(nil),  // 9: workflowdefinition.ListWorkflowDefinitionsResponse
	(*DeleteWorkflowDefinitionRequest)(nil),  // 10: workflowdefinition.DeleteWorkflowDefinitionRequest
	(*DeleteWorkflowDefinitionResponse)(nil), // 11: workflowdefinition.DeleteWorkflowDefinitionResponse
}
var file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_depIdxs = []int32{
	0,  // 0: workflowdefinition.CreateWorkflowDefinitionResponse.result:type_name -> workflowdefinition.WorkflowDefinitionProto
	0,  // 1: workflowdefinition.UpdateWorkflowDefinitionResponse.result:type_name -> workflowdefinition.WorkflowDefinitionProto
	0,  // 2: workflowdefinition.GetWorkflowDefinitionResponse.result:type_name -> workflowdefinition.WorkflowDefinitionProto
	0,  // 3: workflowdefinition.WorkflowDefinitionFindResult.entities:type_name -> workflowdefinition.WorkflowDefinitionProto
	8,  // 4: workflowdefinition.ListWorkflowDefinitionsResponse.result:type_name -> workflowdefinition.WorkflowDefinitionFindResult
	1,  // 5: workflowdefinition.WorkflowDefinitionService.CreateWorkflowDefinition:input_type -> workflowdefinition.CreateWorkflowDefinitionRequest
	3,  // 6: workflowdefinition.WorkflowDefinitionService.UpdateWorkflowDefinition:input_type -> workflowdefinition.UpdateWorkflowDefinitionRequest
	5,  // 7: workflowdefinition.WorkflowDefinitionService.GetWorkflowDefinition:input_type -> workflowdefinition.GetWorkflowDefinitionRequest
	7,  // 8: workflowdefinition.WorkflowDefinitionService.ListWorkflowDefinitions:input_type -> workflowdefinition.ListWorkflowDefinitionsRequest
	10, // 9: workflowdefinition.WorkflowDefinitionService.DeleteWorkflowDefinition:input_type -> workflowdefinition.DeleteWorkflowDefinitionRequest
	2,  // 10: workflowdefinition.WorkflowDefinitionService.CreateWorkflowDefinition:output_type -> workflowdefinition.CreateWorkflowDefinitionResponse
	4,  // 11: workflowdefinition.WorkflowDefinitionService.UpdateWorkflowDefinition:output_type -> workflowdefinition.UpdateWorkflowDefinitionResponse
	6,  // 12: workflowdefinition.WorkflowDefinitionService.GetWorkflowDefinition:output_type -> workflowdefinition.GetWorkflowDefinitionResponse
	9,  // 13: workflowdefinition.WorkflowDefinitionService.ListWorkflowDefinitions:output_type -> workflowdefinition.ListWorkflowDefinitionsResponse
	11, // 14: workflowdefinition.WorkflowDefinitionService.DeleteWorkflowDefinition:output_type -> workflowdefinition.DeleteWorkflowDefinitionResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() {
	file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_init()
}
func file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_init() {
	if File_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_rawDesc), len(file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_goTypes,
		DependencyIndexes: file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_depIdxs,
		MessageInfos:      file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_msgTypes,
	}.Build()
	File_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto = out.File
	file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_goTypes = nil
	file_server_internal_infrastructure_server_grpc_proto_definitions_workflow_definition_proto_depIdxs = nil
}
